const KEY='mes-heures-data-v7',OLD_KEYS=['mes-heures-data-v6','mes-heures-data-v5','mes-heures-data-v4','mes-heures-data-v3','mes-heures-data-v2','mes-heures-data-v1'];
const currentSchedule={1:{start:'09:00',end:'18:30',minutes:540},2:{start:'09:00',end:'18:30',minutes:540},3:{start:'09:00',end:'18:30',minutes:540},4:{start:'09:00',end:'18:30',minutes:480},5:{start:'',end:'',minutes:0},6:{start:'',end:'',minutes:0},0:{start:'',end:'',minutes:0}};
const defaultConfig={weeklyTarget:35,pause:30,employmentName:'Mon emploi',employmentStart:new Date().toISOString().slice(0,10),calendarUrl:'',scheduleVersions:[{effectiveFrom:new Date().toISOString().slice(0,10),weeklyTarget:35,schedule:structuredClone(currentSchedule)}]};
let state=load(),editKind=null,editingHistoricalWeek=null;
function dateKey(d=new Date()){return d.toISOString().slice(0,10)}
function hhmm(d=new Date()){return d.toTimeString().slice(0,5)}
function mins(t){if(!t)return null;const[a,b]=t.split(':').map(Number);return a*60+b}
function fmtMinutes(m){const sign=m<0?'-':m>0?'+':'';m=Math.abs(Math.round(m));return `${sign}${Math.floor(m/60)}h${String(m%60).padStart(2,'0')}`}
function fmtPlainMinutes(m){m=Math.abs(Math.round(Number(m)||0));return `${Math.floor(m/60)}h${String(m%60).padStart(2,'0')}`}
function migrate(s){s=s||{};s.config=s.config||structuredClone(defaultConfig);s.days=s.days||{};s.employments=s.employments||[];s.historicalWeeks=Array.isArray(s.historicalWeeks)?s.historicalWeeks:[];s.initialBalanceMinutes=Number(s.initialBalanceMinutes||0);if(!s.config.scheduleVersions)s.config.scheduleVersions=[{effectiveFrom:s.config.employmentStart||dateKey(),weeklyTarget:Number(s.config.weeklyTarget||35),schedule:structuredClone(s.config.schedule||currentSchedule)}];delete s.config.schedule;for(const d of Object.values(s.days)){if(d.pauseMinutes==null&&(d.arrival||d.departure||d.workedMinutes!=null||(Array.isArray(d.segments)&&d.segments.length)))d.pauseMinutes=0}for(const w of s.historicalWeeks){w.targetMinutes=Number(w.targetMinutes??2100);w.workedMinutes=Number(w.workedMinutes??(w.targetMinutes+Number(w.deltaMinutes||0)));w.deltaMinutes=Number(w.deltaMinutes??(w.workedMinutes-w.targetMinutes));w.eventType=w.eventType||'';w.note=w.note||''}return s}
function load(){try{let raw=localStorage.getItem(KEY);if(!raw)for(const k of OLD_KEYS){raw=localStorage.getItem(k);if(raw)break}return migrate(raw?JSON.parse(raw):null)}catch{return migrate(null)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function scheduleFor(date){const vs=(state.config.scheduleVersions||[]).slice().sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom));let v=vs[0]||{weeklyTarget:35,schedule:currentSchedule};for(const x of vs)if(x.effectiveFrom<=date)v=x;return v}
function expectedFor(date){const d=new Date(date+'T12:00:00'),v=scheduleFor(date);return v.schedule?.[d.getDay()]?.minutes||0}
function validSegments(day){return Array.isArray(day?.segments)?day.segments.filter(s=>s.start):[]}
function openSegment(day){const ss=validSegments(day);return ss.length&&!ss.at(-1).end?ss.at(-1):null}
function pauseFor(day){return Math.max(0,Number(day?.pauseMinutes??0)||0)}
function worked(day){if(!day)return null;const ss=validSegments(day);if(ss.length){let total=0,complete=0;for(const s of ss)if(s.start&&s.end&&mins(s.end)>=mins(s.start)){total+=mins(s.end)-mins(s.start);complete++}return complete?Math.max(0,total-pauseFor(day)):null}if(day.workedMinutes!=null)return Math.max(0,Number(day.workedMinutes)-pauseFor(day));if(!day.arrival||!day.departure)return null;return Math.max(0,mins(day.departure)-mins(day.arrival)-Number(day.pauseMinutes??state.config.pause??0))}
function dayObj(k=dateKey()){return state.days[k]||(state.days[k]={segments:[],pauseMinutes:Number(state.config.pause||0),note:'',status:'open',source:'live'})}
function ensureDefaultPause(d){if(d.pauseMinutes==null)d.pauseMinutes=Number(state.config.pause||0)}
function frenchDate(k){return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(k+'T12:00:00'))}
function shortFrenchDate(k){return new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'numeric'}).format(new Date(k+'T12:00:00'))}
function weekStart(k=dateKey()){const d=new Date(k+'T12:00:00');d.setDate(d.getDate()-((d.getDay()+6)%7));return dateKey(d)}
function weekDays(k=dateKey()){const s=new Date(weekStart(k)+'T12:00:00');return Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return dateKey(d)})}
function weekWorked(k=dateKey()){let total=0;for(const x of weekDays(k)){const d=state.days[x],w=worked(d);if(w!=null)total+=w;if(d?.retainedMinutes!=null)total+=Number(d.retainedMinutes)}return total}
function weekTarget(k=dateKey()){return weekDays(k).reduce((a,x)=>a+expectedFor(x),0)}
function weekDelta(k=dateKey()){return weekWorked(k)-weekTarget(k)}
function balanceNow(k=dateKey()){return state.initialBalanceMinutes+state.historicalWeeks.reduce((a,w)=>a+Number(w.deltaMinutes||0),0)+weekDelta(k)}
function ensureSegments(d){if(Array.isArray(d.segments))return d.segments;if(d.arrival){d.segments=[{start:d.arrival,end:d.departure||null,label:''}];delete d.workedMinutes}return d.segments||(d.segments=[])}
function segmentText(d){const ss=validSegments(d);if(ss.length)return ss.map(s=>`${s.start}–${s.end||'…'}${s.label?` ${escapeHtml(s.label)}`:''}`).join(' · ');return `${d?.arrival||'—'} → ${d?.departure||'—'}`}
function pauseEditor(d,prefix='today'){return `<div class="field"><label for="${prefix}Pause">Pause non travaillée</label><div class="row"><input id="${prefix}Pause" type="number" min="0" step="5" value="${pauseFor(d)}"><span>min</span><button class="ghost" onclick="saveDayPause('${prefix}')">Enregistrer</button></div><div class="muted">Elle est déduite en plus des coupures entre plusieurs plages.</div></div>`}
function currentWeekEditor(k=dateKey()){const today=dateKey();return `<div class="card"><h2>Ma semaine</h2><p class="muted">Une journée normale = une seule plage + sa pause. Plusieurs plages seulement si tu interromps vraiment le travail.</p>${weekDays(k).map(x=>{const d=state.days[x],w=worked(d),future=x>today;let right='';if(future)right='À venir';else if(openSegment(d))right='En cours';else if(w!=null)right=fmtMinutes(w).replace('+','');else if(expectedFor(x)===0)right='Repos';else right='À saisir';const details=d&&validSegments(d).length?`${segmentText(d)} · pause ${pauseFor(d)} min`:d?.note?escapeHtml(d.note):'';return `<div class="history-item"><div class="row"><strong>${shortFrenchDate(x)}</strong><span>${right}</span></div>${details?`<div class="muted">${details}</div>`:''}${!future?`<button class="ghost" onclick="editWeekDay('${x}')">${w==null?'Saisir':'Modifier'}</button>`:''}</div>`}).join('')}</div>`}
function renderToday(){const k=dateKey(),d=dayObj(k),w=worked(d),exp=expectedFor(k),ss=validSegments(d),open=openSegment(d),legacy=!ss.length&&d.arrival;let actions='';if(open)actions=`<button onclick="finishWorkNow()">Je termine cette plage</button><button class="secondary" onclick="setEndTime()">Je suis déjà partie</button>`;else if(ss.length||d.departure)actions=`<button onclick="resumeWorkNow()">Je reprends le travail</button><button class="secondary" onclick="editTodaySegments()">Modifier les plages</button>`;else actions=`<button onclick="startWorkNow()">Je commence maintenant</button><button class="secondary" onclick="setStartTime()">Je suis déjà arrivée</button>`;const ww=weekWorked(k),wt=weekTarget(k),wd=ww-wt;const status=open?'Au travail':(ss.length||d.departure)?'Journée terminée':exp?'Journée prévue':'Jour non prévu';const timeline=ss.length?`<div class="field"><label>Plages de travail</label>${ss.map((s,i)=>`<div class="time-row row"><span>Plage ${i+1}</span><strong>${s.start} → ${s.end||'en cours'}</strong></div>`).join('')}</div>`:legacy?`<div class="muted">Ancien pointage continu : ${d.arrival} → ${d.departure||'…'}. Utilise « Modifier les plages » pour le découper.</div>`:'';document.querySelector('#todayView').innerHTML=`<div class="card"><div class="date">${frenchDate(k)}</div><div class="big">${w==null?'En cours':fmtMinutes(w)}</div><span class="status">${status}</span><div class="actions">${actions}</div></div><div class="card">${timeline}${(ss.length||d.departure)?pauseEditor(d):''}${w!=null?`<div class="time-row row"><span>Écart du jour</span><span class="time-value ${w-exp>=0?'positive':'negative'}">${fmtMinutes(w-exp)}</span></div>`:''}<div class="field"><label for="note">Remarque / justification</label><textarea id="note" placeholder="Réunion, dossier, événement…">${escapeHtml(d.note||'')}</textarea></div><button class="ghost" onclick="saveNote()">Enregistrer la remarque</button></div><div class="card"><h2>Cette semaine</h2><div class="row"><span>Pointé</span><strong>${fmtMinutes(ww).replace('+','')}</strong></div><div class="row"><span>Objectif</span><strong>${fmtMinutes(wt).replace('+','')}</strong></div><div class="time-row row"><span>Solde de la semaine</span><strong class="${wd>=0?'positive':'negative'}">${fmtMinutes(wd)}</strong></div>${state.historicalWeeks.length?`<div class="time-row row"><span>Solde annuel indicatif</span><strong class="${balanceNow(k)>=0?'positive':'negative'}">${fmtMinutes(balanceNow(k))}</strong></div><div class="muted">Report 2025 inclus.</div>`:''}</div>${currentWeekEditor(k)}`}
function historyEditor(k=dateKey()){return `<div class="card" id="historyEditor"><h2>Ajouter / compléter une journée</h2><div class="field"><label>Date</label><input id="histDate" type="date" max="${dateKey()}" value="${k}"></div><div class="weekgrid">${[1,2,3,4,5].map(i=>`<strong>Plage ${i}</strong><span></span><input id="hs${i}" type="time"><input id="he${i}" type="time">`).join('')}</div><div class="field"><label>Pause non travaillée (minutes)</label><input id="histPause" type="number" min="0" step="5" value="${Number(state.config.pause||0)}"><div class="row"><button class="ghost" onclick="setHistPause(0)">0</button><button class="ghost" onclick="setHistPause(10)">10</button><button class="ghost" onclick="setHistPause(30)">30</button><button class="ghost" onclick="setHistPause(45)">45</button><button class="ghost" onclick="setHistPause(60)">60</button></div><div class="muted">Pour une journée normale, garde une seule plage et indique simplement la pause. Avec plusieurs plages, cette pause s’ajoute aux coupures déjà visibles.</div></div><div class="field"><label>Remarque</label><textarea id="histNote" placeholder="Réunion, télétravail, dossier…"></textarea></div><div class="actions"><button onclick="savePastDay()">Enregistrer cette journée</button><button class="secondary" onclick="loadPastDay()">Charger la journée choisie</button></div><div id="histStatus" class="muted"></div></div>`}
function historicalWeekEditor(){if(editingHistoricalWeek==null)return '';const sorted=state.historicalWeeks.slice().sort((a,b)=>(a.weekStart||'').localeCompare(b.weekStart||'')),w=sorted[editingHistoricalWeek];if(!w)return '';const options=['','Congés','Arrêt maladie','Férié','Récup','Formation','Autre'].map(x=>`<option value="${x}" ${w.eventType===x?'selected':''}>${x||'Aucun événement'}</option>`).join('');return `<div class="card" id="historicalWeekEditor"><h2>Modifier la semaine ${w.week||''}</h2><div class="muted">Semaine du ${frenchDate(w.weekStart)}</div><div class="field"><label>Heures retenues</label><input id="histWeekWorked" type="number" min="0" step="0.25" value="${(Number(w.workedMinutes||0)/60).toFixed(2)}"></div><div class="field"><label>Objectif</label><input id="histWeekTarget" type="number" min="0" step="0.25" value="${(Number(w.targetMinutes||0)/60).toFixed(2)}"></div><div class="field"><label>Événement</label><select id="histWeekEvent">${options}</select></div><div class="field"><label>Note</label><textarea id="histWeekNote" placeholder="Congés, arrêt, précision…">${escapeHtml(w.note||'')}</textarea></div><div class="actions"><button onclick="saveHistoricalWeek()">Enregistrer la semaine</button><button class="secondary" onclick="cancelHistoricalWeekEdit()">Annuler</button></div></div>`}
function renderHistoricalWeeks(){if(!state.historicalWeeks.length)return '';const sorted=state.historicalWeeks.slice().sort((a,b)=>(a.weekStart||'').localeCompare(b.weekStart||''));let running=state.initialBalanceMinutes;const cards=sorted.map((w,i)=>{running+=Number(w.deltaMinutes||0);return {...w,_idx:i,_balance:running}}).reverse();return `<div class="card"><h2>Semaines importées</h2><p class="muted">Historique consolidé. Ici on garde les totaux fiables de l’ancien suivi, sans inventer le détail jour par jour.</p>${cards.map(w=>`<div class="history-item"><div class="row"><strong>Semaine ${w.week||''}</strong><span>${fmtPlainMinutes(w.workedMinutes)}</span></div><div class="muted">${frenchDate(w.weekStart)} · objectif ${fmtPlainMinutes(w.targetMinutes)} · écart ${fmtMinutes(w.deltaMinutes)}</div>${w.eventType?`<div><span class="status">${escapeHtml(w.eventType)}</span></div>`:''}${w.note?`<div>${escapeHtml(w.note)}</div>`:''}<div class="muted">Solde après cette semaine : ${fmtMinutes(w._balance)}</div><button class="ghost" onclick="editHistoricalWeek(${w._idx})">Modifier</button></div>`).join('')}</div>`}
function renderHistory(){const keys=Object.keys(state.days).sort().reverse();document.querySelector('#historyView').innerHTML=historyEditor()+historicalWeekEditor()+`<div class="card"><h2>Historique récent</h2>${keys.length?keys.map(k=>{const d=state.days[k],w=worked(d),e=expectedFor(k);return `<div class="history-item"><div class="row"><strong>${frenchDate(k)}</strong><span>${d.status==='absence'?escapeHtml(d.absenceType||'Absence'):w==null?'À compléter':fmtMinutes(w).replace('+','')}</span></div><div class="muted">${segmentText(d)}${w!=null?` · pause ${pauseFor(d)} min · écart ${fmtMinutes(w-e)}`:''}</div>${d.note?`<div>${escapeHtml(d.note)}</div>`:''}<button class="ghost" onclick="editPastDay('${k}')">Modifier</button></div>`}).join(''):'<p class="muted">Aucune journée enregistrée.</p>'}</div>`+renderHistoricalWeeks()+`<div class="card"><button class="secondary" onclick="exportCsv()">Exporter en CSV</button></div>`}
function renderSettings(){const c=state.config;document.querySelector('#settingsView').innerHTML=`<div class="card"><h2>Mon emploi actuel</h2><div class="field"><label>Nom</label><input id="jobName" value="${escapeAttr(c.employmentName)}"></div><div class="field"><label>Début de cet emploi</label><input id="jobStart" type="date" value="${c.employmentStart}"></div><div class="field"><label>Objectif hebdomadaire</label><input id="target" type="number" min="0" step="0.25" value="${c.weeklyTarget||35}"></div><div class="field"><label>Pause par défaut (minutes)</label><input id="pause" type="number" min="0" value="${c.pause}"></div><button onclick="saveSettings()">Enregistrer</button></div><div class="card"><h2>Reprendre un historique</h2><p class="muted">Import local uniquement. Le fichier reste sur cet appareil.</p><input id="historyFile" type="file" accept="application/json,.json"><button class="secondary" onclick="importHistory()">Importer l’historique</button><div id="importStatus" class="muted"></div></div><div class="card"><h2>Agenda professionnel</h2><div class="field"><label>Adresse de l’agenda</label><input id="calUrl" type="url" placeholder="https://…" value="${escapeAttr(c.calendarUrl||'')}"></div><button class="secondary" onclick="saveCalendar()">Enregistrer l’adresse</button><p class="muted">L’adresse est enregistrée, mais la lecture automatique de l’agenda n’est pas encore activée.</p></div>`}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function escapeAttr(s){return escapeHtml(s)}
window.startWorkNow=()=>{const d=dayObj();ensureDefaultPause(d);ensureSegments(d).push({start:hhmm(),end:null,label:''});d.status='open';save();renderAll()}
window.resumeWorkNow=()=>{const d=dayObj();ensureDefaultPause(d);ensureSegments(d);if(!openSegment(d))d.segments.push({start:hhmm(),end:null,label:''});d.status='open';save();renderAll()}
window.finishWorkNow=()=>{const d=dayObj(),s=openSegment(d);if(s)s.end=hhmm();d.status='closed';save();renderAll()}
window.setStartTime=()=>{editKind='newStart';document.querySelector('#timeDialogTitle').textContent='Heure de début';document.querySelector('#timeInput').value=hhmm();document.querySelector('#timeDialog').showModal()}
window.setEndTime=()=>{editKind='endCurrent';document.querySelector('#timeDialogTitle').textContent='Heure de fin';document.querySelector('#timeInput').value=hhmm();document.querySelector('#timeDialog').showModal()}
document.querySelector('#timeForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const t=document.querySelector('#timeInput').value,d=dayObj();ensureDefaultPause(d);if(editKind==='newStart'){ensureSegments(d).push({start:t,end:null,label:''});d.status='open'}else if(editKind==='endCurrent'){const s=openSegment(d);if(s){s.end=t;d.status='closed'}}save();renderAll()})
window.saveNote=()=>{dayObj().note=document.querySelector('#note').value;save();renderAll()}
window.saveDayPause=prefix=>{const el=document.querySelector('#'+prefix+'Pause'),d=dayObj();if(!el)return;d.pauseMinutes=Math.max(0,Number(el.value)||0);save();renderAll()}
window.setHistPause=n=>{const el=document.querySelector('#histPause');if(el)el.value=n}
window.editTodaySegments=()=>{showView('historyView');setTimeout(()=>{document.querySelector('#histDate').value=dateKey();loadPastDay();document.querySelector('#historyEditor').scrollIntoView({behavior:'smooth'})},0)}
window.editWeekDay=k=>{showView('historyView');setTimeout(()=>{document.querySelector('#histDate').value=k;loadPastDay();document.querySelector('#historyEditor').scrollIntoView({behavior:'smooth'})},0)}
window.loadPastDay=()=>{const k=document.querySelector('#histDate').value,d=state.days[k]||{},ss=Array.isArray(d.segments)?d.segments:(d.arrival&&d.departure?[{start:d.arrival,end:d.departure}]:[]);for(let i=1;i<=5;i++){document.querySelector('#hs'+i).value=ss[i-1]?.start||'';document.querySelector('#he'+i).value=ss[i-1]?.end||''}document.querySelector('#histPause').value=d.pauseMinutes??Number(state.config.pause||0);document.querySelector('#histNote').value=d.note||'';document.querySelector('#histStatus').textContent=d.status==='absence'?'Cette journée était marquée comme absence. Enregistrer des plages la remplacera.':(!state.days[k]?'Pause préremplie avec ta valeur habituelle. Modifie-la si besoin.':'')}
window.editPastDay=k=>{document.querySelector('#histDate').value=k;loadPastDay();document.querySelector('#historyEditor').scrollIntoView({behavior:'smooth'})}
window.savePastDay=()=>{const k=document.querySelector('#histDate').value,status=document.querySelector('#histStatus');if(!k){status.textContent='Choisis une date.';return}const ss=[];for(let i=1;i<=5;i++){const s=document.querySelector('#hs'+i).value,e=document.querySelector('#he'+i).value;if(!s&&!e)continue;if(!s||!e||mins(e)<=mins(s)){status.textContent=`La plage ${i} n’est pas valide.`;return}ss.push({start:s,end:e,label:''})}if(!ss.length){status.textContent='Ajoute au moins une plage de travail.';return}ss.sort((a,b)=>a.start.localeCompare(b.start));for(let i=1;i<ss.length;i++)if(mins(ss[i].start)<mins(ss[i-1].end)){status.textContent='Deux plages se chevauchent.';return}state.days[k]={segments:ss,pauseMinutes:Math.max(0,Number(document.querySelector('#histPause').value)||0),note:document.querySelector('#histNote').value.trim(),status:'closed',source:k<dateKey()?'manual-history':'manual'};save();renderAll();showView('historyView');setTimeout(()=>{const s=document.querySelector('#histStatus');if(s)s.textContent=`${frenchDate(k)} enregistrée.`},0)}
window.editHistoricalWeek=i=>{editingHistoricalWeek=i;renderHistory();setTimeout(()=>document.querySelector('#historicalWeekEditor')?.scrollIntoView({behavior:'smooth'}),0)}
window.cancelHistoricalWeekEdit=()=>{editingHistoricalWeek=null;renderHistory()}
window.saveHistoricalWeek=()=>{const sorted=state.historicalWeeks.slice().sort((a,b)=>(a.weekStart||'').localeCompare(b.weekStart||'')),w=sorted[editingHistoricalWeek];if(!w)return;const workedH=Math.max(0,Number(document.querySelector('#histWeekWorked').value)||0),targetH=Math.max(0,Number(document.querySelector('#histWeekTarget').value)||0);w.workedMinutes=Math.round(workedH*60);w.targetMinutes=Math.round(targetH*60);w.deltaMinutes=w.workedMinutes-w.targetMinutes;w.eventType=document.querySelector('#histWeekEvent').value;w.note=document.querySelector('#histWeekNote').value.trim();editingHistoricalWeek=null;save();renderAll();showView('historyView')}
window.saveSettings=()=>{state.config.employmentName=document.querySelector('#jobName').value||'Mon emploi';state.config.employmentStart=document.querySelector('#jobStart').value;state.config.weeklyTarget=Number(document.querySelector('#target').value)||0;state.config.pause=Number(document.querySelector('#pause').value)||0;save();renderAll()}
window.saveCalendar=()=>{state.config.calendarUrl=document.querySelector('#calUrl').value.trim();save();renderAll()}
window.importHistory=async()=>{const el=document.querySelector('#historyFile'),status=document.querySelector('#importStatus');if(!el.files?.[0]){status.textContent='Choisis d’abord le fichier d’import.';return}try{const imp=JSON.parse(await el.files[0].text());if(imp.format!=='mes-heures-import-v1')throw Error('Format non reconnu');const today=structuredClone(state.days[dateKey()]||null);state.initialBalanceMinutes=Number(imp.initialBalanceMinutes||0);state.historicalWeeks=imp.historicalWeeks||[];for(const[k,d]of Object.entries(imp.days||{})){if(k===dateKey()&&today)continue;state.days[k]=d}if(imp.scheduleVersions?.length)state.config.scheduleVersions=imp.scheduleVersions;if(imp.weeklyTarget!=null)state.config.weeklyTarget=Number(imp.weeklyTarget);state=migrate(state);save();status.textContent='Import terminé. Le pointage d’aujourd’hui a été conservé.';renderAll()}catch(e){status.textContent='Import impossible : '+e.message}}
window.exportCsv=()=>{const rows=[['date','plages','pause_minutes','travaille_minutes','prevu_minutes','ecart_minutes','statut','remarque']];for(const k of Object.keys(state.days).sort()){const d=state.days[k],w=worked(d);rows.push([k,validSegments(d).map(s=>s.start+'-'+(s.end||'')).join('|'),pauseFor(d),w??'',expectedFor(k),w==null?'':w-expectedFor(k),d.status||'',d.note||''])}const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='mes-heures-'+dateKey()+'.csv';a.click();URL.revokeObjectURL(a.href)}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==id));document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('#screenTitle').textContent=id==='todayView'?'Aujourd’hui':id==='historyView'?'Historique':'Réglages';if(id==='historyView')renderHistory();if(id==='settingsView')renderSettings()}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelector('#settingsBtn').onclick=()=>showView('settingsView');function renderAll(){renderToday();renderHistory();renderSettings()}save();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');