const KEY='mes-heures-data-v2';
const OLD_KEY='mes-heures-data-v1';
const currentSchedule={1:{start:'09:00',end:'18:30',minutes:540},2:{start:'09:00',end:'18:30',minutes:540},3:{start:'09:00',end:'18:30',minutes:540},4:{start:'09:00',end:'18:30',minutes:480},5:{start:'',end:'',minutes:0},6:{start:'',end:'',minutes:0},0:{start:'',end:'',minutes:0}};
const defaultConfig={weeklyTarget:35,pause:30,employmentName:'Mon emploi',employmentStart:new Date().toISOString().slice(0,10),calendarUrl:'',scheduleVersions:[{effectiveFrom:new Date().toISOString().slice(0,10),weeklyTarget:35,schedule:structuredClone(currentSchedule)}]};
let state=load();let editKind=null;
function migrate(s){s=s||{};s.config=s.config||structuredClone(defaultConfig);s.days=s.days||{};s.employments=s.employments||[];s.historicalWeeks=s.historicalWeeks||[];s.initialBalanceMinutes=Number(s.initialBalanceMinutes||0);if(!s.config.scheduleVersions){s.config.scheduleVersions=[{effectiveFrom:s.config.employmentStart||dateKey(),weeklyTarget:Number(s.config.weeklyTarget||35),schedule:structuredClone(s.config.schedule||currentSchedule)}]}delete s.config.schedule;return s}
function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY);return migrate(raw?JSON.parse(raw):null)}catch{return migrate(null)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dateKey(d=new Date()){return d.toISOString().slice(0,10)}
function hhmm(d=new Date()){return d.toTimeString().slice(0,5)}
function mins(t){if(!t)return null;const[a,b]=t.split(':').map(Number);return a*60+b}
function fmtMinutes(m){const sign=m<0?'-':m>0?'+':'';m=Math.abs(Math.round(m));return `${sign}${Math.floor(m/60)}h${String(m%60).padStart(2,'0')}`}
function scheduleFor(date){const versions=(state.config.scheduleVersions||[]).slice().sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom));let v=versions[0]||{weeklyTarget:state.config.weeklyTarget||35,schedule:currentSchedule};for(const x of versions)if(x.effectiveFrom<=date)v=x;return v}
function worked(day){if(day?.workedMinutes!=null)return Number(day.workedMinutes);if(!day?.arrival||!day?.departure)return null;return Math.max(0,mins(day.departure)-mins(day.arrival)-(day.pause??state.config.pause))}
function expectedFor(date){const d=new Date(date+'T12:00:00'),v=scheduleFor(date);return v.schedule?.[d.getDay()]?.minutes||0}
function dayObj(k=dateKey()){return state.days[k]||(state.days[k]={pause:state.config.pause,note:'',status:'open'})}
function frenchDate(k){return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(k+'T12:00:00'))}
function weekStart(k=dateKey()){const d=new Date(k+'T12:00:00');const n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return dateKey(d)}
function weekDays(k=dateKey()){const s=new Date(weekStart(k)+'T12:00:00');return Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return dateKey(d)})}
function importedDeltaBefore(k){return state.historicalWeeks.filter(w=>w.weekStart<weekStart(k)).reduce((a,w)=>a+Number(w.deltaMinutes||0),0)}
function currentWeekDelta(k=dateKey()){let actual=0,expected=0;weekDays(k).forEach(x=>{const d=state.days[x];const w=worked(d);if(w!=null)actual+=w;if(d?.retainedMinutes!=null)actual+=Number(d.retainedMinutes);expected+=expectedFor(x)});return actual-expected}
function balanceNow(){return state.initialBalanceMinutes+state.historicalWeeks.reduce((a,w)=>a+Number(w.deltaMinutes||0),0)+currentWeekDelta()}
function renderToday(){const k=dateKey(),d=dayObj(k),w=worked(d),exp=expectedFor(k);let action='';if(!d.arrival){action=`<button onclick="arriveNow()">J’arrive maintenant</button><button class="secondary" onclick="editTime('arrival')">Je suis déjà arrivée</button>`}else if(!d.departure){action=`<button onclick="leaveNow()">Je pars maintenant</button><button class="secondary" onclick="editTime('departure')">Je suis déjà partie</button>`}else{action=`<button class="secondary" onclick="editTime('arrival')">Modifier l’arrivée</button><button class="secondary" onclick="editTime('departure')">Modifier le départ</button>`}
let weekActual=0;weekDays(k).forEach(x=>{const wd=worked(state.days[x]);if(wd!=null)weekActual+=wd});
document.querySelector('#todayView').innerHTML=`<div class="card"><div class="date">${frenchDate(k)}</div><div class="big">${w==null?'En cours':fmtMinutes(w)}</div><span class="status">${d.departure?'Journée terminée':d.arrival?'Au travail':exp?'Journée prévue':'Jour non prévu'}</span><div class="actions">${action}</div></div><div class="card"><div class="time-row row"><span>Arrivée</span><span class="time-value">${d.arrival||'—'}</span></div><div class="time-row row"><span>Pause</span><span class="time-value">${d.pause} min</span></div><div class="time-row row"><span>Départ</span><span class="time-value">${d.departure||'—'}</span></div>${w!=null?`<div class="time-row row"><span>Écart du jour</span><span class="time-value ${w-exp>=0?'positive':'negative'}">${fmtMinutes(w-exp)}</span></div>`:''}<div class="field"><label for="note">Remarque / justification</label><textarea id="note" placeholder="Réunion, dossier, événement…">${escapeHtml(d.note||'')}</textarea></div><button class="ghost" onclick="saveNote()">Enregistrer la remarque</button></div><div class="card"><h2>Cette semaine</h2><div class="row"><span>Pointé jusqu’ici</span><strong>${fmtMinutes(weekActual).replace('+','')}</strong></div><div class="row"><span>Objectif</span><strong>${scheduleFor(k).weeklyTarget||state.config.weeklyTarget||35}h</strong></div>${state.historicalWeeks.length?`<div class="time-row row"><span>Solde indicatif</span><strong>${fmtMinutes(balanceNow())}</strong></div>`:''}</div>`}
function renderHistory(){const keys=Object.keys(state.days).sort().reverse();document.querySelector('#historyView').innerHTML=`<div class="card"><h2>Historique</h2>${keys.length?keys.map(k=>{const d=state.days[k],w=worked(d),e=expectedFor(k);return `<div class="history-item"><div class="row"><strong>${frenchDate(k)}</strong><span>${d.status==='absence'?escapeHtml(d.absenceType||'Absence'):w==null?'À compléter':fmtMinutes(w).replace('+','')}</span></div><div class="muted">${d.arrival||'—'} → ${d.departure||'—'}${w!=null?` · écart ${fmtMinutes(w-e)}`:''}${d.source==='import-2026'?' · importé':''}</div>${d.note?`<div>${escapeHtml(d.note)}</div>`:''}</div>`}).join(''):'<p class="muted">Aucune journée enregistrée.</p>'}</div><div class="card"><button class="secondary" onclick="exportCsv()">Exporter en CSV</button></div>`}
function renderSettings(){const c=state.config;document.querySelector('#settingsView').innerHTML=`<div class="card"><h2>Mon emploi actuel</h2><div class="field"><label>Nom</label><input id="jobName" value="${escapeAttr(c.employmentName)}"></div><div class="field"><label>Début de cet emploi</label><input id="jobStart" type="date" value="${c.employmentStart}"></div><div class="field"><label>Objectif hebdomadaire</label><input id="target" type="number" min="0" step="0.25" value="${c.weeklyTarget||35}"></div><div class="field"><label>Pause par défaut (minutes)</label><input id="pause" type="number" min="0" value="${c.pause}"></div><button onclick="saveSettings()">Enregistrer</button></div><div class="card"><h2>Reprendre un historique</h2><p class="muted">Import local uniquement. Le fichier reste sur cet appareil et n’est pas envoyé sur GitHub.</p><input id="historyFile" type="file" accept="application/json,.json"><button class="secondary" onclick="importHistory()">Importer l’historique</button><div id="importStatus" class="muted"></div></div><div class="card"><h2>Agenda professionnel</h2><p class="muted">Connexion prévue ici. L’adresse reste sur cet appareil et n’est jamais publiée dans le code.</p><div class="field"><label>Adresse de l’agenda</label><input id="calUrl" type="url" placeholder="https://…" value="${escapeAttr(c.calendarUrl||'')}"></div><button class="secondary" onclick="saveCalendar()">Enregistrer l’adresse</button></div><div class="card"><h2>Changement de boulot</h2><p class="muted">Un nouvel emploi repart avec un nouveau compteur. L’ancien historique reste conservé.</p><button class="danger" onclick="newEmployment()">Commencer un nouvel emploi</button></div>`}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escapeAttr(s){return escapeHtml(String(s||''))}
window.arriveNow=()=>{const d=dayObj();d.arrival=hhmm();d.departure=null;delete d.workedMinutes;d.status='open';save();renderAll()};window.leaveNow=()=>{const d=dayObj();d.departure=hhmm();delete d.workedMinutes;d.status='closed';save();renderAll()};window.editTime=(kind)=>{editKind=kind;const d=dayObj();document.querySelector('#timeDialogTitle').textContent=kind==='arrival'?'Heure d’arrivée':'Heure de départ';document.querySelector('#timeInput').value=d[kind]||hhmm();document.querySelector('#timeDialog').showModal()};document.querySelector('#timeForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const d=dayObj();d[editKind]=document.querySelector('#timeInput').value;delete d.workedMinutes;if(editKind==='departure')d.status='closed';save();renderAll()});window.saveNote=()=>{dayObj().note=document.querySelector('#note').value;save();renderAll()};
window.saveSettings=()=>{state.config.employmentName=document.querySelector('#jobName').value||'Mon emploi';state.config.employmentStart=document.querySelector('#jobStart').value;state.config.weeklyTarget=Number(document.querySelector('#target').value)||0;state.config.pause=Number(document.querySelector('#pause').value)||0;save();renderAll()};window.saveCalendar=()=>{state.config.calendarUrl=document.querySelector('#calUrl').value.trim();save();renderAll()};window.newEmployment=()=>{if(!confirm('Commencer un nouvel emploi avec un compteur neuf ? L’historique actuel sera archivé.'))return;state.employments.push({ended:dateKey(),config:structuredClone(state.config),days:structuredClone(state.days),historicalWeeks:structuredClone(state.historicalWeeks),initialBalanceMinutes:state.initialBalanceMinutes});state=migrate(null);state.config.employmentStart=dateKey();save();showView('settingsView')};
window.importHistory=async()=>{const el=document.querySelector('#historyFile'),status=document.querySelector('#importStatus');if(!el.files?.[0]){status.textContent='Choisis d’abord le fichier d’import.';return}try{const imp=JSON.parse(await el.files[0].text());if(imp.format!=='mes-heures-import-v1')throw new Error('Format non reconnu');const liveToday=structuredClone(state.days[dateKey()]||null);state.initialBalanceMinutes=Number(imp.initialBalanceMinutes||0);state.historicalWeeks=imp.historicalWeeks||[];for(const [k,d] of Object.entries(imp.days||{})){if(k===dateKey()&&liveToday)continue;state.days[k]=d}if(Array.isArray(imp.scheduleVersions)&&imp.scheduleVersions.length)state.config.scheduleVersions=imp.scheduleVersions;if(imp.weeklyTarget!=null)state.config.weeklyTarget=Number(imp.weeklyTarget);save();status.textContent=`Import terminé : ${Object.keys(imp.days||{}).length} journées lues. Le pointage d’aujourd’hui a été conservé.`;renderAll()}catch(e){status.textContent='Import impossible : '+e.message}};
window.exportCsv=()=>{const rows=[['date','arrivee','depart','pause_minutes','travaille_minutes','prevu_minutes','ecart_minutes','statut','remarque']];Object.keys(state.days).sort().forEach(k=>{const d=state.days[k],w=worked(d);rows.push([k,d.arrival||'',d.departure||'',d.pause??state.config.pause,w??'',expectedFor(k),w==null?'':w-expectedFor(k),d.status||'',d.note||''])});const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='mes-heures-'+dateKey()+'.csv';a.click();URL.revokeObjectURL(a.href)};
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==id));document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('#screenTitle').textContent=id==='todayView'?'Aujourd’hui':id==='historyView'?'Historique':'Réglages';if(id==='historyView')renderHistory();if(id==='settingsView')renderSettings()}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelector('#settingsBtn').onclick=()=>showView('settingsView');function renderAll(){renderToday();renderHistory();renderSettings()}save();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');