/* Mes heures - règles métier uniques : planning, événements, prévisions et compteurs */
window.MH = window.MH || {};
(function(MH){
  'use strict';
  const C=MH.core;
  const S=()=>C.state, cfg=()=>S().config;
  const NEUTRAL_TYPES=new Set(['Congé','Congé exceptionnel','Arrêt maladie','Férié']);
  function plans(includeArchived=false){return (cfg().planningProfiles||[]).filter(p=>includeArchived||!p.archived)}
  function planBy(id){return(cfg().planningProfiles||[]).find(p=>p.id===id)||null}
  function typeBy(id){return(cfg().dayTypes||[]).find(t=>t.id===id)||null}
  function principalPlan(){return plans().find(p=>p.role==='principal')||planBy('normal')||plans()[0]||null}
  function planDays(plan,k,pending=false){if(!plan)return{};const versions=(plan.versions||[]).filter(v=>v.effectiveFrom<=k&&(v.status==='validated'||pending&&v.status==='pending')).sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom));return C.clone(versions.length?versions.at(-1).days:(plan.days||{}))}
  function activePeriod(k,pending=false){return(cfg().planningPeriods||[]).map((p,i)=>({p,i})).filter(x=>x.p.start<=k&&x.p.end>=k&&(x.p.status==='validated'||pending&&x.p.status==='pending')).sort((a,b)=>b.p.start.localeCompare(a.p.start)||b.i-a.i)[0]?.p||null}
  function activePlan(k,pending=false){return planBy(activePeriod(k,pending)?.profileId)||principalPlan()}
  function plannedType(k,pending=false){const p=activePlan(k,pending),days=planDays(p,k,pending),dow=String(new Date(k+'T12:00:00').getDay());return typeBy(days[dow])||null}
  function baseDay(k){const o=cfg().dayOverridesV32?.[k]||null,t=(o?.dayTypeId&&typeBy(o.dayTypeId))||plannedType(k),part=o?.part||'full';if(!t)return{type:null,part:'full',start:'',end:'',minutes:0,pause:0,boundary:''};if(part==='full')return{type:t,part,start:t.start||'',end:t.end||'',minutes:Math.max(0,Number(t.minutes)||0),pause:Math.max(0,Number(t.pause)||0),boundary:''};const start=part==='morning'?(t.start||''):(o?.boundary||'13:30'),end=part==='morning'?(o?.boundary||'12:00'):(t.end||''),a=C.mins(start),b=C.mins(end);return{type:t,part,start,end,minutes:a!=null&&b!=null?Math.max(0,b-a):Math.round((Number(t.minutes)||0)/2),pause:0,boundary:o?.boundary||''}}
  function easter(y){const a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=y%100,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-Math.floor(b/4)-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*(b%4)+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),da=((h+l-7*m+114)%31)+1;return new Date(y,mo-1,da,12)}
  function holidays(y){const map=new Map(),fixed=[[1,1,'Jour de l’an'],[5,1,'Fête du Travail'],[5,8,'Victoire 1945'],[7,14,'Fête nationale'],[8,15,'Assomption'],[11,1,'Toussaint'],[11,11,'Armistice'],[12,25,'Noël']];for(const[mo,d,n]of fixed)map.set(C.localKey(new Date(y,mo-1,d,12)),n);const e=easter(y),ek=C.localKey(e);map.set(C.addDays(ek,1),'Lundi de Pâques');map.set(C.addDays(ek,39),'Ascension');map.set(C.addDays(ek,50),'Lundi de Pentecôte');if(cfg().alsaceMoselle){map.set(C.localKey(new Date(y,11,26,12)),'Saint-Étienne');const gf=new Date(e);gf.setDate(gf.getDate()-2);map.set(C.localKey(gf),'Vendredi saint')}return map}
  function holidayFor(k){return holidays(Number(k.slice(0,4))).get(k)||''}
  function storedEventsFor(k,pending=false){return(cfg().futureEvents||[]).filter(e=>e.start<=k&&e.end>=k&&(e.status==='validated'||pending&&e.status==='pending'))}
  function eventsFor(k,pending=false){const out=storedEventsFor(k,pending).slice(),h=holidayFor(k);if(h&&!out.some(e=>e.type==='Férié'))out.push({id:'holiday:'+k,type:'Férié',comment:h,start:k,end:k,part:'full',splitTime:'',status:'validated',automatic:true});return out}
  function segmentWork(base,part,split){if(part==='full')return 0;const a=C.mins(base.start),b=C.mins(base.end),s=C.mins(split||(part==='morning'?'13:30':'12:00'));if(a==null||b==null||s==null)return Math.round(base.minutes/2);return part==='morning'?Math.max(0,b-Math.max(a,s)):Math.max(0,Math.min(b,s)-a)}
  function dayExpectation(k,pending=false){
    const base=baseDay(k),events=eventsFor(k,pending);let required=base.minutes,credit=0,requiredPause=base.pause;
    for(const e of events){if(e.status!=='validated'&&!pending)continue;const part=e.part||'full';if(NEUTRAL_TYPES.has(e.type)){const work=part==='full'?0:segmentWork(base,part,e.splitTime);required=Math.min(required,work);credit=Math.max(credit,Math.max(0,base.minutes-work));requiredPause=part==='full'?0:0}else if(e.type==='Récup'){const work=part==='full'?0:segmentWork(base,part,e.splitTime);required=Math.min(required,work);requiredPause=0}}
    if(base.part!=='full')requiredPause=0;
    const retained=Math.max(0,required+credit);
    return{date:k,base,events,requiredWork:Math.max(0,Math.round(required)),credit:Math.max(0,Math.round(credit)),retainedForecast:Math.max(0,Math.round(retained)),requiredPause:Math.max(0,Math.round(requiredPause))}
  }
  function forecastMinutes(k,pending=false){return dayExpectation(k,pending).retainedForecast}
  function requiredWorkMinutes(k){return dayExpectation(k).requiredWork}
  function accountedMinutes(k){const x=dayExpectation(k),day=S().days[k],w=day?C.worked(day):null;return (w==null?0:w)+x.credit+Number(day?.retainedMinutes||0)}
  function weekForecast(ws,pending=false){return C.weekDays(ws).reduce((n,k)=>n+forecastMinutes(k,pending),0)}
  function scheduleFor(k){const vs=(cfg().scheduleVersions||[]).slice().sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom));let v=vs[0]||{weeklyTarget:Number(cfg().weeklyTarget||35)};for(const x of vs)if(x.effectiveFrom<=k)v=x;return v}
  function weeklyObjective(k=C.dateKey()){return Math.round(Number(scheduleFor(C.weekStart(k))?.weeklyTarget??cfg().weeklyTarget??35)*60)}
  function weekAccounted(ws=C.weekStart()){const hist=(S().historicalWeeks||[]).find(w=>w.weekStart===C.weekStart(ws));if(hist)return Number(hist.workedMinutes||0);return C.weekDays(ws).reduce((n,k)=>n+accountedMinutes(k),0)}
  function weekActualWorked(ws=C.weekStart()){return C.weekDays(ws).reduce((n,k)=>{const w=C.worked(S().days[k]);return n+(w==null?0:w)},0)}
  function remainingThisWeek(k=C.dateKey()){return Math.max(0,weeklyObjective(k)-weekAccounted(C.weekStart(k)))}
  function paidForWeek(ws){return(S().balanceAdjustments||[]).filter(x=>x.weekStart===ws).reduce((n,x)=>n+Number(x.minutes||0),0)}
  function historicalCarryBefore(ws){let b=Number(S().initialBalanceMinutes||0);const hist=(S().historicalWeeks||[]).slice().sort((a,z)=>a.weekStart.localeCompare(z.weekStart));const histSet=new Set(hist.map(w=>w.weekStart));for(const w of hist)if(w.weekStart<ws)b+=Number(w.deltaMinutes||0);for(const a of(S().balanceAdjustments||[]))if(a.weekStart<ws&&!histSet.has(a.weekStart))b-=Number(a.minutes||0);return Math.round(b)}
  function currentBalance(){return historicalCarryBefore(C.weekStart(C.dateKey()))}
  function openingAtYear(y){return historicalCarryBefore(C.firstMonday(y))}
  function annualObjective(y){return C.mondays(y).reduce((n,ws)=>n+weeklyObjective(ws),0)}
  function annualProjection(y){const today=C.dateKey(),hist=new Map((S().historicalWeeks||[]).map(w=>[w.weekStart,w]));let n=0;for(const ws of C.mondays(y)){const h=hist.get(ws);if(h){n+=Number(h.workedMinutes||0);continue}if(ws===C.weekStart(today)){n+=weekAccounted(ws)+Math.max(0,weekForecast(ws)-C.weekDays(ws).filter(k=>k<=today).reduce((s,k)=>s+forecastMinutes(k),0));continue}if(ws<C.weekStart(today)){n+=weekAccounted(ws);continue}n+=weekForecast(ws)}return Math.round(n)}
  function annualRealized(y){const today=C.dateKey(),hist=new Map((S().historicalWeeks||[]).map(w=>[w.weekStart,w]));let n=0;for(const ws of C.mondays(y)){if(ws>C.weekStart(today))break;const h=hist.get(ws);if(h)n+=Number(h.workedMinutes||0);else n+=weekAccounted(ws)}return Math.round(n)}
  function weekInfo(ws){const codes=new Set(),events=[],hols=[],overrides=[],days=[];let minutes=0,pending=false;for(const k of C.weekDays(ws)){const p=activePlan(k);if(p)codes.add(p.code||p.name);const ex=dayExpectation(k,true);minutes+=ex.retainedForecast;for(const e of ex.events){if(e.automatic){if(!hols.includes(e.comment))hols.push(e.comment)}else{if(!events.includes(e.type))events.push(e.type);if(e.status==='pending')pending=true}}if(cfg().dayOverridesV32?.[k])overrides.push(k);days.push({k,plan:p,expectation:ex})}const principal=principalPlan()?.code||'';return{ws,code:codes.size>1?'MIXTE':([...codes][0]||'—'),minutes,events,holidays:hols,overrides,pending,special:codes.size>1||events.length||hols.length||overrides.length||[...codes].some(c=>c!==principal),days}}
  function assignPlanningRange(profileId,start,end,status='validated'){if(!start||!end||end<start)throw new Error('Période invalide');cfg().planningPeriods=Array.isArray(cfg().planningPeriods)?cfg().planningPeriods:[];const principal=principalPlan(),next=[];for(const p of cfg().planningPeriods){if(p.end<start||p.start>end){next.push(p);continue}if(p.start<start)next.push({...p,id:C.uid('per'),end:C.addDays(start,-1)});if(p.end>end)next.push({...p,id:C.uid('per'),start:C.addDays(end,1)})}if(profileId&&profileId!==principal?.id)next.push({id:C.uid('per'),profileId,start,end,status,createdAt:C.dateKey()});next.sort((a,b)=>a.start.localeCompare(b.start));const merged=[];for(const p of next){const prev=merged.at(-1);if(prev&&prev.profileId===p.profileId&&prev.status===p.status&&C.addDays(prev.end,1)===p.start)prev.end=p.end;else merged.push(p)}cfg().planningPeriods=merged;C.save();return merged}
  function removePlanningPeriod(id){cfg().planningPeriods=(cfg().planningPeriods||[]).filter(p=>p.id!==id);C.save()}
  function saveDayOverride(k,data){cfg().dayOverridesV32=cfg().dayOverridesV32||{};cfg().dayOverridesV32[k]={dayTypeId:data.dayTypeId||plannedType(k)?.id||'',part:data.part||'full',boundary:data.part==='full'?'':data.boundary||'',updatedAt:C.dateKey()};C.save()}
  function removeDayOverride(k){if(cfg().dayOverridesV32)delete cfg().dayOverridesV32[k];C.save()}
  function upsertEvent(data,id=''){cfg().futureEvents=Array.isArray(cfg().futureEvents)?cfg().futureEvents:[];const clean={type:data.type||'Autre',comment:String(data.comment||'').trim(),start:data.start,end:data.end,part:data.part||'full',splitTime:data.part==='full'?'':data.splitTime||'',status:data.status||'validated'};if(!clean.start||!clean.end||clean.end<clean.start)throw new Error('Période invalide');let e=id?cfg().futureEvents.find(x=>x.id===id):null;if(e)Object.assign(e,clean,{updatedAt:C.dateKey(),validatedAt:clean.status==='validated'?(e.validatedAt||C.dateKey()):''});else{e={id:C.uid('evt'),createdAt:C.dateKey(),...clean,validatedAt:clean.status==='validated'?C.dateKey():''};cfg().futureEvents.push(e)}C.save();return e}
  function removeEvent(id){cfg().futureEvents=(cfg().futureEvents||[]).filter(e=>e.id!==id);C.save()}
  function validateEvent(id){const e=(cfg().futureEvents||[]).find(x=>x.id===id);if(!e)return false;e.status='validated';e.validatedAt=C.dateKey();C.save();return true}
  function saveDayActual(k,{segments,pauseMinutes,note}){const d=C.dayObj(k);d.segments=(segments||[]).filter(s=>s.start).map(s=>({start:s.start,end:s.end||null,label:s.label||''}));d.pauseMinutes=Math.max(0,Number(pauseMinutes)||0);d.note=String(note||'');d.status=C.openSegment(d)?'open':'closed';d.source=d.source||'manual';C.save();return d}
  function saveDayType(data,id=''){const a=C.mins(data.start),b=C.mins(data.end),pause=Math.max(0,Number(data.pause)||0);if(!data.code||!data.name)throw new Error('Code et nom nécessaires');if((data.start&&!data.end)||(!data.start&&data.end))throw new Error('Renseigne le début et la fin, ou laisse les deux vides');if(a!=null&&b!=null&&b<a)throw new Error('La fin doit être après le début');const code=String(data.code).trim().toUpperCase().slice(0,4);if((cfg().dayTypes||[]).some(t=>t.id!==id&&String(t.code).toUpperCase()===code))throw new Error('Ce code est déjà utilisé');const values={code,name:String(data.name).trim(),description:String(data.description||'').trim(),start:data.start||'',end:data.end||'',pause,minutes:a!=null&&b!=null?Math.max(0,b-a-pause):0};let t=id?typeBy(id):null;if(t)Object.assign(t,values);else{t={id:C.uid('type'),...values};cfg().dayTypes.push(t)}C.save();return t}
  function deleteDayType(id){if((cfg().dayTypes||[]).length<=1)throw new Error('Il faut garder au moins une journée type');const used=plans(true).some(p=>Object.values(p.days||{}).includes(id)||(p.versions||[]).some(v=>Object.values(v.days||{}).includes(id)));if(used)throw new Error('Cette journée type est encore utilisée dans un planning');cfg().dayTypes=cfg().dayTypes.filter(t=>t.id!==id);C.save()}
  function createPlanning({name,code,baseId}){if(!name||!code)throw new Error('Nom et code nécessaires');if(plans(true).some(p=>p.code.toUpperCase()===String(code).toUpperCase()))throw new Error('Ce code est déjà utilisé');const base=planBy(baseId)||principalPlan(),count=plans().length,role=count===0?'principal':count===1?'secondary':count===2?'exceptional':'extra',p={id:C.uid('plan'),name:String(name).trim(),code:String(code).trim().toUpperCase().slice(0,6),role,days:C.clone(planDays(base,C.dateKey())),versions:[],archived:false};cfg().planningProfiles.push(p);C.save();return p}
  function savePlanningVersion(id,{name,code,effectiveFrom,status,days}){const p=planBy(id);if(!p)throw new Error('Planning introuvable');if(!name||!code||!effectiveFrom)throw new Error('Nom, code et date d’effet nécessaires');if(plans(true).some(x=>x.id!==id&&x.code.toUpperCase()===String(code).toUpperCase()))throw new Error('Ce code est déjà utilisé');p.name=String(name).trim();p.code=String(code).trim().toUpperCase().slice(0,6);p.versions.push({id:C.uid('ver'),effectiveFrom,status:status||'validated',days:C.clone(days||{}),createdAt:C.dateKey(),validatedAt:status==='pending'?'':C.dateKey()});C.save();return p}
  function archivePlanning(id){const p=planBy(id);if(!p||p.role==='principal')return false;p.archived=true;C.save();return true}
  function saveProfile(data){Object.assign(cfg(),{personName:String(data.personName||'').trim(),employmentName:String(data.employmentName||'').trim()||'Mon emploi',employmentStart:data.employmentStart||cfg().employmentStart,contractEnd:data.contractEnd||'',weeklyTarget:Math.max(0,Number(data.weeklyTarget)||0),pause:Math.max(0,Number(data.pause)||0),calendarUrl:String(data.calendarUrl??cfg().calendarUrl??'').trim()});const today=C.dateKey(),vs=cfg().scheduleVersions||(cfg().scheduleVersions=[]),last=vs.slice().sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom)).at(-1);if(last&&last.effectiveFrom===today)last.weeklyTarget=cfg().weeklyTarget;else if(!last||Number(last.weeklyTarget)!==cfg().weeklyTarget)vs.push({effectiveFrom:today,weeklyTarget:cfg().weeklyTarget,schedule:C.clone(C.DEFAULT_SCHEDULE)});C.save()}
  function saveAlerts(data){cfg().balanceAlertNegative=Math.max(0,Number(data.negative)||0);cfg().balanceAlertPositive=Math.max(0,Number(data.positive)||0);cfg().balanceReturnDelayValue=data.delayValue===''?'':Math.max(1,Math.round(Number(data.delayValue)||1));cfg().balanceReturnDelayUnit=['days','weeks','months'].includes(data.delayUnit)?data.delayUnit:'weeks';C.save()}
  function thresholdStatus(balance=currentBalance()){const neg=Math.abs(Number(cfg().balanceAlertNegative||0))*60,pos=Math.abs(Number(cfg().balanceAlertPositive||0))*60;let side='',limit=0;if(neg&&balance<-neg){side='low';limit=-neg}else if(pos&&balance>pos){side='high';limit=pos}if(!side){cfg().balanceAlertTracking=null;C.save();return null}let tr=cfg().balanceAlertTracking;if(!tr||tr.side!==side){tr=cfg().balanceAlertTracking={side,since:C.dateKey()};C.save()}const excess=Math.abs(balance-limit);let deadline='';const val=Number(cfg().balanceReturnDelayValue||0);if(val){if(cfg().balanceReturnDelayUnit==='days')deadline=C.addDays(tr.since,val);else if(cfg().balanceReturnDelayUnit==='weeks')deadline=C.addDays(tr.since,val*7);else{const d=new Date(tr.since+'T12:00:00'),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+val);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));deadline=C.localKey(d)}}if(cfg().contractEnd&&(!deadline||cfg().contractEnd<deadline))deadline=cfg().contractEnd;return{side,limit,excess,since:tr.since,deadline}}
  function departureEstimate(k=C.dateKey()){const day=S().days[k],open=C.openSegment(day),x=dayExpectation(k);if(!day||!open?.start||x.requiredWork<=0)return null;let closedGross=0;for(const s of C.validSegments(day)){if(s===open)continue;const a=C.mins(s.start),b=C.mins(s.end);if(a!=null&&b!=null&&b>=a)closedGross+=b-a}const pause=Math.max(0,Number(day.pauseMinutes??x.requiredPause)||0),need=Math.max(0,x.requiredWork+pause-closedGross),start=C.mins(open.start);return start==null?null:{time:C.clock(start+need),target:x.requiredWork,pause,remainingWeek:remainingThisWeek(k)}}
  MH.domain={NEUTRAL_TYPES,plans,planBy,typeBy,principalPlan,planDays,activePeriod,activePlan,plannedType,baseDay,holidays,holidayFor,storedEventsFor,eventsFor,dayExpectation,forecastMinutes,requiredWorkMinutes,accountedMinutes,weekForecast,scheduleFor,weeklyObjective,weekAccounted,weekActualWorked,remainingThisWeek,paidForWeek,historicalCarryBefore,currentBalance,openingAtYear,annualObjective,annualProjection,annualRealized,weekInfo,assignPlanningRange,removePlanningPeriod,saveDayOverride,removeDayOverride,upsertEvent,removeEvent,validateEvent,saveDayActual,saveDayType,deleteDayType,createPlanning,savePlanningVersion,archivePlanning,saveProfile,saveAlerts,thresholdStatus,departureEstimate};
})(window.MH);
