/* Mes heures v10: éditeur compact des journées types + durée automatique */
(function(){
let dayTypeEditorOpen=false,editingDayTypeId=null;
function v10TypeById(id){return (state.config.dayTypes||[]).find(t=>t.id===id)}
function calcTypeMinutes(start,end,pause){const a=mins(start),b=mins(end),p=Math.max(0,Number(pause)||0);if(a==null||b==null||b<a)return 0;return Math.max(0,b-a-p)}
function typeForm(t){const edit=!!t,start=t?.start||'',end=t?.end||'',pause=t?.pause??state.config.pause??30,minutes=t?.minutes||0;return `<div id="dayTypeForm" class="editor-card"><div class="row"><h3>${edit?'Modifier la journée type':'Ajouter une journée type'}</h3><button class="ghost" onclick="closeDayTypeEditor()">Fermer</button></div><div class="field"><label>Nom</label><input id="newTypeName" value="${escapeAttr(t?.name||'')}" placeholder="ACM, MJC, OF…"></div><div class="weekgrid"><div class="field"><label>Début repère</label><input id="newTypeStart" type="time" value="${start}" oninput="refreshTypeDuration()"></div><div class="field"><label>Fin repère</label><input id="newTypeEnd" type="time" value="${end}" oninput="refreshTypeDuration()"></div></div><div class="field"><label>Pause habituelle (minutes)</label><input id="newTypePause" type="number" min="0" step="5" value="${pause}" oninput="refreshTypeDuration()"></div><div class="field"><label>Durée attendue</label><div id="typeDurationPreview"><strong>${fmtPlainMinutes(minutes)}</strong></div><p class="muted compact">Calculée automatiquement : fin − début − pause.</p></div><button onclick="saveDayTypeV10()">${edit?'Enregistrer les modifications':'Ajouter la journée type'}</button></div>`}
function renderDayTypesV10(){const cards=[...document.querySelectorAll('#settingsView .card')],card=cards.find(x=>x.querySelector('h2')?.textContent.trim()==='Journées types');if(!card)return;card.innerHTML=`<h2>Journées types</h2><p class="muted compact">Les horaires servent de repère. La durée attendue est calculée automatiquement et les pointages restent la réalité.</p>${state.config.dayTypes.map(t=>`<div class="daytype-card"><div class="row"><strong>${escapeHtml(t.name)}</strong><div><button class="ghost" onclick="editDayTypeV10('${t.id}')">Modifier</button><button class="ghost" onclick="deleteDayType('${t.id}')">Supprimer</button></div></div><div class="muted">${t.start&&t.end?t.start+' → '+t.end:'sans horaire'} · pause ${t.pause||0} min</div><div><strong>Durée attendue : ${fmtPlainMinutes(t.minutes)}</strong></div></div>`).join('')}<div style="margin-top:14px"><button class="secondary" onclick="openDayTypeEditorV10()">+ Ajouter une journée type</button></div>${dayTypeEditorOpen?typeForm(editingDayTypeId?v10TypeById(editingDayTypeId):null):''}`;if(dayTypeEditorOpen)setTimeout(refreshTypeDuration,0)}
const oldRenderSettingsV10=renderSettings;
renderSettings=function(){oldRenderSettingsV10();renderDayTypesV10()};
window.openDayTypeEditorV10=()=>{editingDayTypeId=null;dayTypeEditorOpen=true;renderSettings();setTimeout(()=>document.querySelector('#dayTypeForm')?.scrollIntoView({behavior:'smooth',block:'nearest'}),0)};
window.editDayTypeV10=id=>{editingDayTypeId=id;dayTypeEditorOpen=true;renderSettings();setTimeout(()=>document.querySelector('#dayTypeForm')?.scrollIntoView({behavior:'smooth',block:'nearest'}),0)};
window.closeDayTypeEditor=()=>{dayTypeEditorOpen=false;editingDayTypeId=null;renderSettings()};
window.refreshTypeDuration=()=>{const start=document.querySelector('#newTypeStart')?.value||'',end=document.querySelector('#newTypeEnd')?.value||'',pause=document.querySelector('#newTypePause')?.value||0,m=calcTypeMinutes(start,end,pause),el=document.querySelector('#typeDurationPreview');if(el)el.innerHTML=`<strong>${fmtPlainMinutes(m)}</strong>`};
window.saveDayTypeV10=()=>{const name=document.querySelector('#newTypeName')?.value.trim(),start=document.querySelector('#newTypeStart')?.value||'',end=document.querySelector('#newTypeEnd')?.value||'',pause=Math.max(0,Number(document.querySelector('#newTypePause')?.value)||0);if(!name){toast('Donne un nom à la journée type.','error');return}if((start&&!end)||(!start&&end)){toast('Renseigne le début et la fin, ou laisse les deux vides.','error');return}const minutes=start&&end?calcTypeMinutes(start,end,pause):0;if(start&&end&&mins(end)<mins(start)){toast('La fin doit être après le début.','error');return}if(editingDayTypeId){const t=v10TypeById(editingDayTypeId);if(!t)return;t.name=name;t.start=start;t.end=end;t.pause=pause;t.minutes=minutes;save();dayTypeEditorOpen=false;editingDayTypeId=null;renderAll();toast(`✓ Journée type « ${name} » modifiée.`)}else{state.config.dayTypes.push({id:'t'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),name,start,end,minutes,pause});save();dayTypeEditorOpen=false;renderAll();toast(`✓ Journée type « ${name} » ajoutée.`)}};
renderAll();
})();