/* Mes heures v11: export par période CSV + PDF imprimable */
(function(){
let exportPanelOpen=false;
function isoToday(){return dateKey()}
function monthBounds(offset=0){const d=new Date();d.setMonth(d.getMonth()+offset,1);const y=d.getFullYear(),m=d.getMonth();return [localKey(new Date(y,m,1,12)),localKey(new Date(y,m+1,0,12))]}
function escCsv(x){return '"'+String(x??'').replaceAll('"','""')+'"'}
function isoWeekNumber(k){const d=new Date(k+'T12:00:00');d.setHours(0,0,0,0);d.setDate(d.getDate()+3-((d.getDay()+6)%7));const w1=new Date(d.getFullYear(),0,4);return 1+Math.round(((d-w1)/86400000-3+((w1.getDay()+6)%7))/7)}
function rangeDates(a,b){const out=[],d=new Date(a+'T12:00:00'),end=new Date(b+'T12:00:00');while(d<=end){out.push(localKey(d));d.setDate(d.getDate()+1)}return out}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function periodValues(){const a=document.querySelector('#exportStart')?.value,b=document.querySelector('#exportEnd')?.value;if(!a||!b||b<a){toast('Choisis une période valide.','error');return null}return [a,b]}
function setExportDates(a,b){const x=document.querySelector('#exportStart'),y=document.querySelector('#exportEnd');if(x)x.value=a;if(y)y.value=b}
window.exportShortcut=kind=>{if(kind==='month')setExportDates(...monthBounds(0));if(kind==='prevmonth')setExportDates(...monthBounds(-1));if(kind==='week'){const a=weekStart(),b=weekDays().at(-1);setExportDates(a,b)}};
function dayExportRow(k){const d=state.days[k],w=worked(d),t=(typeof dayTypeFor==='function'?dayTypeFor(k):null),evt=d?.eventType||'';return {date:k,type:t?.name||'',repere:t?.start&&t?.end?`${t.start}-${t.end}`:'',plages:d?validSegments(d).map(s=>s.start+'-'+(s.end||'')).join(' | '):'',pause:d?pauseFor(d):'',worked:w,expected:expectedFor(k),event:evt,note:d?.note||''}}
function historicalInRange(a,b){return (state.historicalWeeks||[]).filter(w=>w.weekStart&&w.weekStart>=a&&w.weekStart<=b).sort((x,y)=>x.weekStart.localeCompare(y.weekStart))}
function exportCsvV11(a,b){const rows=[['Date','Semaine','Type de journée','Repère','Plages travaillées','Pause (min)','Temps travaillé (min)','Temps retenu/référence (min)','Événement/absence','Commentaire']];for(const k of rangeDates(a,b)){const r=dayExportRow(k);if(state.days[k])rows.push([r.date,isoWeekNumber(k),r.type,r.repere,r.plages,r.pause,r.worked??'',r.expected,r.event,r.note])}rows.push([]);rows.push(['SEMaines CONSOLIDÉES IMPORTÉES']);rows.push(['Début semaine','Semaine','Heures retenues (min)','Objectif (min)','Écart (min)','Événement','Note']);for(const w of historicalInRange(a,b))rows.push([w.weekStart,w.week||isoWeekNumber(w.weekStart),w.workedMinutes,w.targetMinutes,w.deltaMinutes,w.eventType||'',w.note||'']);const csv=rows.map(r=>r.map(escCsv).join(';')).join('\r\n');downloadBlob(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),`mes-heures_${a}_${b}.csv`);toast('✓ CSV de la période préparé.')}
function weeklySummary(a,b){const starts=[...new Set(rangeDates(a,b).map(k=>weekStart(k)))].sort(),hist=new Map((state.historicalWeeks||[]).map(w=>[w.weekStart,w]));let running=state.initialBalanceMinutes;const histSorted=(state.historicalWeeks||[]).slice().sort((x,y)=>(x.weekStart||'').localeCompare(y.weekStart||''));const balanceAt=new Map();for(const w of histSorted){running+=Number(w.deltaMinutes||0);balanceAt.set(w.weekStart,running)}return starts.map(s=>{const h=hist.get(s);if(h)return {s,worked:Number(h.workedMinutes||0),target:Number(h.targetMinutes||0),delta:Number(h.deltaMinutes||0),balance:balanceAt.get(s),event:h.eventType||'',note:h.note||''};const workedM=weekWorked(s),targetM=weekTarget(s),delta=workedM-targetM;let prior=state.initialBalanceMinutes+histSorted.filter(w=>w.weekStart<s).reduce((z,w)=>z+Number(w.deltaMinutes||0),0);return {s,worked:workedM,target:targetM,delta,balance:prior+delta,event:'',note:''}})}
function printableV11(a,b){const c=state.config,days=rangeDates(a,b).map(dayExportRow).filter((r,i)=>state.days[r.date]),weeks=weeklySummary(a,b),title=`Relevé d’heures du ${new Intl.DateTimeFormat('fr-FR').format(new Date(a+'T12:00:00'))} au ${new Intl.DateTimeFormat('fr-FR').format(new Date(b+'T12:00:00'))}`;const dayRows=days.length?days.map(r=>`<tr><td>${escapeHtml(r.date)}</td><td>${escapeHtml(r.type||'')}</td><td>${escapeHtml(r.plages||'')}</td><td>${r.pause===''?'':r.pause+' min'}</td><td>${r.worked==null?'':fmtPlainMinutes(r.worked)}</td><td>${escapeHtml(r.event||'')}</td><td>${escapeHtml(r.note||'')}</td></tr>`).join(''):'<tr><td colspan="7">Aucune journée détaillée sur cette période.</td></tr>';const weekRows=weeks.map(w=>`<tr><td>${escapeHtml(w.s)}</td><td>S${isoWeekNumber(w.s)}</td><td>${fmtPlainMinutes(w.worked)}</td><td>${fmtPlainMinutes(w.target)}</td><td>${fmtMinutes(w.delta)}</td><td>${w.balance==null?'':fmtMinutes(w.balance)}</td><td>${escapeHtml(w.event||'')}</td></tr>`).join('');const html=`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>@page{size:A4 landscape;margin:12mm}body{font-family:Arial,sans-serif;color:#111;font-size:11px}h1{font-size:20px;margin-bottom:4px}h2{font-size:14px;margin-top:22px}.meta{margin:3px 0}.hint{color:#555;margin:10px 0 16px}table{width:100%;border-collapse:collapse;margin-top:8px}th,td{border:1px solid #bbb;padding:5px;vertical-align:top}th{background:#eee;text-align:left}.sign{margin-top:28px;display:flex;justify-content:space-between}.sign div{width:45%;border-top:1px solid #999;padding-top:6px}</style></head><body><h1>${escapeHtml(title)}</h1><div class="meta"><strong>${escapeHtml(c.personName||'Nom non renseigné')}</strong> · ${escapeHtml(c.employmentName||'')}</div><div class="meta">Début de contrat : ${escapeHtml(c.employmentStart||'non renseigné')} · Objectif hebdomadaire : ${escapeHtml(String(c.weeklyTarget||0))} h</div><div class="hint">Document généré depuis Mes heures. Utilise « Imprimer / Enregistrer en PDF » dans la fenêtre d’impression.</div><h2>Détail des journées</h2><table><thead><tr><th>Date</th><th>Type</th><th>Plages</th><th>Pause</th><th>Travaillé</th><th>Événement</th><th>Commentaire / justification</th></tr></thead><tbody>${dayRows}</tbody></table><h2>Résumé hebdomadaire</h2><table><thead><tr><th>Début</th><th>Semaine</th><th>Retenu</th><th>Objectif</th><th>Écart</th><th>Solde cumulé</th><th>Événement</th></tr></thead><tbody>${weekRows}</tbody></table><div class="sign"><div>Signature du salarié</div><div>Visa / signature du responsable</div></div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`;const w=window.open('','_blank');if(!w){toast('Le navigateur a bloqué la fenêtre PDF. Autorise les fenêtres pour Mes heures.','error');return}w.document.open();w.document.write(html);w.document.close();toast('✓ Document prêt : choisis « Enregistrer en PDF » dans l’impression.')}
window.runExportV11=kind=>{const p=periodValues();if(!p)return;kind==='csv'?exportCsvV11(...p):printableV11(...p)};
function exportCard(){const [a,b]=monthBounds(0);return `<div class="card" id="exportV11"><div class="row"><h2>Exporter une période</h2></div><p class="muted compact">Choisis la période. Le CSV est fait pour Excel/Office ; le PDF est la version lisible à transmettre ou conserver.</p><div class="row"><button class="ghost" onclick="exportShortcut('week')">Cette semaine</button><button class="ghost" onclick="exportShortcut('month')">Ce mois</button><button class="ghost" onclick="exportShortcut('prevmonth')">Mois précédent</button></div><div class="weekgrid"><div class="field"><label>Du</label><input id="exportStart" type="date" value="${a}"></div><div class="field"><label>Au</label><input id="exportEnd" type="date" value="${b}"></div></div><div class="actions"><button onclick="runExportV11('pdf')">Préparer le PDF</button><button class="secondary" onclick="runExportV11('csv')">Télécharger le CSV</button></div><p class="muted compact">Les semaines importées sans détail quotidien restent exportées sous forme de résumé hebdomadaire, sans inventer des journées qui n’existent pas.</p></div>`}
const oldRenderHistoryV11=renderHistory;renderHistory=function(){oldRenderHistoryV11();const view=document.querySelector('#historyView');if(view&&!document.querySelector('#exportV11'))view.insertAdjacentHTML('beforeend',exportCard())};
renderAll();
})();