/* Mes heures v12: heures supplémentaires payées / régularisations du compteur */
(function(){
function ensureAdjustments(){if(!Array.isArray(state.balanceAdjustments))state.balanceAdjustments=[]}
ensureAdjustments();
function paidForWeek(s){ensureAdjustments();return state.balanceAdjustments.filter(x=>x.weekStart===s).reduce((a,x)=>a+Number(x.minutes||0),0)}
function adjustedHistoricalBalanceAt(s){let b=Number(state.initialBalanceMinutes||0);const hs=(state.historicalWeeks||[]).slice().sort((a,b)=>(a.weekStart||'').localeCompare(b.weekStart||''));for(const w of hs){if(w.weekStart>s)break;b+=Number(w.deltaMinutes||0);b-=paidForWeek(w.weekStart)}return b}
window.addPaidHoursV12=s=>{const h=prompt('Combien d’heures ont été payées et doivent sortir du compteur ?\nExemple : 5 ou 7,5');if(h===null)return;const n=Number(String(h).replace(',','.'));if(!Number.isFinite(n)||n<=0){toast('Indique un nombre d’heures supérieur à 0.','error');return}const note=prompt('Commentaire (facultatif)', 'Heures supplémentaires payées')??'Heures supplémentaires payées';ensureAdjustments();state.balanceAdjustments.push({id:'adj'+Date.now().toString(36),weekStart:s,minutes:Math.round(n*60),type:'paid_overtime',note:note.trim()});save();renderAll();showView('historyView');toast(`✓ ${fmtPlainMinutes(Math.round(n*60))} sorties du compteur.`)};
window.deletePaidHoursV12=id=>{ensureAdjustments();const x=state.balanceAdjustments.find(a=>a.id===id);if(!x)return;if(!confirm(`Supprimer cette régularisation de ${fmtPlainMinutes(x.minutes)} ?`))return;state.balanceAdjustments=state.balanceAdjustments.filter(a=>a.id!==id);save();renderAll();showView('historyView');toast('✓ Régularisation supprimée.')};
function adjustmentsCard(){ensureAdjustments();const rows=state.balanceAdjustments.slice().sort((a,b)=>b.weekStart.localeCompare(a.weekStart));return `<div class="card" id="adjustmentsV12"><h2>Heures payées / régularisations</h2><p class="muted compact">Les heures restent dans le temps réellement travaillé, mais les heures payées sortent du compteur à récupérer.</p><div class="field"><label>Semaine concernée</label><input id="paidWeekV12" type="date" value="${weekStart()}"></div><button onclick="addPaidHoursV12(weekStart(document.querySelector('#paidWeekV12').value))">+ Ajouter des heures payées</button>${rows.length?rows.map(x=>`<div class="history-item"><div class="row"><strong>Semaine ${isoWeekNumberV12(x.weekStart)}</strong><span>− ${fmtPlainMinutes(x.minutes)}</span></div><div class="muted">${escapeHtml(x.note||'Heures supplémentaires payées')} · ${escapeHtml(x.weekStart)}</div><button class="ghost" onclick="deletePaidHoursV12('${x.id}')">Supprimer</button></div>`).join(''):'<p class="muted">Aucune régularisation enregistrée.</p>'}</div>`}
function isoWeekNumberV12(k){const d=new Date(k+'T12:00:00');d.setDate(d.getDate()+3-((d.getDay()+6)%7));const w1=new Date(d.getFullYear(),0,4);return 1+Math.round(((d-w1)/86400000-3+((w1.getDay()+6)%7))/7)}
const oldBalanceNowV12=balanceNow;balanceNow=function(k=dateKey()){const raw=oldBalanceNowV12(k);ensureAdjustments();const ws=weekStart(k);return raw-state.balanceAdjustments.filter(x=>x.weekStart<=ws).reduce((a,x)=>a+Number(x.minutes||0),0)};
const oldRenderHistoricalWeeksV12=renderHistoricalWeeks;renderHistoricalWeeks=function(){if(!state.historicalWeeks.length)return oldRenderHistoricalWeeksV12();const sorted=state.historicalWeeks.slice().sort((a,b)=>(a.weekStart||'').localeCompare(b.weekStart||''));const cards=sorted.map((w,i)=>({...w,_idx:i,_paid:paidForWeek(w.weekStart),_balance:adjustedHistoricalBalanceAt(w.weekStart)})).reverse();return `<div class="card"><h2>Semaines importées</h2>${cards.map(w=>`<div class="history-item"><div class="row"><strong>Semaine ${w.week||''}</strong><span>${fmtPlainMinutes(w.workedMinutes)}</span></div><div class="muted">${frenchDate(w.weekStart)} · objectif ${fmtPlainMinutes(w.targetMinutes)} · écart ${fmtMinutes(w.deltaMinutes)}</div>${w._paid?`<div><strong>Heures payées : − ${fmtPlainMinutes(w._paid)}</strong></div>`:''}${w.eventType?`<div><span class="status">${escapeHtml(w.eventType)}</span></div>`:''}${w.note?`<div>${escapeHtml(w.note)}</div>`:''}<div><strong>Solde : ${fmtMinutes(w._balance)}</strong></div><button class="ghost" onclick="editHistoricalWeek(${w._idx})">Modifier</button></div>`).join('')}</div>`};
const oldRenderHistoryV12=renderHistory;renderHistory=function(){oldRenderHistoryV12();const view=document.querySelector('#historyView');if(view&&!document.querySelector('#adjustmentsV12')){const exp=document.querySelector('#exportV11');if(exp)exp.insertAdjacentHTML('beforebegin',adjustmentsCard());else view.insertAdjacentHTML('beforeend',adjustmentsCard())}};
renderAll();
})();