/* Mes heures v14: profil en lecture seule, modification explicite */
(function(){
function esc(v){return escapeHtml(String(v??''))}
function dateFr(v){if(!v)return 'Non renseignée';const d=new Date(v+'T12:00:00');return new Intl.DateTimeFormat('fr-FR').format(d)}
function profileDisplay(){const c=state.config;return `<div class="card" id="profileV14"><div class="row"><h2>Mon profil</h2><button class="ghost" onclick="editProfileV14()">Modifier</button></div><div class="history-item"><div class="row"><span>Nom et prénom</span><strong>${esc(c.personName||'Non renseigné')}</strong></div><div class="row"><span>Emploi / structure</span><strong>${esc(c.employmentName||'Non renseigné')}</strong></div><div class="row"><span>Début du contrat</span><strong>${dateFr(c.employmentStart)}</strong></div><div class="row"><span>Fin de contrat</span><strong>${c.contractEnd?dateFr(c.contractEnd):'Non renseignée'}</strong></div><div class="row"><span>Objectif hebdomadaire</span><strong>${Number(c.weeklyTarget||0)} h</strong></div><div class="row"><span>Pause par défaut</span><strong>${Number(c.pause||0)} min</strong></div></div></div>`}
function profileEdit(){const c=state.config;return `<div class="card" id="profileV14"><h2>Modifier mon profil</h2><div class="field"><label>Nom et prénom</label><input id="p14name" value="${escapeAttr(c.personName||'')}"></div><div class="field"><label>Emploi / structure</label><input id="p14job" value="${escapeAttr(c.employmentName||'')}"></div><div class="field"><label>Début du contrat</label><input id="p14start" type="date" value="${c.employmentStart||''}"></div><div class="field"><label>Fin de contrat (facultatif)</label><input id="p14end" type="date" value="${c.contractEnd||''}"></div><div class="field"><label>Objectif hebdomadaire</label><input id="p14target" type="number" step="0.25" value="${Number(c.weeklyTarget||0)}"></div><div class="field"><label>Pause par défaut</label><input id="p14pause" type="number" min="0" value="${Number(c.pause||0)}"></div><div class="actions"><button onclick="saveProfileV14()">Enregistrer</button><button class="secondary" onclick="cancelProfileV14()">Annuler</button></div></div>`}
function replaceProfile(html){return html.replace(/<div class="card"><h2>Mon profil<\/h2>[\s\S]*?<\/div>(?=<div class="card"><h2>Journées types)/,profileDisplay())}
const oldRenderSettingsV14=renderSettings;renderSettings=function(){oldRenderSettingsV14();const view=document.querySelector('#settingsView');if(view&&!document.querySelector('#profileV14'))view.innerHTML=replaceProfile(view.innerHTML)};
window.editProfileV14=()=>{const p=document.querySelector('#profileV14');if(p)p.outerHTML=profileEdit()};
window.cancelProfileV14=()=>{const p=document.querySelector('#profileV14');if(p)p.outerHTML=profileDisplay()};
window.saveProfileV14=()=>{const c=state.config;c.personName=document.querySelector('#p14name').value.trim();c.employmentName=document.querySelector('#p14job').value.trim()||'Mon emploi';c.employmentStart=document.querySelector('#p14start').value;c.contractEnd=document.querySelector('#p14end').value;c.weeklyTarget=Math.max(0,Number(document.querySelector('#p14target').value)||0);c.pause=Math.max(0,Number(document.querySelector('#p14pause').value)||0);const v=scheduleFor(dateKey());v.weeklyTarget=c.weeklyTarget;save();renderAll();showView('settingsView');toast('✓ Profil enregistré.');};
renderSettings();
})();