/* Mes heures v19: nomenclature des journées types */
(function(){
let open=false, editing=null;
const types=()=>state.config.dayTypes||[];
const byId=id=>types().find(t=>t.id===id);
const inferredCode=t=>String(t?.code||t?.name||'').toUpperCase().replace(/\s+/g,'').slice(0,4);
const calc=(start,end,pause)=>{const a=mins(start),b=mins(end),p=Math.max(0,Number(pause)||0);if(a==null||b==null||b<a)return 0;return Math.max(0,b-a-p)};
function counters(){[['#v19code','#v19codeCount'],['#v19name','#v19nameCount'],['#v19desc','#v19descCount']].forEach(([a,b])=>{const i=document.querySelector(a),o=document.querySelector(b);if(i&&o)o.textContent=i.value.length})}
function duration(){const s=document.querySelector('#v19start')?.value||'',e=document.querySelector('#v19end')?.value||'',p=document.querySelector('#v19pause')?.value||0,m=calc(s,e,p),o=document.querySelector('#v19duration');if(o)o.innerHTML=`<strong>${fmtPlainMinutes(m)}</strong>`}
function form(t){const code=inferredCode(t),name=t?.name||'',desc=t?.description||'',start=t?.start||'',end=t?.end||'',pause=t?.pause??state.config.pause??30,minutes=t?.minutes||0;return `<div id="v19form" class="editor-card"><div class="row"><h3>${t?'Modifier la journée type':'Ajouter une journée type'}</h3><button class="ghost" onclick="closeDayTypeV19()">Fermer</button></div><div class="field"><label>Code <span class="muted">(1 à 4 caractères)</span></label><input id="v19code" maxlength="4" value="${escapeAttr(code)}" placeholder="NORM" oninput="this.value=this.value.toUpperCase();refreshDayTypeV19()"><p class="muted compact"><span id="v19codeCount">${code.length}</span>/4 · code unique</p></div><div class="field"><label>Nom <span class="muted">(20 caractères max.)</span></label><input id="v19name" maxlength="20" value="${escapeAttr(name)}" placeholder="Normal jeudi" oninput="refreshDayTypeV19()"><p class="muted compact"><span id="v19nameCount">${name.length}</span>/20</p></div><div class="field"><label>Description <span class="muted">(facultative, 40 caractères max.)</span></label><input id="v19desc" maxlength="40" value="${escapeAttr(desc)}" placeholder="Tai-chi 12h-13h, hors travail" oninput="refreshDayTypeV19()"><p class="muted compact"><span id="v19descCount">${desc.length}</span>/40</p></div><div class="weekgrid"><div class="field"><label>Début repère</label><input id="v19start" type="time" value="${start}" oninput="refreshDayTypeV19()"></div><div class="field"><label>Fin repère</label><input id="v19end" type="time" value="${end}" oninput="refreshDayTypeV19()"></div></div><div class="field"><label>Pause habituelle (minutes)</label><input id="v19pause" type="number" min="0" step="5" value="${pause}" oninput="refreshDayTypeV19()"></div><div class="field"><label>Durée attendue</label><div id="v19duration"><strong>${fmtPlainMinutes(minutes)}</strong></div><p class="muted compact">Calculée automatiquement : fin - début - pause.</p></div><button onclick="saveDayTypeV19()">${t?'Enregistrer les modifications':'Ajouter la journée type'}</button></div>`}
function draw(){const cards=[...document.querySelectorAll('#settingsView .card')],card=cards.find(x=>x.querySelector('h2')?.textContent.trim()==='Journées types');if(!card)return;card.innerHTML=`<h2>Journées types</h2><p class="muted compact">Code unique (4 caractères max.), nom court et description facultative. Maximum 6 journées types.</p>${types().map(t=>`<div class="daytype-card"><div class="row"><strong>${escapeHtml(inferredCode(t)||'—')} · ${escapeHtml(t.name)}</strong><div><button class="ghost" onclick="editDayTypeV19('${t.id}')">Modifier</button><button class="ghost" onclick="deleteDayType('${t.id}')">Supprimer</button></div></div>${t.description?`<div class="muted">${escapeHtml(t.description)}</div>`:''}<div class="muted">${t.start&&t.end?t.start+' → '+t.end:'sans horaire'} · pause ${t.pause||0} min</div><div><strong>Durée attendue : ${fmtPlainMinutes(t.minutes)}</strong></div></div>`).join('')}<div style="margin-top:14px">${types().length<6?'<button class="secondary" onclick="openDayTypeV19()">+ Ajouter une journée type</button>':'<p class="muted compact">6/6 journées types actives.</p>'}</div>${open?form(editing?byId(editing):null):''}`;if(open)setTimeout(()=>{counters();duration()},0)}
const prev=renderSettings;renderSettings=function(){prev();draw()};
window.openDayTypeV19=()=>{if(types().length>=6){toast('Maximum 6 journées types actives.','error');return}editing=null;open=true;renderSettings();setTimeout(()=>document.querySelector('#v19form')?.scrollIntoView({behavior:'smooth',block:'nearest'}),0)};
window.editDayTypeV19=id=>{editing=id;open=true;renderSettings();setTimeout(()=>document.querySelector('#v19form')?.scrollIntoView({behavior:'smooth',block:'nearest'}),0)};
window.closeDayTypeV19=()=>{editing=null;open=false;renderSettings()};
window.refreshDayTypeV19=()=>{counters();duration()};
window.saveDayTypeV19=()=>{const code=(document.querySelector('#v19code')?.value||'').trim().toUpperCase(),name=(document.querySelector('#v19name')?.value||'').trim(),description=(document.querySelector('#v19desc')?.value||'').trim(),start=document.querySelector('#v19start')?.value||'',end=document.querySelector('#v19end')?.value||'',pause=Math.max(0,Number(document.querySelector('#v19pause')?.value)||0);if(!code||code.length>4){toast('Le code doit contenir de 1 à 4 caractères.','error');return}if(!name){toast('Donne un nom à la journée type.','error');return}if(types().some(t=>t.id!==editing&&inferredCode(t)===code)){toast(`Le code « ${code} » est déjà utilisé.`,'error');return}if((start&&!end)||(!start&&end)){toast('Renseigne le début et la fin, ou laisse les deux vides.','error');return}if(start&&end&&mins(end)<mins(start)){toast('La fin doit être après le début.','error');return}const values={code,name,description,start,end,pause,minutes:start&&end?calc(start,end,pause):0};if(editing){const t=byId(editing);if(!t)return;Object.assign(t,values)}else{if(types().length>=6){toast('Maximum 6 journées types actives.','error');return}types().push({id:'t'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),...values})}save();open=false;editing=null;renderAll();toast(`✓ Journée type « ${name} » enregistrée.`)};
renderAll();
})();