/* Mes heures v20: finitions PDF */
(function(){
const old=window.runExportV11,nativeOpen=window.open.bind(window);
const shortDates=h=>h.replace(/>(\d{2})\/(\d{2})\/\d{4}</g,'>$1/$2<');
function paid(s){return(state.balanceAdjustments||[]).filter(x=>x.weekStart===s).reduce((n,x)=>n+Number(x.minutes||0),0)}
function balanceMap(){let b=Number(state.initialBalanceMinutes||0),m=new Map();for(const w of(state.historicalWeeks||[]).slice().sort((a,z)=>a.weekStart.localeCompare(z.weekStart))){b+=Number(w.deltaMinutes||0)-paid(w.weekStart);m.set(w.weekStart,b)}return m}
function monthCarry(a){const d=new Date(a+'T12:00:00'),y=d.getFullYear(),m=d.getMonth(),x=new Date(y,m,1,12);while(x.getDay()!==1)x.setDate(x.getDate()+1);const first=localKey(x),last=new Date(y,m+1,0,12),owned=[];while(x<=last){owned.push(localKey(x));x.setDate(x.getDate()+7)}const bm=balanceMap(),hist=(state.historicalWeeks||[]).map(w=>w.weekStart).sort(),before=hist.filter(s=>s<first),opening=before.length?(bm.get(before.at(-1))??Number(state.initialBalanceMinutes||0)):Number(state.initialBalanceMinutes||0),today=dateKey(),known=owned.filter(s=>s<=today&&bm.has(s)),closing=known.length?bm.get(known.at(-1)):(owned.includes(weekStart(today))?balanceNow(weekStart(today)):opening),end=localKey(last),label=end>=today&&localKey(new Date(y,m,1,12))<=today?`À reporter au mois suivant au ${new Intl.DateTimeFormat('fr-FR').format(new Date(today+'T12:00:00'))}`:'À reporter au mois suivant';return{opening,closing,label}}
function transform(html,kind,a){if(kind==='annual'){html=html.replace('Report au ','Report au lundi ');html=shortDates(html);html=html.replace('table{width:100%;','table{width:92%;margin-left:auto;margin-right:auto;').replace('.h1{font-size:11px;', '.h1{font-size:12px;').replace('.h2{font-size:7px;white-space:nowrap;margin:1px 0 2.5px}', '.h2{font-size:7.4px;white-space:nowrap;margin:2px 0 5px}');return html.replace('</style>','.h1,.h2{margin-left:4%;margin-right:4%}th:nth-child(1){width:6%}th:nth-child(2){width:9%}th:nth-child(3),th:nth-child(4),th:nth-child(5),th:nth-child(7){width:10%}th:nth-child(6){width:12%}th:nth-child(8){width:23%}</style>')}
html=shortDates(html);html=html.replace('</style>','.days th:nth-child(1){width:7%!important}.days th:nth-child(2){width:6%!important}.days th:nth-child(3){width:24%!important}.days th:nth-child(4){width:7%!important}.days th:nth-child(5){width:8%!important}.days th:nth-child(6){width:13%!important}.days th:nth-child(7){width:35%!important}</style>');const c=monthCarry(a),top=`<div style="font-weight:700;margin:2px 0 3px">Report du mois précédent : ${fmtMinutes(c.opening)}</div>`,bottom=`<div style="font-weight:700;margin:3px 0 0">${escapeHtml(c.label)} : ${fmtMinutes(c.closing)}</div>`;html=html.replace(/(<h2>Résumé hebdomadaire<\/h2>)/,`$1${top}`);html=html.replace(/(<div class="sign">)/,`${bottom}$1`);return html}
window.runExportV11=kind=>{if(kind!=='pdf'&&kind!=='annual')return old(kind);const a=document.querySelector('#exportStart')?.value||dateKey(),original=window.open;window.open=function(){return{document:{open(){},close(){},write(h){const w=nativeOpen('','_blank');if(!w)return;w.document.open();w.document.write(transform(h,kind,a));w.document.close()}}}};try{return old(kind)}finally{window.open=original}};
})();