/* Mes heures v21: notice integree */
(function(){
let helpOpen=false;
function helpHtml(){return `<div class="card"><div class="row"><h2>Aide et mode d’emploi</h2><button class="ghost" onclick="closeHelpV21()">Fermer</button></div><p class="muted">Le guide grandit avec l’application. Parce qu’une fonction sans explication finit tôt ou tard dans le cimetière des trucs utiles mais flemme.</p></div><div class="card"><h2>Bien démarrer</h2><p>Renseigne ton emploi, ton objectif hebdomadaire, tes journées types et ton planning habituel. Le suivi se fait ensuite au quotidien depuis l’écran Aujourd’hui.</p></div><div class="card"><h2>Journées types</h2><p>Une journée type décrit un horaire habituel. Son code court sert dans les relevés PDF. Le nom reste lisible dans l’application et la description permet d’expliquer une particularité, par exemple une coupure personnelle.</p><p>La durée attendue est calculée à partir du début, de la fin et de la pause habituelle.</p></div><div class="card"><h2>Planning habituel</h2><p>Le planning associe une journée type à chaque jour de la semaine. Il sert de prévision, pas de pointage réel. On prévoit une semaine normale. La vraie vie conservera évidemment son droit de réponse.</p></div><div class="card"><h2>Au quotidien</h2><p>Enregistre tes plages de travail, ta pause et, si nécessaire, une remarque. Les heures réellement saisies restent la référence. Une journée inhabituelle peut donc différer du planning sans modifier celui-ci.</p></div><div class="card"><h2>Solde et régularisations</h2><p>Le suivi compare les heures retenues à l’objectif de la semaine. Le solde se poursuit d’une semaine à l’autre. Les heures payées ou régularisées restent travaillées mais sont déduites du compteur à récupérer.</p></div><div class="card"><h2>Exports</h2><p>Le relevé mensuel détaille les journées et résume les semaines. Le relevé annuel rassemble les semaines de l’année. Les reports permettent de suivre la continuité du solde entre les périodes.</p><p class="muted">Pour les moments où « promis, j’ai fait mes heures » ne constitue pas un justificatif.</p></div><div class="card"><h2>Sauvegarde et restauration</h2><p>Cette partie sera complétée lorsque la sauvegarde externe sera ajoutée. L’objectif sera de pouvoir retrouver l’ensemble du suivi sur un autre téléphone, pas seulement un export CSV.</p><p class="muted">Parce qu’un téléphone perdu ne devrait pas emporter six mois de travail dans sa chute.</p></div><div class="card"><h2>Mes données</h2><p>Les données personnelles du suivi sont actuellement conservées localement par l’application sur cet appareil. Le code de l’application et les données personnelles sont deux choses différentes.</p></div>`}
function drawHelp(){const s=document.querySelector('#settingsView');if(!s)return;s.innerHTML=helpHtml();document.querySelector('#screenTitle').textContent='Aide';syncButton()}
function syncButton(){const b=document.querySelector('#settingsBtn');if(!b)return;const settingsVisible=!document.querySelector('#settingsView')?.classList.contains('hidden');b.textContent=settingsVisible&&!helpOpen?'?':'⚙️';b.setAttribute('aria-label',settingsVisible&&!helpOpen?'Aide et mode d’emploi':'Réglages')}
window.openHelpV21=()=>{helpOpen=true;drawHelp()};window.closeHelpV21=()=>{helpOpen=false;renderSettings();document.querySelector('#screenTitle').textContent='Réglages';syncButton()};
const oldShow=showView;showView=function(id){helpOpen=false;oldShow(id);syncButton()};
const b=document.querySelector('#settingsBtn');if(b)b.onclick=()=>{const settingsVisible=!document.querySelector('#settingsView')?.classList.contains('hidden');if(settingsVisible&&!helpOpen)return openHelpV21();showView('settingsView')};
const oldRender=renderSettings;renderSettings=function(){oldRender();if(helpOpen)drawHelp();else syncButton()};
syncButton();
})();