/* Mes heures v22: delai de retour dans les seuils */
(function(){
const DAY=86400000;
function ensureAlertDelay(){const c=state.config;c.balanceReturnDelayValue=c.balanceReturnDelayValue??'';c.balanceReturnDelayUnit=c.balanceReturnDelayUnit||'weeks';c.balanceAlertTracking=c.balanceAlertTracking||null}
function dayDiff(a,b){const x=new Date(a+'T12:00:00'),y=new Date(b+'T12:00:00');return Math.round((Date.UTC(y.getFullYear(),y.getMonth(),y.getDate())-Date.UTC(x.getFullYear(),x.getMonth(),x.getDate()))/DAY)}
function addMonths(k,n){const d=new Date(k+'T12:00:00'),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);const last=new Date(d.getFullYear(),d.getMonth()+1,0,12).getDate();d.setDate(Math.min(day,last));return localKey(d)}
function addDelay(k,value,unit){const n=Math.max(0,Number(value)||0);if(!n)return'';if(unit==='days'){const d=new Date(k+'T12:00:00');d.setDate(d.getDate()+n);return localKey(d)}if(unit==='months')return addMonths(k,n);const d=new Date(k+'T12:00:00');d.setDate(d.getDate()+n*7);return localKey(d)}
function fr(k){return k?new Intl.DateTimeFormat('fr-FR').format(new Date(k+'T12:00:00')):''}
function sideFor(balance){const c=state.config,neg=Math.abs(Number(c.balanceAlertNegative||0))*60,pos=Math.abs(Number(c.balanceAlertPositive||0))*60;if(neg&&balance<-neg)return'low';if(pos&&balance>pos)return'high';return''}
function thresholdFor(side){const c=state.config;return side==='low'?-Math.abs(Number(c.balanceAlertNegative||0))*60:Math.abs(Number(c.balanceAlertPositive||0))*60}
function syncTracking(balance){ensureAlertDelay();const c=state.config,side=sideFor(balance),today=dateKey(),tr=c.balanceAlertTracking;if(!side){if(tr){c.balanceAlertTracking=null;save()}return null}if(!tr||tr.side!==side){c.balanceAlertTracking={side,since:today};save()}return c.balanceAlertTracking}
function deadlineInfo(track){const c=state.config,delay=addDelay(track.since,c.balanceReturnDelayValue,c.balanceReturnDelayUnit),end=c.contractEnd||'';if(delay&&end)return end<delay?{date:end,reason:'contract'}:{date:delay,reason:'delay'};if(end)return{date:end,reason:'contract'};if(delay)return{date:delay,reason:'delay'};return null}
function unitLabel(u,n){if(u==='days')return n>1?'jours':'jour';if(u==='months')return n>1?'mois':'mois';return n>1?'semaines':'semaine'}
function alertText(balance){const side=sideFor(balance);if(!side)return'';const c=state.config,track=syncTracking(balance),limit=thresholdFor(side),excess=Math.abs(balance-limit),dl=deadlineInfo(track);let parts=[`⚠️ Ton solde dépasse la zone autorisée de ${fmtPlainMinutes(excess)}.`];if(dl){const left=dayDiff(dateKey(),dl.date);if(left<0)parts.push(`Délai dépassé depuis ${Math.abs(left)} jour${Math.abs(left)>1?'s':''} (${fr(dl.date)}).`);else{const weeks=Math.max(1,Math.ceil((left+1)/7)),per=Math.ceil(excess/weeks);parts.push(`Retour dans la zone attendu avant le ${fr(dl.date)}${dl.reason==='contract'?' (fin de contrat)':''}.`);parts.push(side==='low'?`Objectif conseillé : environ +${fmtPlainMinutes(per)} par semaine.`:`À récupérer ou régulariser : environ ${fmtPlainMinutes(per)} par semaine.`)}}else parts.push('Aucune échéance n’est définie pour le retour dans la zone autorisée.');return parts.join(' ')}
function decorateToday(){const bal=balanceNow(dateKey());document.querySelectorAll('#todayView .alertline').forEach(x=>x.remove());const text=alertText(bal);if(!text)return;const card=[...document.querySelectorAll('#todayView .card')].find(x=>x.querySelector('h2')?.textContent.trim()==='Cette semaine');if(card)card.insertAdjacentHTML('beforeend',`<div class="alertline">${escapeHtml(text)}</div>`)}
const oldToday=renderToday;renderToday=function(){oldToday();decorateToday()};
function decorateSettings(){ensureAlertDelay();const c=state.config,cards=[...document.querySelectorAll('#settingsView .card')],card=cards.find(x=>x.querySelector('h2')?.textContent.trim()==='Alertes de solde');if(!card||card.querySelector('#alertDelayValue'))return;const btn=[...card.querySelectorAll('button')].find(x=>x.textContent.includes('Enregistrer les alertes'));const html=`<div class="field"><label>Délai maximum pour revenir dans la zone autorisée</label><div class="row"><input id="alertDelayValue" type="number" min="1" step="1" placeholder="Facultatif" value="${escapeAttr(c.balanceReturnDelayValue)}"><select id="alertDelayUnit"><option value="days" ${c.balanceReturnDelayUnit==='days'?'selected':''}>jours</option><option value="weeks" ${c.balanceReturnDelayUnit==='weeks'?'selected':''}>semaines</option><option value="months" ${c.balanceReturnDelayUnit==='months'?'selected':''}>mois</option></select></div><p class="muted compact">La date de fin de contrat reste prioritaire si elle arrive avant cette échéance.</p></div>`;if(btn)btn.insertAdjacentHTML('beforebegin',html)}
const oldSettings=renderSettings;renderSettings=function(){oldSettings();decorateSettings()};
const oldSave=window.saveAlerts;window.saveAlerts=()=>{const v=document.querySelector('#alertDelayValue')?.value,u=document.querySelector('#alertDelayUnit')?.value;state.config.balanceReturnDelayValue=v===''?'':Math.max(1,Math.round(Number(v)||1));state.config.balanceReturnDelayUnit=['days','weeks','months'].includes(u)?u:'weeks';oldSave();toast('✓ Seuils et délai de retour enregistrés.')};
ensureAlertDelay();renderAll();
})();