/* Mes heures v24: vue annuelle previsionnelle */
(function(){
const DAY=86400000;
const cp=o=>JSON.parse(JSON.stringify(o));
function ensure(){const c=state.config;c.planningProfiles=Array.isArray(c.planningProfiles)?c.planningProfiles:[];if(!c.planningProfiles.length)c.planningProfiles=[{id:'normal',code:'NORM',name:'Normal',days:cp(c.weekPlan||{}),archived:false}];c.planningPeriods=Array.isArray(c.planningPeriods)?c.planningPeriods:[];c.futureEvents=Array.isArray(c.futureEvents)?c.futureEvents:[];c.annualViewYear=Number(c.annualViewYear)||new Date().getFullYear()}
const prof=id=>state.config.planningProfiles.find(p=>p.id===id);
const typ=id=>(state.config.dayTypes||[]).find(t=>t.id===id);
function mondays(y){const d=new Date(y,0,1,12);while(d.getDay()!==1)d.setDate(d.getDate()+1);const a=[];while(d.getFullYear()===y){a.push(localKey(d));d.setDate(d.getDate()+7)}return a}
function wn(k){const d=new Date(k+'T12:00:00'),u=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));u.setUTCDate(u.getUTCDate()+4-(u.getUTCDay()||7));const y=new Date(Date.UTC(u.getUTCFullYear(),0,1));return Math.ceil((((u-y)/DAY)+1)/7)}
function period(k,pending=false){return state.config.planningPeriods.filter(x=>x.start<=k&&x.end>=k&&(x.status==='validated'||pending&&x.status==='pending')).sort((a,b)=>b.start.localeCompare(a.start))[0]||null}
function plan(k,pending=false){return prof(period(k,pending)?.profileId)||prof('normal')||state.config.planningProfiles[0]}
function minsFor(k,pending=false){const p=plan(k,pending),dow=String(new Date(k+'T12:00:00').getDay());return Number(typ(p?.days?.[dow])?.minutes||0)}
function event(k,pending=false){return state.config.futureEvents.find(x=>x.start<=k&&x.end>=k&&(x.status==='validated'||pending&&x.status==='pending'))||null}
function forecastDay(k,pending=false){const e=event(k,pending),m=minsFor(k,pending);return e?.type==='Récup'?0:m}
function weekInfo(ws,pending=false){const codes=new Set(),events=new Set();let m=0;for(const k of weekDays(ws)){const p=plan(k,pending);if(p)codes.add(p.code||p.name);const e=event(k,pending);if(e)events.add(e.type);m+=forecastDay(k,pending)}return{code:codes.size>1?'MIXTE':([...codes][0]||'—'),m,events:[...events]}}
function objective(y){let total=0;for(const ws of mondays(y)){const target=Math.round(Number(scheduleFor(ws)?.weeklyTarget??state.config.weeklyTarget??35)*60);const ds=weekDays(ws),weights=ds.map(minsFor),sum=weights.reduce((a,b)=>a+b,0);ds.forEach((k,i)=>{if(state.config.employmentStart&&k<state.config.employmentStart)return;if(state.config.contractEnd&&k>state.config.contractEnd)return;total+=sum?target*weights[i]/sum:0})}return Math.round(total)}
function pure(y,pending=false){let n=0;for(const ws of mondays(y))for(const k of weekDays(ws))n+=forecastDay(k,pending);return Math.round(n)}
function projection(y,pending=false){let n=0,today=dateKey();for(const ws of mondays(y)){const h=(state.historicalWeeks||[]).find(w=>w.weekStart===ws);if(h){n+=Number(h.workedMinutes||0);continue}for(const k of weekDays(ws)){if(k<today){const d=state.days[k],w=worked(d);if(w!=null)n+=w;else n+=forecastDay(k,pending)}else n+=forecastDay(k,pending)}}return Math.round(n)}
function summary(y){const o=objective(y),p=pure(y),r=projection(y),sim=projection(y,true),hasPending=state.config.planningPeriods.some(x=>x.status==='pending')||state.config.futureEvents.some(x=>x.status==='pending');return `<div class="annual-summary-v24"><div class="row"><span>Objectif annuel</span><strong>${fmtPlainMinutes(o)}</strong></div><div class="row"><span>Planning annuel prévu</span><strong>${fmtPlainMinutes(p)}</strong></div><div class="row"><span>Projection réelle + prévue</span><strong>${fmtPlainMinutes(r)}</strong></div><div class="row"><span>Écart projeté</span><strong class="${r-o>=0?'positive':'negative'}">${fmtMinutes(r-o)}</strong></div>${hasPending?`<div class="row"><span>Si les demandes sont validées</span><strong>${fmtPlainMinutes(sim)} · ${fmtMinutes(sim-o)}</strong></div>`:''}</div>`}
function cal(y){const mm=Array.from({length:12},()=>[]);mondays(y).forEach(ws=>mm[new Date(ws+'T12:00:00').getMonth()].push({ws,...weekInfo(ws)}));return mm.map((weeks,i)=>`<div class="annual-month-v24"><strong>${new Intl.DateTimeFormat('fr-FR',{month:'long'}).format(new Date(y,i,1))}</strong><div class="annual-weeks-v24">${weeks.map(w=>`<button class="annual-week-v24" onclick="annualWeekV24('${w.ws}')"><b>S${String(wn(w.ws)).padStart(2,'0')}</b><span>${escapeHtml(w.code)}</span><strong>${fmtPlainMinutes(w.m)}</strong>${w.events.length?'<small>•</small>':''}</button>`).join('')}</div></div>`).join('')}
function card(){const y=state.config.annualViewYear;return `<div class="card" id="annualV24"><div class="row"><div><h2>Prévision annuelle</h2><p class="muted compact">Le réel remplace progressivement le prévu. Les semaines futures restent des prévisions.</p></div><input style="width:82px" type="number" value="${y}" onchange="changeAnnualYearV24(this.value)"></div>${summary(y)}${cal(y)}<p class="muted compact">MIXTE = deux plannings dans la même semaine. Touche une semaine pour le détail.</p></div>`}
function decorate(){ensure();if(!document.querySelector('#v24style'))document.head.insertAdjacentHTML('beforeend','<style id="v24style">.annual-month-v24{padding:9px 0;border-top:1px solid rgba(128,128,128,.2)}.annual-month-v24>strong{display:block;margin-bottom:6px;text-transform:capitalize}.annual-weeks-v24{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:5px}.annual-week-v24{min-width:0;padding:7px 2px;border-radius:9px;display:flex;flex-direction:column;align-items:center;gap:2px;font-size:11px}.annual-week-v24 b,.annual-week-v24 strong{font-size:12px}</style>');const s=document.querySelector('#settingsView');if(!s||s.querySelector('#annualV24'))return;s.querySelector('.card')?.insertAdjacentHTML('afterend',card())}
const old=renderSettings;renderSettings=function(){old();decorate()};
window.changeAnnualYearV24=v=>{state.config.annualViewYear=Number(v)||new Date().getFullYear();save();renderSettings()};
window.annualWeekV24=ws=>{const lines=weekDays(ws).map(k=>{const p=plan(k),e=event(k);return `${new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(k+'T12:00:00'))} · ${p?.code||'—'}${e?' · '+e.type:''} · ${fmtPlainMinutes(forecastDay(k))}`});alert(`S${String(wn(ws)).padStart(2,'0')}\n\n${lines.join('\n')}`)};
ensure();save();renderAll();
})();