/* Mes heures v25: plannings dates et evenements previsionnels */
(function(){
const cp=o=>JSON.parse(JSON.stringify(o)),uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,5);
const P=()=>state.config.planningProfiles||[],by=id=>P().find(x=>x.id===id),T=id=>(state.config.dayTypes||[]).find(x=>x.id===id);
function planRows(p){return [['1','Lundi'],['2','Mardi'],['3','Mercredi'],['4','Jeudi'],['5','Vendredi'],['6','Samedi'],['0','Dimanche']].map(([d,n])=>`<div class="row"><span>${n}</span><select data-v25plan="${p.id}" data-dow="${d}">${(state.config.dayTypes||[]).map(t=>`<option value="${t.id}" ${p.days?.[d]===t.id?'selected':''}>${escapeHtml(t.code||t.name)} · ${escapeHtml(t.name)}</option>`).join('')}</select></div>`).join('')}
function plans(){return `<details class="card"><summary><strong>Plannings prévisionnels</strong><div class="muted compact">Le planning normal sert de base. Les autres s’appliquent seulement aux périodes prévues.</div></summary>${P().filter(p=>!p.archived).map(p=>`<div class="daytype-card"><div class="row"><strong>${escapeHtml(p.code)} · ${escapeHtml(p.name)}</strong>${p.id!=='normal'?`<button class="ghost" onclick="archivePlanV25('${p.id}')">Archiver</button>`:''}</div>${planRows(p)}<button class="ghost" onclick="savePlanV25('${p.id}')">Enregistrer</button></div>`).join('')}<button class="secondary" onclick="duplicatePlanV25()">+ Dupliquer le planning normal</button><h3>Périodes de planning</h3>${(state.config.planningPeriods||[]).map(x=>`<div class="history-item"><strong>${escapeHtml(by(x.profileId)?.code||'—')}</strong> · ${x.start} → ${x.end}<div class="muted">${x.status==='validated'?'Validé':'En attente de validation'}</div>${x.status==='pending'?`<button class="ghost" onclick="validatePeriodV25('${x.id}')">Marquer validé</button>`:''}<button class="ghost" onclick="removePeriodV25('${x.id}')">Retirer</button></div>`).join('')}<div class="field"><label>Planning</label><select id="v25pp">${P().filter(p=>!p.archived).map(p=>`<option value="${p.id}">${escapeHtml(p.code)} · ${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="weekgrid"><div class="field"><label>Date d’effet</label><input id="v25ps" type="date"></div><div class="field"><label>Fin</label><input id="v25pe" type="date"></div></div><div class="field"><label>Validation</label><select id="v25pv"><option value="pending">À faire valider</option><option value="validated">Déjà validé</option></select></div><button onclick="addPeriodV25()">Ajouter la période</button></details>`}
function events(){return `<details class="card"><summary><strong>Événements prévisionnels</strong><div class="muted compact">Une demande en attente peut être simulée, mais ne devient officielle qu’après validation.</div></summary>${(state.config.futureEvents||[]).map(x=>`<div class="history-item"><strong>${escapeHtml(x.type)}</strong> · ${x.start} → ${x.end}<div class="muted">${x.status==='validated'?'Validé':'En attente de validation'}</div>${x.status==='pending'?`<button class="ghost" onclick="validateEventV25('${x.id}')">Marquer validé</button>`:''}<button class="ghost" onclick="removeEventV25('${x.id}')">Retirer</button></div>`).join('')}<div class="field"><label>Type</label><select id="v25et">${['Congé','Récup','Arrêt maladie','Férié','Autre'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="weekgrid"><div class="field"><label>Du</label><input id="v25es" type="date"></div><div class="field"><label>Au</label><input id="v25ee" type="date"></div></div><div class="field"><label>Validation</label><select id="v25ev"><option value="pending">Demandé · en attente</option><option value="validated">Déjà validé</option></select></div><button onclick="addEventV25()">Ajouter l’événement</button></details>`}
function decorate(){const s=document.querySelector('#settingsView');if(!s||s.querySelector('#plansV25'))return;const a=s.querySelector('#annualV24');if(!a)return;a.insertAdjacentHTML('afterend',`<div id="plansV25">${plans()}${events()}</div>`)}
const old=renderSettings;renderSettings=function(){old();decorate()};
window.savePlanV25=id=>{const p=by(id);document.querySelectorAll(`[data-v25plan="${id}"]`).forEach(x=>p.days[x.dataset.dow]=x.value);if(id==='normal')state.config.weekPlan=cp(p.days);save();renderAll();toast('✓ Planning enregistré.')};
window.duplicatePlanV25=()=>{const name=prompt('Nom du nouveau planning','Vacances / ACM');if(!name)return;const code=(prompt('Code court','ACM')||'ACM').trim().toUpperCase().slice(0,4);if(P().some(p=>p.code===code)){toast('Ce code existe déjà.','error');return}P().push({id:uid('p'),code,name:name.trim(),days:cp(by('normal').days),archived:false});save();renderSettings();toast('✓ Planning dupliqué.')};
window.archivePlanV25=id=>{const p=by(id);if(p)p.archived=true;save();renderSettings()};
window.addPeriodV25=()=>{const start=document.querySelector('#v25ps').value,end=document.querySelector('#v25pe').value,status=document.querySelector('#v25pv').value;if(!start||!end||end<start){toast('Choisis une période valide.','error');return}state.config.planningPeriods.push({id:uid('r'),profileId:document.querySelector('#v25pp').value,start,end,status,createdAt:dateKey(),validatedAt:status==='validated'?dateKey():''});save();renderAll();toast(status==='validated'?'✓ Période validée ajoutée.':'✓ Période en attente ajoutée.')};
window.validatePeriodV25=id=>{const x=state.config.planningPeriods.find(x=>x.id===id);if(!x)return;if(x.start<dateKey()&&!confirm('La date d’effet est déjà passée. Conserver cette date rétroactive ?'))return;x.status='validated';x.validatedAt=dateKey();save();renderAll();toast('✓ Planning validé.')};
window.removePeriodV25=id=>{state.config.planningPeriods=state.config.planningPeriods.filter(x=>x.id!==id);save();renderAll()};
window.addEventV25=()=>{const start=document.querySelector('#v25es').value,end=document.querySelector('#v25ee').value,status=document.querySelector('#v25ev').value;if(!start||!end||end<start){toast('Choisis des dates valides.','error');return}state.config.futureEvents.push({id:uid('e'),type:document.querySelector('#v25et').value,start,end,status,createdAt:dateKey(),validatedAt:status==='validated'?dateKey():''});save();renderAll();toast(status==='validated'?'✓ Événement validé ajouté.':'✓ Demande ajoutée. Elle reste une simulation.')};
window.validateEventV25=id=>{const x=state.config.futureEvents.find(x=>x.id===id);if(x){x.status='validated';x.validatedAt=dateKey()}save();renderAll();toast('✓ Événement validé.')};
window.removeEventV25=id=>{state.config.futureEvents=state.config.futureEvents.filter(x=>x.id!==id);save();renderAll()};
renderAll();
})();