/* Mes heures v26: navigation, previsions et acces contextuels */
(function(){
const cp=o=>JSON.parse(JSON.stringify(o)),uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,5);
function ensure(){state.config.planningProfiles=Array.isArray(state.config.planningProfiles)?state.config.planningProfiles:[];state.config.planningPeriods=Array.isArray(state.config.planningPeriods)?state.config.planningPeriods:[];state.config.futureEvents=Array.isArray(state.config.futureEvents)?state.config.futureEvents:[];for(const e of state.config.futureEvents){if(e.comment==null)e.comment=''}}
function addViews(){const main=document.querySelector('main');if(!document.querySelector('#forecastView'))main.insertAdjacentHTML('beforeend','<section id="forecastView" class="view hidden"></section><section id="docsView" class="view hidden"></section>');const nav=document.querySelector('.bottomnav');if(nav&&!nav.querySelector('[data-view="forecastView"]'))nav.innerHTML='<button data-view="todayView" class="navbtn active">Aujourd’hui</button><button data-view="historyView" class="navbtn">Historique</button><button data-view="forecastView" class="navbtn">Prévisions</button><button data-view="docsView" class="navbtn">Docs admin</button>';nav?.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));}
function titleFor(id){return{id:'',todayView:'Aujourd’hui',historyView:'Historique',forecastView:'Prévisions',docsView:'Docs admin',settingsView:'Réglages'}[id]||'Mes heures'}
const baseShow=showView;showView=function(id){baseShow(id);document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==id));document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('#screenTitle').textContent=titleFor(id);if(id==='forecastView')renderForecastV26();if(id==='docsView')renderDocsV26()};
function trimToday(){const v=document.querySelector('#todayView');if(!v)return;[...v.querySelectorAll('.card')].forEach(c=>{if(c.querySelector('h2')?.textContent.trim()==='Ma semaine')c.remove()})}
const oldToday=renderToday;renderToday=function(){oldToday();trimToday()};
function openingAtYear(y){const d=new Date(y,0,1,12);while(d.getDay()!==1)d.setDate(d.getDate()+1);const first=localKey(d);let b=Number(state.initialBalanceMinutes||0);const paid=s=>(state.balanceAdjustments||[]).filter(x=>x.weekStart===s).reduce((n,x)=>n+Number(x.minutes||0),0);for(const w of(state.historicalWeeks||[]).slice().sort((a,z)=>a.weekStart.localeCompare(z.weekStart)))if(w.weekStart<first)b+=Number(w.deltaMinutes||0)-paid(w.weekStart);return b}
function patchAnnualSummary(card){if(!card)return;const y=Number(state.config.annualViewYear)||new Date().getFullYear(),rows=[...card.querySelectorAll('.annual-summary-v24 .row')],result=rows.find(r=>r.firstElementChild?.textContent==='Écart projeté');if(result){const raw=result.querySelector('strong')?.textContent||'0h00',m=/(-?)(\d+)h(\d+)/.exec(raw),annual=m?(m[1]? -1:1)*(Number(m[2])*60+Number(m[3])):0,carry=openingAtYear(y),final=carry+annual;result.firstElementChild.textContent='Résultat prévu de l’année';result.querySelector('strong').textContent=fmtMinutes(annual);result.insertAdjacentHTML('afterend',`<div class="row"><span>Report N-1</span><strong>${fmtMinutes(carry)}</strong></div><div class="row"><span>Report N+1 projeté</span><strong class="${final>=0?'positive':'negative'}">${fmtMinutes(final)}</strong></div>`)}}
function renderForecastV26(){ensure();const v=document.querySelector('#forecastView');if(!v)return;renderSettings();const annual=document.querySelector('#annualV24');const events=document.querySelector('#plansV25 details:nth-of-type(2)');v.innerHTML='<div class="card"><h2>Prévisions</h2><p class="muted">Ce qui est prévu pour l’année, et ce que cela devrait donner sur ton compteur.</p></div>';if(annual){patchAnnualSummary(annual);v.appendChild(annual)}if(events){events.open=true;events.querySelector('summary strong').textContent='Événements à venir';v.appendChild(events)}enhanceEvents();}
function enhanceEvents(){const v=document.querySelector('#forecastView');if(!v)return;const sel=v.querySelector('#v25et');if(sel){[...sel.options].forEach(o=>{if(o.text==='Férié')o.remove()});if(![...sel.options].some(o=>o.text==='Congé exceptionnel')){const o=document.createElement('option');o.textContent='Congé exceptionnel';sel.insertBefore(o,[...sel.options].find(x=>x.text==='Autre')||null)}}const btn=v.querySelector('button[onclick="addEventV25()"]');if(btn&&!v.querySelector('#v26eventComment')){btn.insertAdjacentHTML('beforebegin','<div class="field" id="v26eventComment"><label>Commentaire (facultatif)</label><textarea id="v26ec" placeholder="Ex. mariage de ma sœur, fermeture…"></textarea></div>')}linkDates('#v25es','#v25ee')}
const oldAddEvent=window.addEventV25;window.addEventV25=()=>{const before=state.config.futureEvents.length;oldAddEvent();if(state.config.futureEvents.length>before){state.config.futureEvents.at(-1).comment=document.querySelector('#v26ec')?.value.trim()||'';save();renderAll();if(!document.querySelector('#forecastView').classList.contains('hidden'))renderForecastV26()}};
function linkDates(a,b){const s=document.querySelector(a),e=document.querySelector(b);if(!s||!e||s.dataset.linked)return;s.dataset.linked='1';s.addEventListener('change',()=>{e.min=s.value;if(!e.value||e.value<s.value)e.value=s.value})}
function weekNo(k){const d=new Date(k+'T12:00:00'),u=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));u.setUTCDate(u.getUTCDate()+4-(u.getUTCDay()||7));const y=new Date(Date.UTC(u.getUTCFullYear(),0,1));return Math.ceil((((u-y)/86400000)+1)/7)}
window.annualWeekV24=function(ws){openWeekV26(ws)};
function planFor(k){const ps=state.config.planningPeriods.filter(x=>x.start<=k&&x.end>=k&&x.status==='validated').sort((a,b)=>b.start.localeCompare(a.start)),id=ps[0]?.profileId||'normal';return state.config.planningProfiles.find(p=>p.id===id)||state.config.planningProfiles[0]}
function openWeekV26(ws){document.querySelector('#weekDialogV26')?.remove();const days=weekDays(ws),lines=days.map(k=>{const p=planFor(k),ev=state.config.futureEvents.find(e=>e.start<=k&&e.end>=k&&e.status==='validated');return `<div class="history-item"><div class="row"><strong>${new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(k+'T12:00:00'))}</strong><span>${escapeHtml(p?.code||'—')}</span></div>${ev?`<div class="muted">${escapeHtml(ev.type)}${ev.comment?' · '+escapeHtml(ev.comment):''}</div>`:''}</div>`}).join('');document.body.insertAdjacentHTML('beforeend',`<dialog id="weekDialogV26" class="week-dialog-v26"><div class="row"><h2>S${String(weekNo(ws)).padStart(2,'0')}</h2><button class="ghost" onclick="document.querySelector('#weekDialogV26').close()">Fermer</button></div>${lines}<div class="actions v26-week-actions"><button onclick="weekPlanActionV26('${ws}')">Changer de planning</button><button class="secondary" onclick="weekEventActionV26('${ws}')">Ajouter un événement</button><button class="secondary" onclick="weekDayActionV26('${ws}')">Modifier une journée</button></div></dialog>`);document.querySelector('#weekDialogV26').showModal()}
window.weekPlanActionV26=ws=>{document.querySelector('#weekDialogV26')?.close();showView('settingsView');setTimeout(()=>{const p=document.querySelector('#plansV25');p?.scrollIntoView({behavior:'smooth'});const s=document.querySelector('#v25ps'),e=document.querySelector('#v25pe');if(s&&e){s.value=ws;e.value=weekDays(ws)[6];e.min=ws}},50)};
window.weekEventActionV26=ws=>{document.querySelector('#weekDialogV26')?.close();showView('forecastView');setTimeout(()=>{const s=document.querySelector('#v25es'),e=document.querySelector('#v25ee');if(s&&e){s.value=ws;e.value=weekDays(ws)[6];e.min=ws;s.scrollIntoView({behavior:'smooth'})}},50)};
window.weekDayActionV26=ws=>{document.querySelector('#weekDialogV26')?.close();showView('historyView');setTimeout(()=>{openHistoryEditor();const i=document.querySelector('#histDate');if(i){i.value=ws;loadPastDay();i.scrollIntoView({behavior:'smooth'})}},50)};
function renderDocsV26(){const v=document.querySelector('#docsView');if(!v)return;const now=new Date(),ym=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;v.innerHTML=`<div class="card"><h2>Docs admin</h2><p class="muted">Pour les moments où « promis, j’ai fait mes heures » ne constitue pas un justificatif.</p><div class="field"><label>Mois</label><input id="exportStart" type="date" value="${ym}"></div><div class="actions"><button onclick="runExportV11('pdf')">PDF mensuel</button><button class="secondary" onclick="runExportV11('annual')">PDF annuel</button></div></div><div class="card"><h2>Documents à venir</h2><p class="muted">Les futures demandes de congé, récup ou changement de planning auront leur place ici lorsqu’elles produiront réellement un document.</p></div>`}
function settingsMenu(){const s=document.querySelector('#settingsView');if(!s)return;const cards=[...s.children];const annual=s.querySelector('#annualV24');annual?.remove();const pv=s.querySelector('#plansV25');const ev=pv?.querySelector('details:nth-of-type(2)');ev?.remove();const groups=[];function take(title,rx){const els=cards.filter(c=>c.isConnected&&rx.test(c.textContent||''));if(els.length)groups.push({title,els})}take('Profil & contrat',/profil|emploi|contrat/i);if(pv?.isConnected)groups.push({title:'Mes plannings',els:[pv]});take('Journées types',/journée.? type/i);take('Seuils & alertes',/seuil|zone autorisée|alerte/i);take('Importer / reprendre mes données',/import|historique initial|solde de départ/i);take('Sauvegarde',/sauvegarde|restauration/i);const used=new Set(groups.flatMap(g=>g.els));const leftovers=[...s.children].filter(x=>!used.has(x));s.innerHTML='<div class="card"><h2>Réglages</h2><p class="muted">Les règles de l’application. Ce qui est prévu pour l’année vit désormais dans Prévisions.</p></div>';for(const g of groups){const d=document.createElement('details');d.className='card settings-menu-v26';d.innerHTML=`<summary><strong>${g.title}</strong></summary><div class="settings-body-v26"></div>`;const body=d.lastElementChild;g.els.forEach(e=>body.appendChild(e));s.appendChild(d)}if(leftovers.length){const d=document.createElement('details');d.className='card settings-menu-v26';d.innerHTML='<summary><strong>Autres paramètres</strong></summary><div class="settings-body-v26"></div>';leftovers.forEach(e=>d.lastElementChild.appendChild(e));s.appendChild(d)}const help=document.createElement('button');help.className='card settings-link-v26';help.innerHTML='<strong>❓ Aide et mode d’emploi</strong>';help.onclick=()=>openHelpV21();s.appendChild(help);linkDates('#v25ps','#v25pe')}
const legacySettings=renderSettings;renderSettings=function(){legacySettings();settingsMenu()};
function style(){if(document.querySelector('#v26style'))return;document.head.insertAdjacentHTML('beforeend',`<style id="v26style">.bottomnav{grid-template-columns:repeat(4,1fr)!important}.bottomnav .navbtn{font-size:12px;padding-left:4px;padding-right:4px}.week-dialog-v26{width:min(92vw,520px);border:0;border-radius:20px;padding:18px}.week-dialog-v26::backdrop{background:rgba(15,23,42,.42)}.v26-week-actions{display:grid;gap:8px;margin-top:14px}.settings-menu-v26>summary{cursor:pointer;list-style:none}.settings-body-v26>.card,.settings-body-v26>details{box-shadow:none;margin:10px 0;padding:10px;border:1px solid rgba(128,128,128,.18)}.settings-link-v26{width:100%;text-align:left}</style>`)}
ensure();addViews();style();const oldAll=renderAll;renderAll=function(){oldAll();trimToday();addViews();if(!document.querySelector('#forecastView').classList.contains('hidden'))renderForecastV26();if(!document.querySelector('#docsView').classList.contains('hidden'))renderDocsV26()};renderAll();
})();