/* Mes heures v28: fonctionnalites completes previsions/plannings/historique */
(function(){
const DAY=86400000, cp=o=>JSON.parse(JSON.stringify(o)), uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const WD=[['1','Lundi'],['2','Mardi'],['3','Mercredi'],['4','Jeudi'],['5','Vendredi'],['6','Samedi'],['0','Dimanche']];
function ensure(){const c=state.config;c.planningProfiles=Array.isArray(c.planningProfiles)?c.planningProfiles:[];if(!c.planningProfiles.length)c.planningProfiles=[{id:'normal',code:'HAB',name:'Planning habituel',days:cp(c.weekPlan||{}),versions:[],archived:false}];for(const p of c.planningProfiles){p.versions=Array.isArray(p.versions)?p.versions:[];p.days=p.days||cp(c.weekPlan||{});p.code=p.code||'PLAN';p.name=p.name||'Planning'}c.planningPeriods=Array.isArray(c.planningPeriods)?c.planningPeriods:[];c.futureEvents=Array.isArray(c.futureEvents)?c.futureEvents:[];c.recurringEvents=Array.isArray(c.recurringEvents)?c.recurringEvents:[];c.annualViewYear=Number(c.annualViewYear)||new Date().getFullYear();applyCurrentNormal()}
const plans=()=>state.config.planningProfiles.filter(p=>!p.archived), planBy=id=>state.config.planningProfiles.find(p=>p.id===id), typeBy=id=>(state.config.dayTypes||[]).find(t=>t.id===id);
function daysForPlan(p,k,pending=false){if(!p)return{};const vs=(p.versions||[]).filter(v=>v.effectiveFrom<=k&&(v.status==='validated'||pending&&v.status==='pending')).sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom));return cp(vs.length?vs.at(-1).days:p.days||{})}
function applyCurrentNormal(){const p=planBy('normal')||plans()[0];if(!p)return;const d=daysForPlan(p,dateKey());if(p.id==='normal'&&Object.keys(d).length)state.config.weekPlan=cp(d)}
function activePeriod(k,pending=false){return state.config.planningPeriods.filter(x=>x.start<=k&&x.end>=k&&(x.status==='validated'||pending&&x.status==='pending')).sort((a,b)=>b.start.localeCompare(a.start))[0]||null}
function activePlan(k,pending=false){return planBy(activePeriod(k,pending)?.profileId)||planBy('normal')||plans()[0]}
function plannedMinutes(k,pending=false){const p=activePlan(k,pending),d=daysForPlan(p,k,pending),dow=String(new Date(k+'T12:00:00').getDay());return Number(typeBy(d[dow])?.minutes||0)}
function mondayList(y){const d=new Date(y,0,1,12);while(d.getDay()!==1)d.setDate(d.getDate()+1);const a=[];while(d.getFullYear()===y){a.push(localKey(d));d.setDate(d.getDate()+7)}return a}
function weekNo(k){const d=new Date(k+'T12:00:00'),first=new Date(d.getFullYear(),0,1,12);while(first.getDay()!==1)first.setDate(first.getDate()+1);return 1+Math.floor((Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-Date.UTC(first.getFullYear(),first.getMonth(),first.getDate()))/(7*DAY))}
function easter(y){const a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),da=((h+l-7*m+114)%31)+1;return new Date(y,mo-1,da,12)}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function holidays(y){const fixed=[[1,1,'Jour de l’an'],[5,1,'Fête du Travail'],[5,8,'Victoire 1945'],[7,14,'Fête nationale'],[8,15,'Assomption'],[11,1,'Toussaint'],[11,11,'Armistice'],[12,25,'Noël']],m=new Map();for(const [mo,d,n] of fixed)m.set(localKey(new Date(y,mo-1,d,12)),n);const e=easter(y);m.set(localKey(addDays(e,1)),'Lundi de Pâques');m.set(localKey(addDays(e,39)),'Ascension');m.set(localKey(addDays(e,50)),'Lundi de Pentecôte');return m}
function recurringOccurrence(r,y){const month=Number(r.month||1)-1;let d;if(r.ordinal==='last'){d=new Date(y,month+1,0,12);while(d.getDay()!==1)d.setDate(d.getDate()-1)}else{d=new Date(y,month,1,12);while(d.getDay()!==1)d.setDate(d.getDate()+1)}const start=localKey(d),end=localKey(addDays(d,Math.max(1,Number(r.weeks||1))*7-1));return{...r,start,end,status:r.status||'planned',recurring:true}}
function eventsFor(k,pending=false){const y=Number(k.slice(0,4)),all=[...state.config.futureEvents,...state.config.recurringEvents.map(r=>recurringOccurrence(r,y))];return all.filter(e=>e.start<=k&&e.end>=k&&(e.status==='validated'||e.status==='planned'||pending&&e.status==='pending'))}
function holidayFor(k){return holidays(Number(k.slice(0,4))).get(k)||''}
function forecastMinutes(k,pending=false){return eventsFor(k,pending).some(e=>e.type==='Récup')?0:plannedMinutes(k,pending)}
function openingAtYear(y){const first=mondayList(y)[0];let b=Number(state.initialBalanceMinutes||0);const paid=s=>(state.balanceAdjustments||[]).filter(x=>x.weekStart===s).reduce((n,x)=>n+Number(x.minutes||0),0);for(const w of(state.historicalWeeks||[]).slice().sort((a,z)=>a.weekStart.localeCompare(z.weekStart)))if(w.weekStart<first)b+=Number(w.deltaMinutes||0)-paid(w.weekStart);return b}
function objective(y){let n=0;for(const ws of mondayList(y))n+=Math.round(Number(scheduleFor(ws)?.weeklyTarget??state.config.weeklyTarget??35)*60);return n}
function projection(y,pending=false){const today=dateKey(),hist=new Map((state.historicalWeeks||[]).map(w=>[w.weekStart,w]));let n=0;for(const ws of mondayList(y)){const h=hist.get(ws);if(h){n+=Number(h.workedMinutes||0);continue}for(const k of weekDays(ws)){if(k<today){const d=state.days[k],w=d?worked(d):null;n+=w!=null?w:forecastMinutes(k,pending)}else n+=forecastMinutes(k,pending)}}return Math.round(n)}
function realized(y){const today=dateKey(),hist=new Map((state.historicalWeeks||[]).map(w=>[w.weekStart,w]));let n=0;for(const ws of mondayList(y)){if(ws>today)continue;const h=hist.get(ws);if(h){n+=Number(h.workedMinutes||0);continue}for(const k of weekDays(ws))if(k<=today){const d=state.days[k],w=d?worked(d):null;if(w!=null)n+=w}}return Math.round(n)}
function weekInfo(ws){const codes=new Set(),evs=[],hs=[];let m=0,pending=false;for(const k of weekDays(ws)){const p=activePlan(k);if(p)codes.add(p.code||p.name);for(const e of eventsFor(k,true)){if(!evs.includes(e.type))evs.push(e.type);if(e.status==='pending')pending=true}const h=holidayFor(k);if(h&&!hs.includes(h))hs.push(h);m+=forecastMinutes(k)}const normalCode=planBy('normal')?.code||'';return{code:codes.size>1?'MIXTE':([...codes][0]||'—'),minutes:m,events:evs,holidays:hs,pending,special:codes.size>1||evs.length||hs.length||[...codes].some(c=>c!==normalCode)}}
function summaryHtml(y){const o=objective(y),r=realized(y),p=projection(y),opening=openingAtYear(y),result=p-o,final=opening+result,remain=Math.max(0,p-r);return `<div class="annual-summary-v28"><div class="row"><span>Objectif annuel</span><strong>${fmtPlainMinutes(o)}</strong></div><div class="row"><span>Réalisé à ce jour</span><strong>${fmtPlainMinutes(r)}</strong></div><div class="row"><span>Prévu restant</span><strong>${fmtPlainMinutes(remain)}</strong></div><div class="row"><span>Projection au 31/12</span><strong>${fmtPlainMinutes(p)}</strong></div><div class="row"><span>Résultat prévu de l’année N</span><strong class="${result>=0?'positive':'negative'}">${fmtMinutes(result)}</strong></div><div class="row"><span>Report N-1</span><strong>${fmtMinutes(opening)}</strong></div><div class="row"><span>Report N+1 projeté</span><strong class="${final>=0?'positive':'negative'}">${fmtMinutes(final)}</strong></div></div>`}
function calendarHtml(y){const months=Array.from({length:12},()=>[]);for(const ws of mondayList(y))months[new Date(ws+'T12:00:00').getMonth()].push({ws,...weekInfo(ws)});return months.map((weeks,i)=>`<div class="annual-month-v28"><strong>${new Intl.DateTimeFormat('fr-FR',{month:'long'}).format(new Date(y,i,1))}</strong><div class="annual-weeks-v28">${weeks.map(w=>`<button class="annual-week-v28 ${w.special?'special':''} ${w.pending?'pending':''}" onclick="openWeekV28('${w.ws}')"><b>S${String(weekNo(w.ws)).padStart(2,'0')}</b><span>${escapeHtml(w.code)}</span><strong>${fmtPlainMinutes(w.minutes)}</strong>${w.events.length||w.holidays.length?'<small>•</small>':''}</button>`).join('')}</div></div>`).join('')}
function renderForecast(){ensure();const v=document.querySelector('#forecastView');if(!v)return;const y=state.config.annualViewYear;v.innerHTML=`<div class="card"><div class="row"><div><h2>Prévisions</h2><p class="muted compact">Ton année prévue, puis le réel qui prend progressivement sa place.</p></div><input style="width:88px" type="number" value="${y}" onchange="changeForecastYearV28(this.value)"></div>${summaryHtml(y)}${calendarHtml(y)}<p class="muted compact">Une semaine mise en évidence contient un planning particulier, un événement, un férié ou quelque chose à vérifier.</p></div><div class="card"><h2>Événements à venir</h2><p class="muted compact">Congés, récup et autres événements qui modifient ou expliquent la prévision.</p>${eventListHtml(y)}<button onclick="openEventEditorV28()">+ Ajouter un événement</button></div>`}
window.changeForecastYearV28=v=>{state.config.annualViewYear=Number(v)||new Date().getFullYear();save();renderForecast()};
function eventListHtml(y){const occ=[...state.config.futureEvents.filter(e=>e.start.startsWith(String(y))||e.end.startsWith(String(y))),...state.config.recurringEvents.map(r=>recurringOccurrence(r,y))].sort((a,b)=>a.start.localeCompare(b.start));if(!occ.length)return'<p class="muted">Aucun événement prévu pour cette année.</p>';return occ.map(e=>`<div class="history-item"><div class="row"><strong>${escapeHtml(e.type)}</strong><span>${escapeHtml(e.start)} → ${escapeHtml(e.end)}</span></div>${e.comment?`<div>${escapeHtml(e.comment)}</div>`:''}<div class="muted">${e.recurring?'Récurrent · ':''}${e.status==='pending'?'En attente de validation':e.status==='validated'?'Validé':'Prévu récurrent'}</div>${e.recurring?`<button class="ghost" onclick="removeRecurringV28('${e.id}')">Supprimer la récurrence</button>`:`${e.status==='pending'?`<button class="ghost" onclick="validateEventV28('${e.id}')">Marquer validé</button>`:''}<button class="ghost" onclick="removeEventV28('${e.id}')">Retirer</button>`}</div>`).join('')}
function weekDialogHtml(ws){const rows=weekDays(ws).map(k=>{const p=activePlan(k),es=eventsFor(k,true),h=holidayFor(k);return `<div class="history-item"><div class="row"><strong>${new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(k+'T12:00:00'))}</strong><span>${escapeHtml(p?.code||'—')} · ${fmtPlainMinutes(forecastMinutes(k))}</span></div>${h?`<div class="muted">Férié · ${escapeHtml(h)}</div>`:''}${es.map(e=>`<div class="muted">${escapeHtml(e.type)}${e.comment?' · '+escapeHtml(e.comment):''}${e.status==='pending'?' · en attente':''}</div>`).join('')}</div>`}).join('');return `<dialog id="weekDialogV28" class="modal-v28"><div class="row"><div><h2>S${String(weekNo(ws)).padStart(2,'0')}</h2><div class="muted">${ws} → ${weekDays(ws)[6]}</div></div><button class="ghost" onclick="closeModalV28('weekDialogV28')">Fermer</button></div>${rows}<div class="actions action-stack-v28"><button onclick="openWeekPlanChangeV28('${ws}')">Changer de planning</button><button class="secondary" onclick="openEventEditorV28('${ws}','${weekDays(ws)[6]}')">Ajouter un événement</button><button class="secondary" onclick="chooseDayToEditV28('${ws}')">Modifier une journée</button></div></dialog>`}
window.openWeekV28=ws=>{document.querySelector('#weekDialogV28')?.remove();document.body.insertAdjacentHTML('beforeend',weekDialogHtml(ws));document.querySelector('#weekDialogV28').showModal()};window.annualWeekV24=window.openWeekV28;
window.closeModalV28=id=>document.querySelector('#'+id)?.close();
window.openWeekPlanChangeV28=ws=>{document.querySelector('#weekPlanDialogV28')?.remove();document.body.insertAdjacentHTML('beforeend',`<dialog id="weekPlanDialogV28" class="modal-v28"><h2>Changer le planning · S${weekNo(ws)}</h2><div class="field"><label>Planning</label><select id="weekPlanSelectV28">${plans().map(p=>`<option value="${p.id}">${escapeHtml(p.code)} · ${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="field"><label>Statut</label><select id="weekPlanStatusV28"><option value="validated">Déjà validé</option><option value="pending">En attente de validation</option></select></div><div class="actions"><button onclick="saveWeekPlanChangeV28('${ws}')">Enregistrer</button><button class="secondary" onclick="closeModalV28('weekPlanDialogV28')">Annuler</button></div></dialog>`);document.querySelector('#weekPlanDialogV28').showModal()};
window.saveWeekPlanChangeV28=ws=>{state.config.planningPeriods.push({id:uid('per'),profileId:document.querySelector('#weekPlanSelectV28').value,start:ws,end:weekDays(ws)[6],status:document.querySelector('#weekPlanStatusV28').value,createdAt:dateKey()});save();document.querySelector('#weekPlanDialogV28')?.close();document.querySelector('#weekDialogV28')?.close();renderForecast();toast('✓ Planning de la semaine enregistré.')};
window.chooseDayToEditV28=ws=>{document.querySelector('#dayChoiceV28')?.remove();document.body.insertAdjacentHTML('beforeend',`<dialog id="dayChoiceV28" class="modal-v28"><h2>Modifier une journée</h2>${weekDays(ws).map(k=>`<button class="secondary full-v28" onclick="editChosenDayV28('${k}')">${escapeHtml(frenchDate(k))}</button>`).join('')}<button class="ghost full-v28" onclick="closeModalV28('dayChoiceV28')">Annuler</button></dialog>`);document.querySelector('#dayChoiceV28').showModal()};
window.editChosenDayV28=k=>{document.querySelectorAll('#weekDialogV28,#dayChoiceV28').forEach(x=>x.close());showView('historyView');setTimeout(()=>{openHistoryEditor();const i=document.querySelector('#histDate');if(i){i.value=k;loadPastDay();i.scrollIntoView({block:'start'})}},60)};
let rangeCtx=null;
function monthLabel(d){return new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(d)}
function rangeCalendar(){if(!rangeCtx)return;const box=document.querySelector('#rangeCalendarBodyV28'),d=rangeCtx.month,first=new Date(d.getFullYear(),d.getMonth(),1,12),startDow=(first.getDay()+6)%7,last=new Date(d.getFullYear(),d.getMonth()+1,0,12).getDate();let h='<div class="cal-head-v28"><button class="ghost" onclick="moveRangeMonthV28(-1)">‹</button><strong>'+escapeHtml(monthLabel(d))+'</strong><button class="ghost" onclick="moveRangeMonthV28(1)">›</button></div><div class="cal-grid-v28">'+['L','M','M','J','V','S','D'].map(x=>'<b>'+x+'</b>').join('');for(let i=0;i<startDow;i++)h+='<span></span>';for(let n=1;n<=last;n++){const k=localKey(new Date(d.getFullYear(),d.getMonth(),n,12)),sel=(rangeCtx.start&&k===rangeCtx.start)||(rangeCtx.end&&k===rangeCtx.end),between=rangeCtx.start&&rangeCtx.end&&k>=rangeCtx.start&&k<=rangeCtx.end;h+=`<button class="cal-day-v28 ${sel?'edge':''} ${between?'between':''}" onclick="pickRangeDateV28('${k}')">${n}</button>`}h+='</div><div class="muted compact">'+(rangeCtx.start?`Début : ${rangeCtx.start}`:'Choisis le premier jour')+(rangeCtx.end?` · Fin : ${rangeCtx.end}`:' · puis le dernier jour')+'</div>';box.innerHTML=h;document.querySelector('#rangeValidateV28').disabled=!(rangeCtx.start&&rangeCtx.end)}
window.openRangePickerV28=(startId,endId)=>{const a=document.querySelector('#'+startId)?.value||'',b=document.querySelector('#'+endId)?.value||'',base=a?new Date(a+'T12:00:00'):new Date();rangeCtx={startId,endId,start:a||'',end:b||'',month:new Date(base.getFullYear(),base.getMonth(),1,12)};document.querySelector('#rangeDialogV28')?.remove();document.body.insertAdjacentHTML('beforeend','<dialog id="rangeDialogV28" class="modal-v28"><div id="rangeCalendarBodyV28"></div><div class="actions"><button id="rangeValidateV28" onclick="validateRangeV28()">Valider la période</button><button class="secondary" onclick="closeModalV28(\'rangeDialogV28\')">Annuler</button></div></dialog>');rangeCalendar();document.querySelector('#rangeDialogV28').showModal()};
window.moveRangeMonthV28=n=>{rangeCtx.month=new Date(rangeCtx.month.getFullYear(),rangeCtx.month.getMonth()+n,1,12);rangeCalendar()};
window.pickRangeDateV28=k=>{if(!rangeCtx.start||rangeCtx.end){rangeCtx.start=k;rangeCtx.end=''}else if(k<rangeCtx.start){rangeCtx.start=k;rangeCtx.end=''}else rangeCtx.end=k;rangeCalendar()};
window.validateRangeV28=()=>{if(!rangeCtx?.start||!rangeCtx?.end)return;const a=document.querySelector('#'+rangeCtx.startId),b=document.querySelector('#'+rangeCtx.endId);if(a)a.value=rangeCtx.start;if(b)b.value=rangeCtx.end;document.querySelector('#rangeDialogV28')?.close()};
function rangeFields(prefix,start='',end=''){return `<div class="field"><label>Période</label><div class="row"><input id="${prefix}Start" type="date" value="${start}" readonly><span>→</span><input id="${prefix}End" type="date" value="${end}" readonly></div><button class="ghost" onclick="openRangePickerV28('${prefix}Start','${prefix}End')">Choisir la période</button></div>`}
window.openEventEditorV28=(start='',end='')=>{document.querySelector('#eventDialogV28')?.remove();document.body.insertAdjacentHTML('beforeend',`<dialog id="eventDialogV28" class="modal-v28"><div class="row"><h2>Ajouter un événement</h2><button class="ghost" onclick="closeModalV28('eventDialogV28')">Fermer</button></div><div class="field"><label>Type</label><select id="eventTypeV28">${['Congé','Congé exceptionnel','Récup','Arrêt maladie','Autre'].map(x=>`<option>${x}</option>`).join('')}</select></div>${rangeFields('eventV28',start,end)}<div class="field"><label>Commentaire (facultatif)</label><textarea id="eventCommentV28" placeholder="Ex. mariage de ma sœur"></textarea></div><div class="field"><label>Récurrence</label><select id="eventRecV28" onchange="toggleRecV28()"><option value="none">Aucune</option><option value="calendar">Chaque année selon le calendrier</option></select></div><div id="recFieldsV28" class="hidden"><div class="row"><select id="recOrdinalV28"><option value="first">Premier lundi</option><option value="last">Dernier lundi</option></select><select id="recMonthV28">${Array.from({length:12},(_,i)=>`<option value="${i+1}">${new Intl.DateTimeFormat('fr-FR',{month:'long'}).format(new Date(2026,i,1))}</option>`).join('')}</select></div><div class="field"><label>Durée (semaines)</label><input id="recWeeksV28" type="number" min="1" max="8" value="1"></div></div><div class="field"><label>Statut</label><select id="eventStatusV28"><option value="validated">Déjà validé</option><option value="pending">En attente de validation</option></select></div><button onclick="saveEventV28()">Enregistrer l’événement</button></dialog>`);document.querySelector('#eventDialogV28').showModal()};
window.toggleRecV28=()=>document.querySelector('#recFieldsV28')?.classList.toggle('hidden',document.querySelector('#eventRecV28').value!=='calendar');
window.saveEventV28=()=>{const type=document.querySelector('#eventTypeV28').value,comment=document.querySelector('#eventCommentV28').value.trim(),status=document.querySelector('#eventStatusV28').value;if(document.querySelector('#eventRecV28').value==='calendar'){state.config.recurringEvents.push({id:uid('rec'),type,comment,status:status==='validated'?'planned':'pending',ordinal:document.querySelector('#recOrdinalV28').value,month:Number(document.querySelector('#recMonthV28').value),weeks:Number(document.querySelector('#recWeeksV28').value)||1,createdAt:dateKey()})}else{const start=document.querySelector('#eventV28Start').value,end=document.querySelector('#eventV28End').value;if(!start||!end){toast('Choisis la période.','error');return}state.config.futureEvents.push({id:uid('evt'),type,comment,start,end,status,createdAt:dateKey(),validatedAt:status==='validated'?dateKey():''})}save();document.querySelector('#eventDialogV28')?.close();renderForecast();toast('✓ Événement enregistré.')};
window.validateEventV28=id=>{const e=state.config.futureEvents.find(x=>x.id===id);if(e){e.status='validated';e.validatedAt=dateKey();save();renderForecast()}};window.removeEventV28=id=>{state.config.futureEvents=state.config.futureEvents.filter(x=>x.id!==id);save();renderForecast()};window.removeRecurringV28=id=>{state.config.recurringEvents=state.config.recurringEvents.filter(x=>x.id!==id);save();renderForecast()};
function currentDays(p){return daysForPlan(p,dateKey())}
function planEditorHtml(){return `<div id="planningManagerV28"><p class="muted compact">Crée tes plannings ici. Leur nom et leur code sont indépendants des journées types.</p>${plans().map(planCardHtml).join('')}<button class="secondary" onclick="openNewPlanV28()">+ Créer un planning</button></div>`}
function planCardHtml(p){const ds=currentDays(p),total=WD.reduce((n,[d])=>n+Number(typeBy(ds[d])?.minutes||0),0),periods=state.config.planningPeriods.filter(x=>x.profileId===p.id).sort((a,b)=>a.start.localeCompare(b.start));return `<details class="plan-card-v28"><summary><strong>${escapeHtml(p.code)} · ${escapeHtml(p.name)}</strong><span>${fmtPlainMinutes(total)}/sem.</span></summary><div class="field"><label>Nom du planning</label><input id="pn-${p.id}" value="${escapeAttr(p.name)}"></div><div class="field"><label>Code</label><input id="pc-${p.id}" maxlength="6" value="${escapeAttr(p.code)}"></div>${WD.map(([d,n])=>`<div class="row"><span>${n}</span><select data-plan-day="${p.id}" data-dow="${d}">${(state.config.dayTypes||[]).map(t=>`<option value="${t.id}" ${ds[d]===t.id?'selected':''}>${escapeHtml(t.code||'')} · ${escapeHtml(t.name)}</option>`).join('')}</select></div>`).join('')}<div class="muted compact">Durée totale prévue : ${fmtPlainMinutes(total)} · Objectif hebdomadaire : ${fmtPlainMinutes(Math.round(Number(state.config.weeklyTarget||0)*60))}</div><div class="field"><label>Date de prise d’effet</label><input id="pe-${p.id}" type="date" value="${dateKey()}"></div><div class="field"><label>Validation</label><select id="pv-${p.id}"><option value="validated">Déjà validé</option><option value="pending">En attente de validation</option></select></div><button onclick="savePlanV28('${p.id}')">Enregistrer cette nouvelle version</button><h3>Périodes d’application</h3>${periods.length?periods.map(x=>`<div class="history-item"><div class="row"><span>${x.start} → ${x.end}</span><span>${x.status==='pending'?'En attente':'Validé'}</span></div><button class="ghost" onclick="removePlanPeriodV28('${x.id}')">Retirer</button></div>`).join(''):'<p class="muted">Aucune période particulière.</p>'}${rangeFields('pp-'+p.id)}<div class="field"><label>Statut de la période</label><select id="pps-${p.id}"><option value="validated">Déjà validé</option><option value="pending">En attente de validation</option></select></div><button class="secondary" onclick="addPlanPeriodV28('${p.id}')">Ajouter cette période</button>${p.id!=='normal'?`<button class="ghost" onclick="archivePlanV28('${p.id}')">Archiver ce planning</button>`:''}</details>`}
window.savePlanV28=id=>{const p=planBy(id),name=document.querySelector('#pn-'+id).value.trim(),code=document.querySelector('#pc-'+id).value.trim().toUpperCase(),effective=document.querySelector('#pe-'+id).value,status=document.querySelector('#pv-'+id).value;if(!name||!code||!effective){toast('Nom, code et date d’effet sont nécessaires.','error');return}if(plans().some(x=>x.id!==id&&x.code.toUpperCase()===code)){toast('Ce code est déjà utilisé par un autre planning.','error');return}const days={};document.querySelectorAll(`[data-plan-day="${id}"]`).forEach(x=>days[x.dataset.dow]=x.value);p.name=name;p.code=code;p.versions.push({id:uid('ver'),effectiveFrom:effective,status,days,createdAt:dateKey(),validatedAt:status==='validated'?dateKey():''});save();applyCurrentNormal();save();renderSettings();toast(status==='validated'?'✓ Nouvelle version du planning enregistrée.':'✓ Version enregistrée en attente de validation.')};
window.openNewPlanV28=()=>{document.querySelector('#newPlanDialogV28')?.remove();document.body.insertAdjacentHTML('beforeend',`<dialog id="newPlanDialogV28" class="modal-v28"><h2>Créer un planning</h2><div class="field"><label>Nom</label><input id="newPlanNameV28" placeholder="Vacances, direction…"></div><div class="field"><label>Code</label><input id="newPlanCodeV28" maxlength="6" placeholder="VAC"></div><div class="field"><label>Partir de</label><select id="newPlanBaseV28">${plans().map(p=>`<option value="${p.id}">${escapeHtml(p.code)} · ${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="actions"><button onclick="createPlanV28()">Créer</button><button class="secondary" onclick="closeModalV28('newPlanDialogV28')">Annuler</button></div></dialog>`);document.querySelector('#newPlanDialogV28').showModal()};
window.createPlanV28=()=>{const name=document.querySelector('#newPlanNameV28').value.trim(),code=document.querySelector('#newPlanCodeV28').value.trim().toUpperCase(),base=planBy(document.querySelector('#newPlanBaseV28').value);if(!name||!code){toast('Donne un nom et un code.','error');return}if(plans().some(p=>p.code.toUpperCase()===code)){toast('Ce code est déjà utilisé.','error');return}state.config.planningProfiles.push({id:uid('pl'),name,code,days:cp(currentDays(base)),versions:[],archived:false});save();document.querySelector('#newPlanDialogV28')?.close();renderSettings();toast('✓ Planning créé.')};
window.addPlanPeriodV28=id=>{const start=document.querySelector('#pp-'+id+'Start').value,end=document.querySelector('#pp-'+id+'End').value,status=document.querySelector('#pps-'+id).value;if(!start||!end){toast('Choisis la période.','error');return}state.config.planningPeriods.push({id:uid('per'),profileId:id,start,end,status,createdAt:dateKey()});save();renderSettings();toast('✓ Période d’application ajoutée.')};window.removePlanPeriodV28=id=>{state.config.planningPeriods=state.config.planningPeriods.filter(x=>x.id!==id);save();renderSettings()};window.archivePlanV28=id=>{const p=planBy(id);if(p)p.archived=true;save();renderSettings()};
function patchSettings(){const s=document.querySelector('#settingsView');if(!s)return;s.querySelector('#plansV25')?.remove();[...s.querySelectorAll('.card')].forEach(c=>{if(c.querySelector('h2')?.textContent.trim()==='Planning habituel')c.remove()});let host=[...s.querySelectorAll('details.settings-menu-v26')].find(d=>d.querySelector('summary')?.textContent.includes('Mes plannings'));if(!host){host=document.createElement('details');host.className='card settings-menu-v26';host.innerHTML='<summary><strong>Mes plannings</strong></summary><div class="settings-body-v26"></div>';const first=s.querySelector('.settings-menu-v26');first?first.insertAdjacentElement('afterend',host):s.appendChild(host)}host.querySelector('.settings-body-v26').innerHTML=planEditorHtml();const imp=[...s.querySelectorAll('details.settings-menu-v26')].find(d=>d.querySelector('summary')?.textContent.includes('Importer'));if(imp&&!imp.querySelector('.import-note-v28'))imp.querySelector('.settings-body-v26')?.insertAdjacentHTML('afterbegin','<p class="muted compact import-note-v28">Ici on reprend un historique, un solde de départ ou une ancienne période. La restauration complète reste une sauvegarde, pas un import.</p>')}
const baseSettings=renderSettings;renderSettings=function(){baseSettings();patchSettings()};
function patchHistory(){const v=document.querySelector('#historyView');if(!v||v.querySelector('#historyTabsV28'))return;v.querySelector('#exportV11')?.remove();const quick=v.querySelector('#historyQuickActionsV17');if(quick)[...quick.querySelectorAll('details')].forEach(d=>{if(d.querySelector('summary')?.textContent==='Exports')d.remove()});const recent=[...v.querySelectorAll('.card')].find(c=>c.querySelector('h2')?.textContent==='Historique récent'),weeks=[...v.querySelectorAll('.card')].find(c=>c.querySelector('h2')?.textContent==='Semaines importées'),adjust=v.querySelector('#adjustmentsV12')||[...v.querySelectorAll('details')].find(d=>/régularisations/i.test(d.textContent||''));const tabs=document.createElement('div');tabs.id='historyTabsV28';tabs.className='card';tabs.innerHTML='<div class="segmented-v28"><button class="active" onclick="historyTabV28(\'recent\')">Semaines récentes</button><button onclick="historyTabV28(\'annual\')">Historique annuel</button><button onclick="historyTabV28(\'adjust\')">Régularisations</button></div><div id="histRecentV28"></div><div id="histAnnualV28" class="hidden"></div><div id="histAdjustV28" class="hidden"></div>';v.insertAdjacentElement('afterbegin',tabs);const r=tabs.querySelector('#histRecentV28'),a=tabs.querySelector('#histAnnualV28'),g=tabs.querySelector('#histAdjustV28');const tools=v.querySelector('.history-tools');if(tools)r.appendChild(tools);if(recent)r.appendChild(recent);if(weeks)a.appendChild(weeks);if(adjust)g.appendChild(adjust);const years=[...new Set([...(state.historicalWeeks||[]).map(w=>w.weekStart?.slice(0,4)),...Object.keys(state.days).map(k=>k.slice(0,4))].filter(Boolean))].sort().reverse();a.insertAdjacentHTML('afterbegin',`<div class="field"><label>Année</label><select id="historyYearV28" onchange="filterHistoryYearV28()">${years.map(y=>`<option>${y}</option>`).join('')}</select></div>`)}
window.historyTabV28=id=>{['Recent','Annual','Adjust'].forEach(x=>document.querySelector('#hist'+x+'V28')?.classList.toggle('hidden',x.toLowerCase()!==id));document.querySelectorAll('#historyTabsV28 .segmented-v28 button').forEach((b,i)=>b.classList.toggle('active',['recent','annual','adjust'][i]===id));window.scrollTo({top:0,behavior:'smooth'})};
window.filterHistoryYearV28=()=>{const y=document.querySelector('#historyYearV28')?.value;if(!y)return;document.querySelectorAll('#histAnnualV28 .history-item').forEach(x=>{x.style.display=(x.textContent||'').includes(y)?'':'none'})};
const baseHistory=renderHistory;renderHistory=function(){baseHistory();patchHistory()};
function monthBounds(ym){const [y,m]=ym.split('-').map(Number);return[localKey(new Date(y,m-1,1,12)),localKey(new Date(y,m,0,12))]}
function renderDocs(){const v=document.querySelector('#docsView');if(!v)return;const n=new Date(),ym=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}`;v.innerHTML=`<div class="card"><h2>Relevés PDF</h2><p class="muted compact">Le relevé mensuel couvre le mois civil. Les semaines, elles, restent rattachées au mois de leur lundi.</p><div class="field"><label>Mois</label><input id="pdfMonthV28" type="month" value="${ym}"></div><button onclick="pdfMonthV28()">PDF mensuel</button><div class="field"><label>Année</label><input id="pdfYearV28" type="number" value="${n.getFullYear()}"></div><button class="secondary" onclick="pdfAnnualV28()">PDF annuel</button></div><div class="card"><h2>Extraire des données</h2><p class="muted compact">Choisis librement la période à exporter en CSV.</p>${rangeFields('exportV28',localKey(new Date(n.getFullYear(),n.getMonth(),1,12)),localKey(new Date(n.getFullYear(),n.getMonth()+1,0,12)))}<input id="exportStart" type="hidden"><input id="exportEnd" type="hidden"><button onclick="csvRangeV28()">Télécharger le CSV</button></div><div class="card"><h2>Documents administratifs</h2><p class="muted compact">Les demandes de congé, récup ou changement de planning viendront ici lorsqu’elles produiront réellement un document.</p></div>`}
window.pdfMonthV28=()=>{const [a,b]=monthBounds(document.querySelector('#pdfMonthV28').value);document.querySelector('#exportStart').value=a;document.querySelector('#exportEnd').value=b;runExportV11('pdf')};window.pdfAnnualV28=()=>{const y=Number(document.querySelector('#pdfYearV28').value)||new Date().getFullYear();document.querySelector('#exportStart').value=`${y}-01-01`;document.querySelector('#exportEnd').value=`${y}-12-31`;runExportV11('annual')};window.csvRangeV28=()=>{document.querySelector('#exportStart').value=document.querySelector('#exportV28Start').value;document.querySelector('#exportEnd').value=document.querySelector('#exportV28End').value;runExportV11('csv')};
const baseShow=showView;showView=function(id){baseShow(id);if(id==='forecastView')renderForecast();if(id==='docsView')renderDocs();if(id==='historyView'){renderHistory();setTimeout(()=>window.scrollTo({top:0,behavior:'auto'}),0)}if(id==='settingsView')setTimeout(patchSettings,0)};
const baseAll=renderAll;renderAll=function(){baseAll();ensure();if(!document.querySelector('#forecastView')?.classList.contains('hidden'))renderForecast();if(!document.querySelector('#docsView')?.classList.contains('hidden'))renderDocs()};
function styles(){if(document.querySelector('#v28style'))return;document.head.insertAdjacentHTML('beforeend',`<style id="v28style">.annual-month-v28{padding:10px 0;border-top:1px solid rgba(128,128,128,.2)}.annual-month-v28>strong{display:block;margin-bottom:6px;text-transform:capitalize}.annual-weeks-v28{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:5px}.annual-week-v28{min-width:0;padding:7px 2px;border-radius:9px;display:flex;flex-direction:column;align-items:center;gap:2px;font-size:11px}.annual-week-v28.special{outline:2px solid rgba(59,130,246,.35)}.annual-week-v28.pending{outline-style:dashed}.annual-week-v28 b,.annual-week-v28 strong{font-size:12px}.modal-v28{width:min(92vw,540px);max-height:86vh;overflow:auto;border:0;border-radius:18px;padding:18px}.modal-v28::backdrop{background:rgba(15,23,42,.45)}.action-stack-v28{display:grid;gap:8px;margin-top:14px}.full-v28{width:100%;margin:4px 0}.plan-card-v28{border:1px solid rgba(128,128,128,.2);border-radius:12px;padding:10px;margin:10px 0}.plan-card-v28 summary{display:flex;justify-content:space-between;cursor:pointer}.cal-head-v28{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.cal-grid-v28{display:grid;grid-template-columns:repeat(7,1fr);gap:4px}.cal-grid-v28>b{text-align:center;font-size:12px}.cal-day-v28{padding:9px 2px;border-radius:8px}.cal-day-v28.between{background:rgba(59,130,246,.12)}.cal-day-v28.edge{outline:2px solid currentColor}.segmented-v28{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.segmented-v28 button{font-size:12px;padding:8px 4px}.segmented-v28 button.active{font-weight:700;outline:2px solid rgba(59,130,246,.35)}</style>`)}
ensure();styles();renderAll();
})();