/* Mes heures v30: historique annuel et reports PDF */
(function(){
function yearsV30(){return [...new Set([...(state.historicalWeeks||[]).map(w=>w.weekStart?.slice(0,4)),...Object.keys(state.days||{}).map(k=>k.slice(0,4))].filter(Boolean))].sort().reverse()}
function annualHistoryHtmlV30(y){const weeks=(state.historicalWeeks||[]).filter(w=>w.weekStart?.startsWith(y)).slice().sort((a,b)=>a.weekStart.localeCompare(b.weekStart));const days=Object.keys(state.days||{}).filter(k=>k.startsWith(y)).sort().reverse();let h='';if(weeks.length){h+='<h3>Semaines consolidées</h3>'+weeks.map(w=>`<div class="history-item"><div class="row"><strong>S${escapeHtml(String(w.week||''))} · ${escapeHtml(w.weekStart)}</strong><span>${fmtPlainMinutes(w.workedMinutes)}</span></div><div class="muted">Objectif ${fmtPlainMinutes(w.targetMinutes)} · écart ${fmtMinutes(w.deltaMinutes)}</div>${w.eventType?`<div>${escapeHtml(w.eventType)}</div>`:''}${w.note?`<div>${escapeHtml(w.note)}</div>`:''}</div>`).join('')}if(days.length){h+='<h3>Journées détaillées</h3>'+days.map(k=>{const d=state.days[k],w=worked(d);return `<div class="history-item"><div class="row"><strong>${escapeHtml(frenchDate(k))}</strong><span>${w==null?'À compléter':fmtPlainMinutes(w)}</span></div>${d.note?`<div>${escapeHtml(d.note)}</div>`:''}<button class="ghost" onclick="editPastDay('${k}')">Modifier</button></div>`}).join('')}return h||'<p class="muted">Aucune donnée pour cette année.</p>'}
function patchAnnualHistoryV30(){const box=document.querySelector('#histAnnualV28');if(!box)return;const ys=yearsV30(),current=document.querySelector('#historyYearV30')?.value||ys[0]||String(new Date().getFullYear());box.innerHTML=`<div class="field"><label>Année</label><select id="historyYearV30" onchange="renderAnnualHistoryV30()">${ys.map(y=>`<option ${y===current?'selected':''}>${y}</option>`).join('')}</select></div><div id="historyAnnualContentV30">${annualHistoryHtmlV30(current)}</div>`}
window.renderAnnualHistoryV30=()=>{const y=document.querySelector('#historyYearV30')?.value,box=document.querySelector('#historyAnnualContentV30');if(y&&box)box.innerHTML=annualHistoryHtmlV30(y)};
const oldHistoryTab=window.historyTabV28;window.historyTabV28=id=>{oldHistoryTab(id);if(id==='annual')patchAnnualHistoryV30()};
function firstMonday(y){const d=new Date(y,0,1,12);while(d.getDay()!==1)d.setDate(d.getDate()+1);return localKey(d)}
function paidV30(s){return(state.balanceAdjustments||[]).filter(x=>x.weekStart===s).reduce((n,x)=>n+Number(x.minutes||0),0)}
function openingV30(y){const first=firstMonday(y);let b=Number(state.initialBalanceMinutes||0);for(const w of(state.historicalWeeks||[]).slice().sort((a,z)=>a.weekStart.localeCompare(z.weekStart)))if(w.weekStart<first)b+=Number(w.deltaMinutes||0)-paidV30(w.weekStart);return b}
function yearResultV30(y){const first=firstMonday(y),today=dateKey(),hist=new Map((state.historicalWeeks||[]).map(w=>[w.weekStart,w]));let result=0;for(let d=new Date(first+'T12:00:00');d.getFullYear()===y;d.setDate(d.getDate()+7)){const s=localKey(d),h=hist.get(s);if(h){result+=Number(h.deltaMinutes||0)-paidV30(s);continue}if(s===weekStart(today))result+=weekWorked(s)-weekTarget(s)-paidV30(s)}return Math.round(result)}
const oldExportV30=window.runExportV11;window.runExportV11=kind=>{if(kind!=='annual')return oldExportV30(kind);const a=document.querySelector('#exportStart')?.value||dateKey(),y=new Date(a+'T12:00:00').getFullYear(),op=openingV30(y),res=yearResultV30(y),next=op+res,nativeOpen=window.open,originalWrite=Document.prototype.write;Document.prototype.write=function(html){if(typeof html==='string'&&html.includes('Relevé annuel')){const block=`<div style="width:86%;margin:0 auto 4px;display:grid;grid-template-columns:repeat(3,1fr);gap:4px;font-size:7px"><div style="border:1px solid #bbb;padding:2px 4px"><b>Report N-1</b><br>${fmtMinutes(op)}</div><div style="border:1px solid #bbb;padding:2px 4px"><b>Résultat année N</b><br>${fmtMinutes(res)}</div><div style="border:1px solid #bbb;padding:2px 4px"><b>Report N+1</b><br>${fmtMinutes(next)}</div></div>`;html=html.replace('<table>',block+'<table>')}return originalWrite.call(this,html)};try{return oldExportV30(kind)}finally{Document.prototype.write=originalWrite;window.open=nativeOpen}};
})();