/* v31 events: demi-journees sans recurrence */
(function(){
const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const planBy=id=>(state.config.planningProfiles||[]).find(p=>p.id===id),typeBy=id=>(state.config.dayTypes||[]).find(t=>t.id===id);
function daysFor(p,k){if(!p)return{};const vs=(p.versions||[]).filter(v=>v.effectiveFrom<=k&&v.status==='validated').sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom));return vs.length?vs.at(-1).days:(p.days||{})}
function activePlan(k){const per=(state.config.planningPeriods||[]).filter(x=>x.start<=k&&x.end>=k&&x.status==='validated').sort((a,b)=>b.start.localeCompare(a.start))[0];return planBy(per?.profileId)||planBy('normal')||(state.config.planningProfiles||[]).find(p=>!p.archived)}
function planned(k){const p=activePlan(k),d=daysFor(p,k),dow=String(new Date(k+'T12:00:00').getDay());return Number(typeBy(d[dow])?.minutes||0)}
function plannedType(k){const p=activePlan(k),d=daysFor(p,k),dow=String(new Date(k+'T12:00:00').getDay());return typeBy(d[dow])||null}
function partMinutes(k,part,split){const t=plannedType(k),total=planned(k);if(!t?.start||!t?.end)return Math.round(total/2);const a=mins(t.start),b=mins(t.end),s=mins(split);if(a==null||b==null||s==null)return Math.round(total/2);return part==='morning'?Math.max(0,Math.min(b,s)-a):Math.max(0,b-Math.max(a,s))}
window.forecastMinutesV31=k=>{let m=planned(k);for(const e of(state.config.futureEvents||[]).filter(e=>e.start<=k&&e.end>=k&&e.status==='validated')){if(e.type!=='Récup')continue;const part=e.part||'full';if(part==='full')return 0;m=Math.max(0,m-partMinutes(k,part,e.splitTime||(part==='morning'?'13:30':'12:00')))}return m};
window.openEventEditorV31=(start='',end='')=>{document.querySelector('#eventDialogV31')?.remove();document.body.insertAdjacentHTML('beforeend',`<dialog id="eventDialogV31" class="modal-v28"><div class="row"><h2>Ajouter un événement</h2><button class="ghost" onclick="document.querySelector('#eventDialogV31').close()">Fermer</button></div><div class="field"><label>Type</label><select id="eventTypeV31">${['Congé','Congé exceptionnel','Récup','Arrêt maladie','Autre'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Période</label><div class="row"><input id="eventV31Start" type="date" value="${escapeAttr(start)}" readonly><span>→</span><input id="eventV31End" type="date" value="${escapeAttr(end)}" readonly></div><button class="ghost" onclick="openRangePickerV28('eventV31Start','eventV31End')">Choisir la période</button></div><div class="field"><label>Partie de journée</label><select id="eventPartV31" onchange="eventPartChangeV31()"><option value="full">Journée entière</option><option value="morning">Matin</option><option value="afternoon">Après-midi</option></select></div><div id="eventSplitWrapV31" class="field hidden"><label id="eventSplitLabelV31">Heure prévue</label><input id="eventSplitV31" type="time"></div><div class="field"><label>Commentaire (facultatif)</label><textarea id="eventCommentV31"></textarea></div><div class="field"><label>Statut</label><select id="eventStatusV31"><option value="validated">Déjà validé</option><option value="pending">En attente de validation</option></select></div><button onclick="saveEventV31()">Enregistrer l’événement</button></dialog>`);document.querySelector('#eventDialogV31').showModal()};
window.eventPartChangeV31=()=>{const part=document.querySelector('#eventPartV31')?.value,wrap=document.querySelector('#eventSplitWrapV31'),i=document.querySelector('#eventSplitV31'),l=document.querySelector('#eventSplitLabelV31');wrap?.classList.toggle('hidden',part==='full');if(part==='morning'){l.textContent='Reprise du travail prévue';if(!i.value)i.value='13:30'}if(part==='afternoon'){l.textContent='Fin du travail prévue';if(!i.value)i.value='12:00'}if(part==='full'&&i)i.value=''};
window.saveEventV31=()=>{const start=document.querySelector('#eventV31Start').value,end=document.querySelector('#eventV31End').value,part=document.querySelector('#eventPartV31').value,split=part==='full'?'':document.querySelector('#eventSplitV31').value;if(!start||!end||end<start){toast('Choisis une période valide.','error');return}if(part!=='full'&&!split){toast('Renseigne l’heure de découpage.','error');return}const status=document.querySelector('#eventStatusV31').value;state.config.futureEvents.push({id:uid('evt'),type:document.querySelector('#eventTypeV31').value,comment:document.querySelector('#eventCommentV31').value.trim(),start,end,part,splitTime:split,status,createdAt:dateKey(),validatedAt:status==='validated'?dateKey():''});save();document.querySelector('#eventDialogV31')?.close();renderAll();toast('✓ Événement enregistré.')};
window.openEventEditorV28=window.openEventEditorV31;window.saveEventV28=window.saveEventV31;
})();