/* v31 UI: historique, docs admin, roles de planning et notice */
(function(){
let histOrder='desc',histTab='recent',histYear='';
const plans=()=>Array.isArray(state.config.planningProfiles)?state.config.planningProfiles.filter(p=>!p.archived):[],planBy=id=>(state.config.planningProfiles||[]).find(p=>p.id===id);
function ensureRoles(){const ps=plans();if(!ps.length)return;const principal=planBy('normal')||ps[0];principal.role='principal';const rest=ps.filter(p=>p.id!==principal.id);if(rest[0]&&!rest[0].role)rest[0].role='secondary';if(rest[1]&&!rest[1].role)rest[1].role='exceptional';save()}
function roleLabel(p){return p?.role==='principal'?'Planning principal':p?.role==='secondary'?'Planning secondaire':p?.role==='exceptional'?'Planning exceptionnel':'Planning supplémentaire'}
function patchPlanning(){ensureRoles();const box=document.querySelector('#planningManagerV28');if(!box)return;const intro=box.querySelector('p');if(intro)intro.textContent='Un planning principal pour la base, un planning secondaire pour les périodes particulières, et un planning exceptionnel pour les cas à part.';const active=plans();box.querySelectorAll('.plan-card-v28').forEach((card,i)=>{card.querySelector('.role-v31')?.remove();const p=active[i];if(p)card.querySelector('summary')?.insertAdjacentHTML('afterend',`<div class="role-v31">${escapeHtml(roleLabel(p))}</div>`)});const add=[...box.querySelectorAll('button')].find(b=>/Créer un planning|Ajouter le planning/i.test(b.textContent||''));if(add){if(active.length>=3){add.style.display='none';if(!box.querySelector('.plan-limit-v31'))add.insertAdjacentHTML('afterend','<p class="muted compact plan-limit-v31">Les trois rôles de planning sont déjà présents.</p>')}else{add.style.display='';add.textContent=active.length===1?'+ Ajouter le planning secondaire':'+ Ajouter le planning exceptionnel'}}}
const oldCreate=window.createPlanV28;window.createPlanV28=()=>{ensureRoles();if(plans().length>=3){toast('Les trois rôles de planning sont déjà utilisés.','error');return}const before=new Set(plans().map(p=>p.id));oldCreate();const p=plans().find(x=>!before.has(x.id));if(p){p.role=plans().filter(x=>x.id!==p.id).length===1?'secondary':'exceptional';save();renderSettings()}};
function dayItem(k){const d=state.days[k],w=d?worked(d):null,future=k>dateKey(),today=k===dateKey();return `<div class="history-item"><div class="row"><strong>${escapeHtml(frenchDate(k))}${today?' · aujourd’hui':''}</strong><span>${future?'À venir':w==null?'À compléter':fmtPlainMinutes(w)}</span></div>${d?`<div class="muted">${escapeHtml(segmentText(d))}${w!=null?' · pause '+pauseFor(d)+' min':''}</div>${d.note?`<div>${escapeHtml(d.note)}</div>`:''}${!future?`<button class="ghost" onclick="editPastDay('${k}')">Modifier</button>`:''}`:''}</div>`}
function weeksHtml(){const arr=(state.historicalWeeks||[]).slice().sort((a,b)=>histOrder==='desc'?b.weekStart.localeCompare(a.weekStart):a.weekStart.localeCompare(b.weekStart));return `<div class="row"><span class="muted">Semaines consolidées</span><button class="ghost" onclick="toggleHistory31Order()">${histOrder==='desc'?'Plus récent d’abord':'Plus ancien d’abord'} ↕</button></div>${arr.length?arr.map(w=>`<div class="history-item"><div class="row"><strong>S${escapeHtml(String(w.week||''))} · ${escapeHtml(w.weekStart)}</strong><span>${fmtPlainMinutes(w.workedMinutes)}</span></div><div class="muted">Objectif ${fmtPlainMinutes(w.targetMinutes)} · écart ${fmtMinutes(w.deltaMinutes)}</div>${w.eventType?`<div>${escapeHtml(w.eventType)}</div>`:''}${w.note?`<div>${escapeHtml(w.note)}</div>`:''}</div>`).join(''):'<p class="muted">Aucune semaine consolidée.</p>'}`}
function years(){return[...new Set([...(state.historicalWeeks||[]).map(w=>w.weekStart?.slice(0,4)),...Object.keys(state.days||{}).map(k=>k.slice(0,4))].filter(Boolean))].sort().reverse()}
function annualHtml(){const ys=years();if(!histYear||!ys.includes(histYear))histYear=ys[0]||String(new Date().getFullYear());const weeks=(state.historicalWeeks||[]).filter(w=>w.weekStart?.startsWith(histYear)).slice().sort((a,b)=>histOrder==='desc'?b.weekStart.localeCompare(a.weekStart):a.weekStart.localeCompare(b.weekStart)),days=Object.keys(state.days||{}).filter(k=>k.startsWith(histYear)).sort((a,b)=>histOrder==='desc'?b.localeCompare(a):a.localeCompare(b));return `<div class="row"><div class="field" style="flex:1"><label>Année</label><select onchange="history31Year(this.value)">${ys.map(y=>`<option ${y===histYear?'selected':''}>${y}</option>`).join('')}</select></div><button class="ghost" onclick="toggleHistory31Order()">${histOrder==='desc'?'Plus récent d’abord':'Plus ancien d’abord'} ↕</button></div>${weeks.length?'<h3>Semaines</h3>'+weeks.map(w=>`<div class="history-item"><div class="row"><strong>S${escapeHtml(String(w.week||''))} · ${escapeHtml(w.weekStart)}</strong><span>${fmtPlainMinutes(w.workedMinutes)}</span></div><div class="muted">Objectif ${fmtPlainMinutes(w.targetMinutes)} · écart ${fmtMinutes(w.deltaMinutes)}</div></div>`).join(''):''}${days.length?'<h3>Journées détaillées</h3>'+days.map(dayItem).join(''):''}${!weeks.length&&!days.length?'<p class="muted">Aucune donnée pour cette année.</p>':''}`}
function body(){const b=document.querySelector('#history31Body');if(!b)return;document.querySelectorAll('.history-tabs-v31 button').forEach((x,i)=>x.classList.toggle('active',['recent','weeks','annual','adjust'][i]===histTab));if(histTab==='recent')b.innerHTML='<p class="muted compact">La semaine en cours, du lundi au dimanche.</p>'+weekDays(dateKey()).map(dayItem).join('');if(histTab==='weeks')b.innerHTML=weeksHtml();if(histTab==='annual')b.innerHTML=annualHtml();if(histTab==='adjust'){const rows=(state.balanceAdjustments||[]).slice().sort((a,z)=>(z.weekStart||'').localeCompare(a.weekStart||''));b.innerHTML=rows.length?rows.map(x=>`<div class="history-item"><div class="row"><strong>${escapeHtml(x.weekStart||'')}</strong><span>${fmtPlainMinutes(x.minutes||0)}</span></div>${x.note?`<div>${escapeHtml(x.note)}</div>`:''}</div>`).join(''):'<p class="muted">Aucune régularisation enregistrée.</p>'}}
function rebuildHistory(){const v=document.querySelector('#historyView');if(!v)return;const editor=v.querySelector('#historyEditor'),weekEditor=v.querySelector('#historicalWeekEditor');v.innerHTML=`<div class="card"><div class="history-tabs-v31"><button onclick="history31Tab('recent')">Récent</button><button onclick="history31Tab('weeks')">Semaines</button><button onclick="history31Tab('annual')">Années</button><button onclick="history31Tab('adjust')">Régularisations</button></div><div style="margin-bottom:10px"><button onclick="openHistoryEditor()">+ Ajouter / compléter une journée</button></div><div id="history31Body"></div></div>`;if(weekEditor)v.insertAdjacentElement('afterbegin',weekEditor);if(editor)v.insertAdjacentElement('afterbegin',editor);body()}
window.history31Tab=id=>{histTab=id;body();window.scrollTo({top:0,behavior:'auto'})};window.toggleHistory31Order=()=>{histOrder=histOrder==='desc'?'asc':'desc';body()};window.history31Year=y=>{histYear=y;body()};
function monthBounds(offset=0){const d=new Date();d.setMonth(d.getMonth()+offset,1);return[localKey(d),localKey(new Date(d.getFullYear(),d.getMonth()+1,0,12))]}
function renderDocs(){const v=document.querySelector('#docsView');if(!v)return;const[a,b]=monthBounds(0),y=new Date().getFullYear();v.innerHTML=`<div class="card"><h2>Extraire une période</h2><p class="muted compact">Pour les moments où « promis, j’ai fait mes heures » ne constitue pas un justificatif.</p><div class="row"><button class="ghost" onclick="docsShortcutV31('month')">Ce mois</button><button class="ghost" onclick="docsShortcutV31('prev')">Mois précédent</button><button class="ghost" onclick="docsShortcutV31('week')">Cette semaine</button></div><div class="weekgrid"><div class="field"><label>Du</label><input id="exportStart" type="date" value="${a}"></div><div class="field"><label>Au</label><input id="exportEnd" type="date" value="${b}"></div></div><div class="actions"><button onclick="runExportV11('pdf')">PDF de la période</button><button class="secondary" onclick="runExportV11('csv')">CSV de la période</button></div><p class="muted compact">Le raccourci mensuel couvre le mois civil. L’organisation des semaines reste basée sur leur lundi.</p></div><div class="card"><h2>Relevé annuel</h2><div class="field"><label>Année</label><input id="pdfYearV31" type="number" value="${y}"></div><button onclick="pdfAnnualV31()">PDF annuel</button></div><div class="card"><h2>Documents administratifs</h2><p class="muted compact">Les demandes administratives auront leur place ici lorsqu’elles produiront réellement un document.</p></div>`}
window.docsShortcutV31=kind=>{let r;if(kind==='month')r=monthBounds(0);if(kind==='prev')r=monthBounds(-1);if(kind==='week')r=[weekStart(dateKey()),weekDays(dateKey())[6]];document.querySelector('#exportStart').value=r[0];document.querySelector('#exportEnd').value=r[1]};window.pdfAnnualV31=()=>{const y=Number(document.querySelector('#pdfYearV31').value)||new Date().getFullYear();document.querySelector('#exportStart').value=`${y}-01-01`;document.querySelector('#exportEnd').value=`${y}-12-31`;runExportV11('annual')};
function patchHelp(){const s=document.querySelector('#settingsView');if(!s)return;const intro=[...s.querySelectorAll('.card')].find(c=>(c.textContent||'').includes('cimetière')),p=intro?.querySelector('.muted')||intro?.querySelector('p');if(p)p.innerHTML='Le guide grandit avec l’application. Parce qu’une fonction sans explication finit tôt ou tard dans le cimetière des « <em>trucs utiles mais flemme</em> ».';const cards=[...s.querySelectorAll('.card')],by=t=>cards.find(c=>c.querySelector('h2')?.textContent.trim()===t),general=by('Plannings'),habit=by('Planning habituel');let sec=by('Planning secondaire');if(!sec&&habit){sec=document.createElement('div');sec.className='card';sec.innerHTML='<h2>Planning secondaire et exceptionnel</h2><p>Le planning secondaire sert aux périodes particulières prévues, et le planning exceptionnel aux cas à part. Ils ne remplacent pas le planning principal en dehors de leurs périodes d’application.</p>';habit.insertAdjacentElement('afterend',sec)}if(general&&habit)habit.insertAdjacentElement('beforebegin',general);const ev=by('Événements à venir');if(ev)ev.innerHTML='<h2>Événements à venir</h2><p>Congés, congés exceptionnels, récupérations et autres événements peuvent être prévus à l’avance, en journée entière, le matin ou l’après-midi. Les heures proposées pour une demi-journée restent modifiables.</p><p>Les jours fériés légaux français sont ajoutés automatiquement au prévisionnel. Les périodes récurrentes restent saisies manuellement.</p>'}
const oldHelp=window.openHelpV21;window.openHelpV21=()=>{oldHelp();setTimeout(patchHelp,0)};
const oldSettings=renderSettings;renderSettings=function(){oldSettings();setTimeout(patchPlanning,0)};const oldHistory=renderHistory;renderHistory=function(){oldHistory();rebuildHistory()};const oldShow=showView;showView=function(id){oldShow(id);if(id==='historyView'){renderHistory();window.scrollTo({top:0,behavior:'auto'})}if(id==='docsView')renderDocs();if(id==='settingsView')setTimeout(patchPlanning,0)};const oldAll=renderAll;renderAll=function(){oldAll();if(!document.querySelector('#docsView')?.classList.contains('hidden'))renderDocs()};
if(!document.querySelector('#v31uistyle'))document.head.insertAdjacentHTML('beforeend','<style id="v31uistyle">.role-v31{font-size:12px;font-weight:700;margin:8px 0 4px}.history-tabs-v31{display:grid;grid-template-columns:repeat(4,1fr);gap:4px;margin-bottom:12px}.history-tabs-v31 button{font-size:11px;padding:8px 2px}.history-tabs-v31 button.active{font-weight:700;outline:2px solid currentColor}@media(max-width:380px){.history-tabs-v31{grid-template-columns:repeat(2,1fr)}}</style>');
ensureRoles();renderAll();
})();