/* Evenements : une seule interface, les regles metier vivent dans domain.js */
(function(){
let editingEventId='';
const eventById=id=>(state.config.futureEvents||[]).find(e=>e.id===id)||null;
function option(value,current){return `<option value="${value}" ${value===current?'selected':''}>${value}</option>`}
function partLabel(e){return e?.part==='morning'?' · matin':e?.part==='afternoon'?' · après-midi':''}
function todayCentralEvent(){return MH.eventsFor(dateKey(),true)[0]||null}
window.openEventEditorV31=(start='',end='',editId='')=>{editingEventId=editId||'';const old=editingEventId?eventById(editingEventId):null;const legacy=!old&&start===dateKey()&&state.days?.[dateKey()]?.eventType?state.days[dateKey()].eventType:'';const type=old?.type||legacy||'Congé',part=old?.part||'full',split=old?.splitTime||(part==='morning'?'13:30':part==='afternoon'?'12:00':''),comment=old?.comment||'',status=old?.status||'validated',s=old?.start||start,e=old?.end||end||start;document.querySelector('#eventDialogV31')?.remove();document.body.insertAdjacentHTML('beforeend',`<dialog id="eventDialogV31" class="modal-v28"><div class="row"><h2>${old?'Modifier':'Ajouter'} un événement</h2><button class="ghost" onclick="document.querySelector('#eventDialogV31').close()">Fermer</button></div><div class="field"><label>Type</label><select id="eventTypeV31">${['Congé','Congé exceptionnel','Récup','Arrêt maladie','Autre'].map(x=>option(x,type)).join('')}</select></div><div class="field"><label>Période</label><div class="row"><input id="eventV31Start" type="date" value="${escapeAttr(s)}" readonly><span>→</span><input id="eventV31End" type="date" value="${escapeAttr(e)}" readonly></div><button class="ghost" onclick="openRangePickerV28('eventV31Start','eventV31End')">Choisir la période</button></div><div class="field"><label>Partie de journée</label><select id="eventPartV31" onchange="eventPartChangeV31()"><option value="full" ${part==='full'?'selected':''}>Journée entière</option><option value="morning" ${part==='morning'?'selected':''}>Matin</option><option value="afternoon" ${part==='afternoon'?'selected':''}>Après-midi</option></select></div><div id="eventSplitWrapV31" class="field ${part==='full'?'hidden':''}"><label id="eventSplitLabelV31">Heure prévue</label><input id="eventSplitV31" type="time" value="${escapeAttr(split)}"></div><div class="field"><label>Commentaire (facultatif)</label><textarea id="eventCommentV31">${escapeHtml(comment)}</textarea></div><div class="field"><label>Statut</label><select id="eventStatusV31"><option value="validated" ${status==='validated'?'selected':''}>Déjà validé</option><option value="pending" ${status==='pending'?'selected':''}>En attente de validation</option></select></div><div class="actions"><button onclick="saveEventV31()">Enregistrer l’événement</button>${old?`<button class="secondary" onclick="removeEditingEventV31()">Retirer</button>`:''}</div></dialog>`);eventPartChangeV31();document.querySelector('#eventDialogV31').showModal()};
window.eventPartChangeV31=()=>{const part=document.querySelector('#eventPartV31')?.value,wrap=document.querySelector('#eventSplitWrapV31'),i=document.querySelector('#eventSplitV31'),l=document.querySelector('#eventSplitLabelV31');wrap?.classList.toggle('hidden',part==='full');if(part==='morning'){l.textContent='Reprise du travail prévue';if(!i.value)i.value='13:30'}if(part==='afternoon'){l.textContent='Fin du travail prévue';if(!i.value)i.value='12:00'}if(part==='full'&&i)i.value=''};
window.saveEventV31=()=>{const start=document.querySelector('#eventV31Start').value,end=document.querySelector('#eventV31End').value,part=document.querySelector('#eventPartV31').value,split=part==='full'?'':document.querySelector('#eventSplitV31').value;if(!start||!end||end<start){toast('Choisis une période valide.','error');return}if(part!=='full'&&!split){toast('Renseigne l’heure de découpage.','error');return}const status=document.querySelector('#eventStatusV31').value;MH.saveEvent({type:document.querySelector('#eventTypeV31').value,comment:document.querySelector('#eventCommentV31').value.trim(),start,end,part,splitTime:split,status},editingEventId);if(start===dateKey()&&state.days?.[dateKey()]?.eventType){state.days[dateKey()].eventType='';save()}editingEventId='';document.querySelector('#eventDialogV31')?.close();renderAll();toast('✓ Événement enregistré.')};
window.removeEditingEventV31=()=>{if(editingEventId)MH.removeEvent(editingEventId);editingEventId='';document.querySelector('#eventDialogV31')?.close();renderAll();toast('✓ Événement retiré.')};
window.openEventPicker=()=>{const k=dateKey(),e=todayCentralEvent();openEventEditorV31(k,k,e?.id||'')};
window.setDayEvent=()=>window.openEventPicker();
function patchTodayEventAccess(){const v=document.querySelector('#todayView');if(!v)return;v.querySelector('#eventPicker')?.remove();const k=dateKey(),central=MH.eventsFor(k,true),legacy=state.days?.[k]?.eventType||'';const button=[...v.querySelectorAll('button')].find(b=>(b.getAttribute('onclick')||'').includes('openEventPicker'));if(button)button.textContent=central.length?'Modifier l’événement / absence':'Événement / absence';const first=v.querySelector('.card');if(first){const row=first.querySelector('.row');if(row){[...row.querySelectorAll('.chip')].forEach((c,i)=>{if(i>0&&(c.textContent===legacy||central.some(e=>c.textContent.startsWith(e.type))))c.remove()});for(const e of central){const span=document.createElement('span');span.className='chip';span.textContent=e.type+partLabel(e)+(e.status==='pending'?' · en attente':'');row.appendChild(span)}}}}
const previousToday=renderToday;renderToday=function(){previousToday();patchTodayEventAccess()};
const previousAll=renderAll;renderAll=function(){previousAll();patchTodayEventAccess()};
window.openEventEditorV28=window.openEventEditorV31;
window.saveEventV28=window.saveEventV31;
patchTodayEventAccess();
})();