/* v32 modification ponctuelle d'une journee */
(function(){
const byId=id=>(state.config.dayTypes||[]).find(t=>t.id===id);
function activePlan(k){const periods=(state.config.planningPeriods||[]).filter(x=>x.start<=k&&x.end>=k&&x.status==='validated').sort((a,b)=>b.start.localeCompare(a.start));return (state.config.planningProfiles||[]).find(p=>p.id===periods[0]?.profileId)||(state.config.planningProfiles||[]).find(p=>p.id==='normal')||(state.config.planningProfiles||[])[0]}
function planDays(p,k){if(!p)return{};const versions=(p.versions||[]).filter(v=>v.status==='validated'&&v.effectiveFrom<=k).sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom));return versions.length?versions[versions.length-1].days:(p.days||{})}
function plannedType(k){const p=activePlan(k),days=planDays(p,k),dow=String(new Date(k+'T12:00:00').getDay());return byId(days[dow])||null}
function minutesOf(t){if(!t)return 0;if(Number.isFinite(Number(t.minutes)))return Number(t.minutes);return 0}
function clock(s){if(!s)return null;const p=s.split(':').map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null}
function halfMinutes(t,part,boundary){const total=minutesOf(t),a=clock(t?.start),b=clock(t?.end),x=clock(boundary);if(a==null||b==null||x==null)return Math.round(total/2);if(part==='morning')return Math.max(0,Math.min(b,x)-a);return Math.max(0,b-Math.max(a,x))}
function ensure(){state.config=state.config||{};state.config.dayOverridesV32=state.config.dayOverridesV32||{}}
window.dayForecastOverrideV32=k=>{ensure();const o=state.config.dayOverridesV32[k];if(!o)return null;const base=byId(o.dayTypeId)||plannedType(k);if(o.part==='full')return minutesOf(base);return halfMinutes(base,o.part,o.boundary)};
function typeOptions(selected){return (state.config.dayTypes||[]).map(t=>`<option value="${escapeAttr(t.id)}" ${t.id===selected?'selected':''}>${escapeHtml(t.code||'')} · ${escapeHtml(t.name||'')}</option>`).join('')}
window.openDayForecastEditorV32=k=>{ensure();const old=state.config.dayOverridesV32[k]||{},planned=plannedType(k),selected=old.dayTypeId||planned?.id||'',part=old.part||'full';document.querySelector('#dayForecastDialogV32')?.remove();document.body.insertAdjacentHTML('beforeend',`<dialog id="dayForecastDialogV32" class="modal-v28"><div class="row"><div><h2>Modifier la journée</h2><div class="muted">${escapeHtml(frenchDate(k))}</div></div><button class="ghost" onclick="document.querySelector('#dayForecastDialogV32').close()">Fermer</button></div><div class="field"><label>Journée type</label><select id="dayTypeV32">${typeOptions(selected)}</select></div><div class="field"><label>Partie prévue</label><select id="dayPartV32" onchange="dayPartChangeV32()"><option value="full" ${part==='full'?'selected':''}>Journée entière</option><option value="morning" ${part==='morning'?'selected':''}>Matin seulement</option><option value="afternoon" ${part==='afternoon'?'selected':''}>Après-midi seulement</option></select></div><div id="dayBoundaryWrapV32" class="field"><label id="dayBoundaryLabelV32"></label><input id="dayBoundaryV32" type="time" value="${escapeAttr(old.boundary||(part==='morning'?'12:00':part==='afternoon'?'13:30':''))}"></div><p class="muted compact">Cette modification ne change pas ton planning ni la journée type d’origine. Elle vaut uniquement pour cette date.</p><div class="actions"><button onclick="saveDayForecastV32('${k}')">Enregistrer</button>${old.dayTypeId?`<button class="secondary" onclick="removeDayForecastV32('${k}')">Revenir au planning</button>`:''}</div></dialog>`);dayPartChangeV32();document.querySelector('#dayForecastDialogV32').showModal()};
window.dayPartChangeV32=()=>{const part=document.querySelector('#dayPartV32')?.value,wrap=document.querySelector('#dayBoundaryWrapV32'),label=document.querySelector('#dayBoundaryLabelV32'),input=document.querySelector('#dayBoundaryV32');wrap?.classList.toggle('hidden',part==='full');if(part==='morning'){label.textContent='Fin prévue';if(!input.value)input.value='12:00'}if(part==='afternoon'){label.textContent='Début prévu';if(!input.value)input.value='13:30'}if(part==='full'&&input)input.value=''};
window.saveDayForecastV32=k=>{ensure();const part=document.querySelector('#dayPartV32').value,boundary=part==='full'?'':document.querySelector('#dayBoundaryV32').value;if(part!=='full'&&!boundary){toast('Renseigne l’heure prévue.','error');return}state.config.dayOverridesV32[k]={dayTypeId:document.querySelector('#dayTypeV32').value,part,boundary,updatedAt:dateKey()};save();document.querySelector('#dayForecastDialogV32')?.close();renderAll();toast('✓ Journée prévue modifiée.')};
window.removeDayForecastV32=k=>{ensure();delete state.config.dayOverridesV32[k];save();document.querySelector('#dayForecastDialogV32')?.close();renderAll();toast('✓ Retour au planning prévu.')};
window.editChosenDayV28=k=>{document.querySelectorAll('#weekDialogV28,#dayChoiceV28').forEach(x=>{try{x.close()}catch(e){}});openDayForecastEditorV32(k)};
ensure();
})();