/* Mes heures v9: journées types, planning souple, événements et alertes */
(function(){
const WD=[['1','Lundi'],['2','Mardi'],['3','Mercredi'],['4','Jeudi'],['5','Vendredi'],['6','Samedi'],['0','Dimanche']];
function uid(){return 't'+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function ensureV9(){const c=state.config;c.personName=c.personName||'';c.balanceAlertNegative=Number.isFinite(Number(c.balanceAlertNegative))?Number(c.balanceAlertNegative):20;c.balanceAlertPositive=Number.isFinite(Number(c.balanceAlertPositive))?Number(c.balanceAlertPositive):20;c.contractEnd=c.contractEnd||'';
if(!Array.isArray(c.dayTypes)||!c.dayTypes.length){const v=scheduleFor(dateKey()),sc=v.schedule||currentSchedule;const normal={id:'normal',name:'Normal',start:'09:00',end:'18:30',minutes:540,pause:Number(c.pause||30)};const th={id:'normal-jeudi',name:'Normal jeudi',start:'09:00',end:'18:30',minutes:480,pause:Number(c.pause||30)};const rest={id:'repos',name:'Repos',start:'',end:'',minutes:0,pause:0};c.dayTypes=[normal,th,rest];c.weekPlan={'1':'normal','2':'normal','3':'normal','4':'normal-jeudi','5':'repos','6':'repos','0':'repos'};for(const [n] of WD){const s=sc[n];if(s&&s.minutes>0&&!c.weekPlan[n])c.weekPlan[n]='normal'}}
c.weekPlan=c.weekPlan||{'1':'normal','2':'normal','3':'normal','4':'normal','5':'repos','6':'repos','0':'repos'};for(const d of Object.values(state.days)){d.eventType=d.eventType||'';d.dayTypeId=d.dayTypeId||''}save()}
ensureV9();
function typeById(id){return state.config.dayTypes.find(t=>t.id===id)}
function defaultTypeFor(k){const dow=String(new Date(k+'T12:00:00').getDay());return typeById(state.config.weekPlan[dow])||null}
function dayTypeFor(k){const d=state.days[k];return typeById(d?.dayTypeId)||defaultTypeFor(k)}
function eventCredit(k){const d=state.days[k];if(!d?.eventType)return null;const base=Number(dayTypeFor(k)?.minutes||0);if(['Congé','Arrêt maladie','Férié'].includes(d.eventType))return base;if(d.eventType==='Récup')return 0;return null}
const oldExpectedFor=expectedFor;expectedFor=function(k){const credit=eventCredit(k);if(credit!=null)return credit;const t=dayTypeFor(k);return t?Number(t.minutes||0):oldExpectedFor(k)};
weekTarget=function(k=dateKey()){const v=scheduleFor(k);return Math.round(Number(v.weeklyTarget??state.config.weeklyTarget??35)*60)};
const oldWeekWorked=weekWorked;weekWorked=function(k=dateKey()){let total=0;for(const x of weekDays(k)){const d=state.days[x],credit=eventCredit(x),w=worked(d);if(credit!=null&&['Congé','Arrêt maladie','Férié'].includes(d?.eventType))total+=credit;else if(w!=null)total+=w;if(d?.retainedMinutes!=null)total+=Number(d.retainedMinutes)}return total};
function typeLabel(k){const t=dayTypeFor(k);return t?.name||'Sans type'}
function repere(k){const t=dayTypeFor(k);return t?.start&&t?.end?`${t.start} → ${t.end}`:'Pas d’horaire repère'}
function alertBox(balance){const c=state.config,neg=Math.abs(Number(c.balanceAlertNegative||0))*60,pos=Math.abs(Number(c.balanceAlertPositive||0))*60;let msg='';if(neg&&balance<=-neg)msg=`⚠️ Ton solde a dépassé ton seuil de -${fmtPlainMinutes(neg)}.`;if(pos&&balance>=pos)msg=`⚠️ Ton solde a dépassé ton seuil de +${fmtPlainMinutes(pos)}.`;if(c.contractEnd){const end=new Date(c.contractEnd+'T12:00:00'),now=new Date(dateKey()+'T12:00:00'),weeks=Math.max(1,Math.ceil((end-now)/(7*86400000)));if(end>=now&&Math.abs(balance)>=30){const per=Math.round(Math.abs(balance)/weeks);msg+=(msg?' ':'')+`Pour viser zéro au ${new Intl.DateTimeFormat('fr-FR').format(end)} : environ ${balance<0?'+':'-'}${fmtPlainMinutes(per)} par semaine.`}}return msg?`<div class="alertline">${escapeHtml(msg)}</div>`:''}
function dayTypeButtons(k){const current=dayTypeFor(k)?.id||'';return `<div class="type-grid">${state.config.dayTypes.map(t=>`<button class="type-btn ${t.id===current?'active':''}" onclick="chooseDayType('${t.id}')">${escapeHtml(t.name)}</button>`).join('')}</div>`}
renderToday=function(){const k=dateKey(),d=dayObj(k),w=worked(d),ss=validSegments(d),open=openSegment(d),t=dayTypeFor(k),evt=d.eventType||'';let actions=open?`<button onclick="finishWorkNow()">Je termine cette plage</button><button class="secondary" onclick="setEndTime()">Je suis déjà partie</button>`:ss.length?`<button onclick="resumeWorkNow()">Je reprends le travail</button><button class="secondary" onclick="editTodaySegments()">Modifier les plages</button>`:`<button onclick="startWorkNow()">Je commence maintenant</button><button class="secondary" onclick="setStartTime()">Je suis déjà arrivée</button>`;const ww=weekWorked(k),wt=weekTarget(k),remain=wt-ww,bal=balanceNow(k);document.querySelector('#todayView').innerHTML=`<div class="card"><div class="date">${frenchDate(k)}</div><div class="row"><span class="chip">${escapeHtml(typeLabel(k))}</span>${evt?`<span class="chip">${escapeHtml(evt)}</span>`:''}</div><div class="big">${w==null?(open?'En cours':'0h00'):fmtPlainMinutes(w)}</div><div class="muted">Repère : <strong>${escapeHtml(repere(k))}</strong>${t?` · journée type ${fmtPlainMinutes(t.minutes)}`:''}</div><div class="actions">${actions}</div></div><div class="card"><h2>Aujourd’hui</h2><div class="field"><label>Type de journée</label>${dayTypeButtons(k)}</div><button class="ghost" onclick="openEventPicker()">${evt?'Modifier l’événement / absence':'Événement / absence'}</button><div id="eventPicker" class="hidden field"><label>Événement</label><div class="type-grid">${['Congé','Arrêt maladie','Récup','Férié','Autre'].map(x=>`<button class="type-btn" onclick="setDayEvent('${x}')">${x}</button>`).join('')}<button class="type-btn" onclick="setDayEvent('')">Aucun</button></div></div>${ss.length?`<div class="field"><label>Plages de travail</label>${ss.map((s,i)=>`<div class="time-row row"><span>Plage ${i+1}</span><strong>${s.start} → ${s.end||'en cours'}</strong></div>`).join('')}</div>${pauseEditor(d)}`:''}<div class="field"><label>Remarque / justification</label><textarea id="note" placeholder="Réunion, formation, dossier…">${escapeHtml(d.note||'')}</textarea></div><button class="ghost" onclick="saveNote()">Enregistrer la remarque</button></div><div class="card"><h2>Cette semaine</h2><div class="row"><span>Pointé / retenu</span><strong>${fmtPlainMinutes(ww)}</strong></div><div class="row"><span>Objectif</span><strong>${fmtPlainMinutes(wt)}</strong></div><div class="time-row row"><span>${remain>0?'Reste pour atteindre 35h':'Écart semaine'}</span><strong class="${remain<=0?'positive':''}">${remain>0?fmtPlainMinutes(remain):fmtMinutes(-remain)}</strong></div><div class="time-row row"><span>Solde cumulé indicatif</span><strong class="${bal>=0?'positive':'negative'}">${fmtMinutes(bal)}</strong></div>${alertBox(bal)}</div>${currentWeekEditor(k)}`}
window.chooseDayType=id=>{const d=dayObj();d.dayTypeId=id;const t=typeById(id);if(t&&(!validSegments(d).length))d.pauseMinutes=Number(t.pause||0);save();renderAll();toast(`✓ Aujourd’hui : ${t?.name||'type modifié'}.`)};
window.openEventPicker=()=>document.querySelector('#eventPicker')?.classList.toggle('hidden');window.setDayEvent=e=>{const d=dayObj();d.eventType=e;save();renderAll();toast(e?`✓ ${e} enregistré pour aujourd’hui.`:'✓ Événement retiré.')};
function typeEditor(){return `<div class="card"><h2>Journées types</h2><p class="muted compact">Les horaires servent de repère. La durée sert au calcul et les pointages restent la réalité.</p>${state.config.dayTypes.map(t=>`<div class="daytype-card"><div class="row"><strong>${escapeHtml(t.name)}</strong><button class="ghost" onclick="deleteDayType('${t.id}')">Supprimer</button></div><div class="muted">${t.start&&t.end?t.start+' → '+t.end:'sans horaire'} · ${fmtPlainMinutes(t.minutes)} · pause ${t.pause||0} min</div></div>`).join('')}<h3>Ajouter un type</h3><div class="field"><label>Nom</label><input id="newTypeName" placeholder="ACM, MJC, OF…"></div><div class="weekgrid"><div class="field"><label>Début repère</label><input id="newTypeStart" type="time"></div><div class="field"><label>Fin repère</label><input id="newTypeEnd" type="time"></div></div><div class="field"><label>Durée attendue (heures)</label><input id="newTypeHours" type="number" min="0" step="0.25"></div><div class="field"><label>Pause habituelle (minutes)</label><input id="newTypePause" type="number" min="0" step="5" value="${state.config.pause||30}"></div><button onclick="addDayType()">Ajouter la journée type</button></div>`}
function weekPlanEditor(){return `<div class="card"><h2>Planning habituel</h2><p class="muted compact">C’est ton repère de disponibilité. Une journée peut être remplacée ponctuellement depuis Aujourd’hui.</p><div class="weekly-plan">${WD.map(([n,label])=>`<strong>${label}</strong><select id="wp${n}">${state.config.dayTypes.map(t=>`<option value="${t.id}" ${state.config.weekPlan[n]===t.id?'selected':''}>${escapeHtml(t.name)}</option>`).join('')}</select>`).join('')}</div><button onclick="saveWeekPlan()" style="margin-top:14px">Enregistrer le planning</button></div>`}
renderSettings=function(){const c=state.config;document.querySelector('#settingsView').innerHTML=`<div class="card"><h2>Mon profil</h2><div class="field"><label>Nom et prénom</label><input id="personName" value="${escapeAttr(c.personName||'')}" placeholder="Champ libre"></div><div class="field"><label>Emploi / structure</label><input id="jobName" value="${escapeAttr(c.employmentName||'')}"></div><div class="field"><label>Début</label><input id="jobStart" type="date" value="${c.employmentStart||''}"></div><div class="field"><label>Fin de contrat (facultatif)</label><input id="contractEnd" type="date" value="${c.contractEnd||''}"></div><div class="field"><label>Objectif hebdomadaire</label><input id="target" type="number" step="0.25" value="${c.weeklyTarget||35}"></div><div class="field"><label>Pause par défaut</label><input id="pause" type="number" value="${c.pause||30}"></div><button onclick="saveV9Settings()">Enregistrer</button></div>${typeEditor()}${weekPlanEditor()}<div class="card"><h2>Alertes de solde</h2><p class="muted compact">L’appli prévient avant que le compteur ne parte faire sa vie tout seul.</p><div class="field"><label>Alerte si je descends sous -… h</label><input id="alertNeg" type="number" min="0" step="1" value="${c.balanceAlertNegative}"></div><div class="field"><label>Alerte si je dépasse +… h</label><input id="alertPos" type="number" min="0" step="1" value="${c.balanceAlertPositive}"></div><button onclick="saveAlerts()">Enregistrer les alertes</button></div><div class="card"><h2>Reprendre un historique</h2><input id="historyFile" type="file" accept="application/json,.json"><button class="secondary" onclick="importHistory()">Importer l’historique</button></div><div class="card"><h2>Agenda professionnel</h2><div class="field"><label>Adresse de l’agenda</label><input id="calUrl" type="url" value="${escapeAttr(c.calendarUrl||'')}"></div><p class="muted compact">Adresse enregistrée seulement. La lecture automatique n’est pas encore active.</p><button class="secondary" onclick="saveCalendar()">Enregistrer l’adresse</button></div>`}
window.saveV9Settings=()=>{const c=state.config;c.personName=document.querySelector('#personName').value.trim();c.employmentName=document.querySelector('#jobName').value.trim()||'Mon emploi';c.employmentStart=document.querySelector('#jobStart').value;c.contractEnd=document.querySelector('#contractEnd').value;c.weeklyTarget=Number(document.querySelector('#target').value)||0;c.pause=Number(document.querySelector('#pause').value)||0;const v=scheduleFor(dateKey());v.weeklyTarget=c.weeklyTarget;save();renderAll();toast('✓ Profil et objectif enregistrés.')};
window.addDayType=()=>{const name=document.querySelector('#newTypeName').value.trim(),hours=Number(document.querySelector('#newTypeHours').value);if(!name||!Number.isFinite(hours)){toast('Donne un nom et une durée à la journée type.','error');return}state.config.dayTypes.push({id:uid(),name,start:document.querySelector('#newTypeStart').value,end:document.querySelector('#newTypeEnd').value,minutes:Math.round(hours*60),pause:Math.max(0,Number(document.querySelector('#newTypePause').value)||0)});save();renderSettings();toast(`✓ Journée type « ${name} » ajoutée.`)};
window.deleteDayType=id=>{if(state.config.dayTypes.length<=1){toast('Il faut garder au moins un type de journée.','error');return}const t=typeById(id);if(!confirm(`Supprimer la journée type « ${t?.name} » ?`))return;state.config.dayTypes=state.config.dayTypes.filter(x=>x.id!==id);const fallback=state.config.dayTypes[0].id;for(const [n] of WD)if(state.config.weekPlan[n]===id)state.config.weekPlan[n]=fallback;save();renderSettings();toast('✓ Journée type supprimée.')};
window.saveWeekPlan=()=>{for(const[n]of WD)state.config.weekPlan[n]=document.querySelector('#wp'+n).value;save();renderAll();toast('✓ Planning habituel enregistré.')};window.saveAlerts=()=>{state.config.balanceAlertNegative=Math.max(0,Number(document.querySelector('#alertNeg').value)||0);state.config.balanceAlertPositive=Math.max(0,Number(document.querySelector('#alertPos').value)||0);save();renderAll();toast('✓ Seuils d’alerte enregistrés.')};
const oldHistoryEditor=historyEditor;historyEditor=function(k){return oldHistoryEditor(k).replace('<div class="field"><label>Remarque</label>',`<div class="field"><label>Événement / absence</label><select id="histEvent"><option value="">Aucun</option>${['Congé','Arrêt maladie','Récup','Férié','Autre'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Remarque</label>`)};
const oldLoadPastDay=window.loadPastDay;window.loadPastDay=()=>{oldLoadPastDay();const k=document.querySelector('#histDate')?.value,d=state.days[k];if(document.querySelector('#histEvent'))document.querySelector('#histEvent').value=d?.eventType||''};
const oldSavePastDay=window.savePastDay;window.savePastDay=()=>{const k=document.querySelector('#histDate')?.value,evt=document.querySelector('#histEvent')?.value||'';oldSavePastDay();if(state.days[k]){state.days[k].eventType=evt;save();renderAll();showView('historyView')}};
const oldHistoricalWeekEditor=historicalWeekEditor;historicalWeekEditor=function(){return oldHistoricalWeekEditor().replace('<option value="Formation" >Formation</option>','')};
renderAll();
})();